{{- if .Values.bootstrapAdmin.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.bootstrapAdmin.existingSecret | quote }}
type: Opaque
data:
  username: {{ .Values.bootstrapAdmin.username | b64enc }}
  password: {{ .Values.bootstrapAdmin.password | b64enc }}
{{- end }}
