backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-order
    tag: ""

  nameOverride: order
  fullnameOverride: order
  databaseName: order
  ingress:
    enabled: true
    host: "{{ .Values.global.apiHost }}"
    path: /order
  extraVolumes:
    - name: order-application-config
      configMap:
        name: order-application-configmap
  extraVolumeMounts:
    - name: order-application-config
      mountPath: /opt/yas/order
  extraApplicationConfigPaths:
    - /opt/yas/order/order-application.yaml  
