global:
  environment: dev
  domain: yasdevops.dev
  apiHost: api.local.test
  apiUrl: http://api.local.test
  identityHost: identity.local.test
  identityScheme: http
  identityUrl: http://identity.local.test
  backofficeHost: backoffice.local.test
  storefrontHost: storefront.local.test
  storefrontUrl: http://storefront.local.test
backend:
  image:
    tag: ""
ui:
  image:
    tag: ""
