ui:
  image:
    repository: ghcr.io/nashtech-garage/yas-backoffice
    tag: ""
  nameOverride: backoffice-ui
  fullnameOverride: backoffice-ui
  ingress:
    enabled: true
    host: "{{ .Values.global.backofficeHost }}"
    path: /
