{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.existingSecret | quote }}
  labels:
    application: spilo
    cluster-name: postgresql
    team: acid
type: Opaque
data:
  password: {{ .Values.password | b64enc }}
  username: {{ .Values.username | b64enc }}
{{- end }}
