domain: yasdevops.dev
postgresql:
  replicas: 1
  username: yasadminuser
  # Password must be provided via SealedSecret named: yas-postgresql-credentials-secret
  password: ""
kafka:
  replicas: 1
zookeeper:
  replicas: 1
elasticsearch:
  replicas: 1
  username: yas
  # Password must be provided via SealedSecret named: yas-elasticsearch-credentials-secret
  password: ""
keycloak:
  bootstrapAdmin:
    username: admin
    # Password must be provided via SealedSecret named: keycloak-credentials
    password: ""
  backofficeRedirectUrl: https://backoffice.yasdevops.dev
  storefrontRedirectUrl: https://storefront.yasdevops.dev
grafana:
  username: admin
  # Password must be provided via SealedSecret named: grafana-admin-credentials
  password: ""
redis:
  # Password must be provided via SealedSecret named: yas-redis-credentials-secret
  password: ""
