global:
  environment: dev
  domain: yasdevops.dev
  backofficeHost: backoffice.yasdevops.dev

backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-backoffice-bff
    tag: ""

  nameOverride: backoffice-bff
  fullnameOverride: backoffice-bff
  deployment:
    annotations:
      configmap.reloader.stakater.com/reload: "yas-gateway-routes-config-configmap,backoffice-bff-extra-configmap"
  ingress:
    enabled: true
    host: "{{ .Values.global.backofficeHost }}"
    path: /api
    paths:
      - path: /api
        pathType: Prefix
      - path: /oauth2
        pathType: Prefix
      - path: /login
        pathType: Prefix
      - path: /logout
        pathType: Prefix
      - path: /authentication
        pathType: Prefix
      - path: /authorized
        pathType: Prefix
      - path: /error
        pathType: Prefix
  extraEnvs:
    - name: SPRING_PROFILES_ACTIVE
      value: "{{ .Values.global.environment }}"
    - name: UI_HOST
      value: http://backoffice-ui:3000
  extraEnvFroms:
    - secretRef:
        name: yas-keycloak-credentials-secret
    - secretRef:
        name: yas-redis-credentials-secret
  extraVolumes:
    - name: yas-gateway-routes-config
      configMap:
        name: yas-gateway-routes-config-configmap
    - name: backoffice-bff-extra-config
      configMap:
        name: backoffice-bff-extra-configmap
  extraVolumeMounts:
    - name: yas-gateway-routes-config
      mountPath: /opt/yas/gateway-routes-config
    - name: backoffice-bff-extra-config
      mountPath: /opt/yas/extra-config
  extraApplicationConfigPaths:
    - /opt/yas/gateway-routes-config/gateway-routes-config.yaml
    - /opt/yas/extra-config/backoffice-bff-extra-config.yaml
  
