backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-tax
    tag: ""

  nameOverride: tax
  fullnameOverride: tax
  databaseName: tax
  ingress:
    enabled: true
    host: "{{ .Values.global.apiHost }}"
    path: /tax
    pathType: Prefix
