---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: grafana-admin-credentials
  namespace: yas-stage
spec:
  encryptedData:
    password: AgAUZo1QMQKceEejm5uqPLjgnN9/GjcO+ZM4a7Nav+qENdW01FwyPfvJ3Admge2VMQhTWTTBH9zMn6EyuQKChcyjCnBuAeSF5bNecdhkTnbfaVcinh74I/GUFtoGM9HD6FAV57zAzoE04ij3LG+mno8Sec/IB1i8MRjjFIAblAY3W5fTFDSvqfyqusyGIPbbPCznqhFtLFVsfZWHKpaop+AYBVUyD/rJzqsazqPBp89LVc/P9fH+yrG74KC1hDXGxnAG+tA3OqzeqoHrMd6wDcC+i8G+S3CUpho4LXnG0w13t1SPxB1AKuYezFykn8VfcugGHUGNLz/QM+jeu3mvtHNnIDHlt3WbOinIbGlUZrVEpAhvY46oTKviLHMJrWCuqnocOQ4shtaWv5Ko0mrbXD0uVc0ysxxmHlZN+R9L96PLIjrdKjaFg/AR2lIYKG5cFMQfvTPrEne6KK0cbYAXGl5wZEfGqiN00HHjTryu2J0arhxZek/p0HoYbiElfqyHsuKwHX4VFJAtXjAjwzSrrC1EbSRthcpa0aYAK80hf38iGE1YGoRojWPcaIhLA2LITvOIALmxgmEgMOg9ker6q7OL2bUBxcNX/aEjm+P5MVWftlLs3YOQzYp0qP++6P+UYx/RcHHHbFKbpXCJ1lU2AoqkHziFImNBwVkl1UkvznAOVvf7/AvgEBhhvq51Lb5eewNpLfz4tQ==
    username: AgBQ5pvxTdW+xnp2tXMnjiOuqYMTk2uM5XZ5UwXpN2RS6TOuCLcZ6pmbqaOTPcel6n24PZ2ne9iapuR/a+cO7SZ40y5RVGpj/C/gorjLGuLd9SiKpRNBtflRxWuaqBMNLDgAkvjkpJEbBPKRILcgib+mvQxnYo3va8GvjuvIX0pCPdfBHlnAU6klyN6QC9hFKa7kfnRL2SCQqAFSHvZchwTHYMq4Fi7qE/Bw13wqReWGap4S3pAefOiW9+gzGHg5EAKREhZ94orbzsTBLPwtpn0YDufDvaBd1pYp+pqhI1Zpa1ZmNG57lKjZ96EFg0dqDAX0tmPUOcrYAVQCuD9YbxeszOwVSR9VvGY0eVCLoW9F2oIFzfnTJ26iPap8RewHRVGwHcY6j7PHevCIIjYt/AgZ8c/vdtab0aimYRuKXiubDh6aRX/U7eD1llQFnaPHRTg5imLlBd0Mf638JrYYTcrxhcbStc3qyDPBsvzDp9f2t6Af69ZEqI00JOYof5Ml8aadEoGDlQC7O5P1yzqGl+JpkMTq7pejR4ZUz2FcsA/FPHkJzBYPbbR/dBDzit2EPWJuMsHjvJWHzPqeVdxsqc+6QBi8qyrHd4pc3ezP6yLSx0ptPcidFgRQIY+LOi3v6YI5I1tOGeaGByjMyBwf+xoJf7sxPjuinfFvQLET1YMBUeXkSajhA9MdY7y6uAlBmXA9Ua1XxQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: grafana-admin-credentials
      namespace: yas-stage
