---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: grafana-admin-credentials
  namespace: yas-stage
spec:
  encryptedData:
    password: AgCCDPlUq7cYwCcLZEqRSABCw5GmfrGEKSOXxDx3xJUwlPv/tuocj2MfdzbT4O79uot/HDK7vXA7QSKXe7XlUNawlU1A8jhKKSpCpk0TOAGqI2h2HToAu69oxTFWpR0boSU5FbcVoAwnxr970/jzL1xQyUuHfNirHI+kGfLgqd5XUX4uQZnJPHW4REwaw21ULRz0FQsbzvAjvM7Xpnk1z+tCeeVMWGSR9rQX2vIyJ7FPRXhYDGecsLjq2EYWmsPmHSeWNbmma7r/LRCsot1xR45dKEzoN7zFnA39NHdzSsgrcVY5LN7IVdDOKjuNWmbgtaxk76uyi4k3VzRfAiHUwSbRj7LbaOGvFP6hcoqNVJK/lsp7b0Eqn+oGQqNxGeiWT/5eurFkLKXumq2v8ZMgZ2v3u1PmKH43QV120/diJyFFAa3W70pAYVfHWKkz5ZZEWb+XG/JdyqCU2K9UBM1q41AFVQzg20xQ5AheFMMcuMGvaL6q8UZrODG7ZJZCs1IfOeGCB5b7UhcC5/WZzIAehbxqc2R30aZVXIUyXh4+vVd3rF+LuJLsz6dIUo6/5v7IlkrPSeDJNU7IP/8Kwb0f4Bi08WoBjuvD8vbsZUykhRshM/Kv7g1ioHKeSK70AP9ukUNPmW2td7rLqNZ0xr/OxRVpxsHR+o6+2DLVF2TFKz47PpRn4I6SUxsujL+8FjHxGCr3+oQz1g==
    username: AgByJ3BiVk8DG4aG+EKHwDpG0ZJSiPC9GKckHfArbZ2UGFsQR04kn8vdSuev0By/qKOvny69cUPfcucxaZf+Q0IAyMeoF/lNoEbyTmG5CQu74NEApoovZwyf51Tv3kpQiINHDWTuwDLSuUcfFwDVvGW48uT9vDl5qs/nB4H4JAuYKSBQ/GyAaJpdgukKLzxuy+cJaCR21HYMgw2yjLB2KQ9vwj1Hs+9sa5furnPm/xq+uPBWHBTbf3oSNnnRUZ7uJQnF28HwBB32ry+0An+lHvn10/m1vapI5QUDeByPUUytvxjvUdvLXiPtEb2n0OVsUpXMoJwNiZm2gS69R/X+wXROPKjIgXbgyu+ERfsyXav35zr6rYJW5UIQuUD2bUvb8CobgPLsMr8OkaoBrW5yZRIbx5grsnAKXygjVScmaak5WcQo1Um56uuYr1IeKmjskyli+d33pPhVfdR5uWaHLvFzr0g0zUM7vmDF7QrHdL1Ddypegr63OJ5s1JuZKbDJ7Yp9deOtS8IxdNhcbouyabz6n1aher/Z8v40E2PI1xFEReALrHZTQlEOXfwLuhr/tb9cu36KCU8iPkQvLAhCaxMNFwOMXahNk7gFpr+Urz/XKjWuK4aRLrRQ+uDR9l+SyYFO6Yq6J/I9iCUERHZAV9aQaaueU4ET1gltNUuBGHNMFaRO+2lDYR47N1W5BgUirHakmWd14w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: grafana-admin-credentials
      namespace: yas-stage
