---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: grafana-admin-credentials
  namespace: yas-stage
spec:
  encryptedData:
    password: AgAxqvNBICOLihWd0e7WiH+HFeMNElGYtSTd9kMHMDB9Q6j4wws0L2Ho9taebwOWySb5kF1uv1lE8Pksm+fMF2QDSjrucJ+AuuuQZa2w+yfCqOUq/tNzOSgKoWG7oea2TovbAyAfZKkLHBTj00WugicSuCVw8+3UTT27boH/qhWGpZF3INgvWWS8P2+KcJ2Tw5DOoLQlKKoUrTseZsOd0eBr3OfjbAzC8MxEVd34z5yBSp5zGK5p9O33nZho9gVE2S2KgRmq0GWw9u4OE8CycrRnbh4qFzVrt3yA9Cnh1uib0fDDSLz5VJn/4pe8P9pGymcvaqep4Hd7jm/SpZuMMlaQ3UdGGRcBRsVinLrLafKDTJfeZ+6DHy0/wXr9v72WtJm5cwzEmAqQlNMJzvDjSqSFZeM/OhQo0/suE6G59pL4lvc4fYFdT2XCw8kP1t0ehai5BB0WZzL/oWhhSVUM8pAIdn0NQmN1VxFBf9AfeHL3P0sT+l2XqrMLuuag+VmX3s6ZDBv4GsR9wGR7DEafwpP1ODc6MVqyg7KLhXcnd9s8nbK23YfiFpX3EndiY3j5eVWZoX3rRAPWalOqusjEvke/9CRKw11DbXsLSzKkP9SupcjFalkPDSGqnI8/NVWMD5rHPa/QpTAP5LQLZMMwQiwHSCSv6+2WGjMcLAkZTegsopTwTTHLlLBkzpMKXb36blow75SggQ==
    username: AgCTlpufgoZe0b7pEChP/YOYGdnhrdONSPJxhIE2zUKG8p9bMeDEhFqHauJtctMlNplQ9OvWO9lQPBJpXdh9yPSco8l6QlfezWXy5bCSNJGlk1VEQcgruFkADHclgCRkabaMNpY3bKwMbZr+1wlwarX/BVnSi1maV8Fo6fmGDAC9Y70JzY+tRI3P88FspWRKu1osTnkhwqGH0aRDGjC41a/7RQC/B6URhPvVDXq4dRHx2rQ5w0IhzmgJvbdNVbCDCu50tQnI1viUsRkOkSJpA8DlAAknIo0NzbKx5gnNq6pWaitltffKJ8cSo+MhjaY5AHTngvBbktBCy+58FgGCWZelde/GDVP+Qo+DCKBwQWPQcoXr0lRIrG4FHODJ2yvQTUTFZbWMjLuVg7AxEo4GVqInaCM0+EO77+Ftbjlt7FZ8wrHnorTLr1BHW1fKJAMEE2j7V5FsNvJb0pHaa3Eisz1tw+Fq1TJFWH1gXv6awNMVQwCZi5AP7uNphFfZZImq/Gg4gbLdHl+npRLOo3jEO7qLXv6vjIDSrGvko9MFPn00aBZE/CNm7wwDX6syN1yPIlx8brIqjT/InazkqHtLeZTKTS2HqEJH7ydzQJSn+NRvvBGO9xgnr3eP/JNUAARKQnaXi5QaZrxUctpgHvF1V+KRglz1aWJZbvLtksL4ostcI0GdC0uVdtHv4krHlahKdWpKwSTLqA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: grafana-admin-credentials
      namespace: yas-stage
