---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: keycloak-credentials
  namespace: yas-stage
spec:
  encryptedData:
    password: AgCL+LcL+oZnaCfqUolPi8JCYeRxNm0dmHmhDwN3f62If+xjO89P+yQsLZE8hLIYzRqz53/t9tqM/W9QXFJsCI3dTfKZVv7Jg8Px8Fqp8ksR8Rnewmexkgbxo9lEdH2nzqBlkDwLZ4xKzQrQB7MX7bhBCTL3HNkGcU+68UL0aqkZYV/TYkGLV059NE27pedB9fL/jxGiFp489W2XGxVfJOFJeOzcZuJKWJHduNRzrVLpM7DxvJgNsH0wqgOFPBtkfkYBP3uIRH/zL951VWkQCpD2kbtaylf2URmNcF2QhQ5L7b4mdoJ8OE31UoR3LY9gmaBPZ8ae/ZieJQd5ObhAlC4v06KVxo538T2PSLaoYpUW9q2FP9Xi06kvSh1nTPC/AHaSgBVz7483snuYHM/MjhL1/IHMhefMaGITHonZPwrJwxT2fn8kWtpE7J+eUg/LKEwcPn0haVT10miroC3ev6IDBHd63cloRxEGxSk9uzpnp9sQA8WARJkcLPjxgVmJY5NrnrkHwJ1bn4UYbWZS7bGjkGp3ULDmUMyxVPaPAnpVCZYmEifOCsx5pmKILmeXttIYV2+kQ0ZHg4LoUFNsiKnt2Zxh7coFOOXS+G3zHpkWtKiL9i6on9Y0jzFTJXdyfuLJvOtt+w8EKxZqPOayaY2KamS8NYQLBg9gXqWHYqiaM3N68vZiAOBqiVp2SgkK+wEyISyR6A==
    username: AgCZ1IfK9TbFrEqFuXBFvpcBDyVkOMJl++gI4ekQDqH4Wb/GJz6PZB75m6aRGwt7GNH0WeOt578nm5MhmPqshZgFBMQhiQiAKBXKy8O9VfrzCWKpbIBGwb75WGWqKZANiw/4VDLXTf3Ib9zFwtCyY/zi+luGceu9XOVc3RONEoRH/qfPscZuaxPSR1SKydTp1kPmw/38DFoGsBirVYnwE/J2FcjEiQ6iqduaeHWJWpCRypUNGi5QtubKW9A0O5/mseBTFvafl9Ls03kayQIDXP1nHiXX5nGlyKCSNtY08XmkdN4jY6NTZWakA3u8rlnL80eR+QcPtWdD7P4iVPqgQC5YXXzDnkwm4KcEhnHgKWNWIvV+sZOq+L9Pa0LxEHerqlV7ZZvxpJKm3Ec827ghgp4UWgV12imJ8w095yGN6a4obeeuYr4OAE/LYWSHXAW916x7szvrd93tK/IRag0K6JWYPfqMmPVktsS9qcmBU3wAwdgYSCzqhk8fQIqjYc05KcOeUCxnEeddtgfTK63IIOHmXheB92SZNh9NA79kmZSOt92fnOof1tJfqeH2BrRNWHC5tNzC/nAbk9zUUCqvshlZ6/0ZVj0ZHiUpy1ruETVZBL42c6XOGDlmcCFjEBoUqPr9BLFexw1q6g4AvwkD73Wj6O0akPwefC1/vCv4HjCn4YFdgai3DDSGeE2eXPXfF1p4CKlsQg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: keycloak-credentials
      namespace: yas-stage
