---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: keycloak-credentials
  namespace: yas-stage
spec:
  encryptedData:
    password: AgBWpcguCnE7Vwmq//0EgQWrygQwyMoUUy3PEQ2kqhSG5aazK7ua6QNA+53t5iy9tpo40+jz3jII7hF8Ho0x3FOxqqjQQBuduwPkUmr+YiCsMZ71o8Mk3Qvn5gMaHuIhWjDov663qDoC1BXlWe4K5vaHnRlk+cHKtMqJFBoVjEQR5jDzwIPiUoxehwO919Tt4kH3GlufOQXJtCBTPQRWY/I/vSjtx6DmvKbGvWXu51rExxRQo43CFE8TPN9C+ZRmgxTaN+6O1lynXutLpQSsBUzj5OcjgfKe2DB1kEeU2DpEQeND8hiOU4ydbMYliZI5WSVqGeV2dJqiue8o30PgeRpJXWIMs54YPHjzlmuPao/v2KTeOEwOkZ9ejqp/x+w5oOxAkiWp1wHB8bZqi1my7bWYB7Yb/0qmJ0jjbjmAsP/9LHWVkFzldCH0FTS8FY8b1h8f0Uoj67/K/exYhuH1KdrZeIy++71H2c6gSMmMVAAkqwCShCxGCH2ESjx3zSVP1PkdQc+NCfgC88qlTJrJGFfxfi628LvxL3Nz0HBvWy0Unf08N83xUUxXUGHamOcbQ0XAJMj+2I3rNnwSeavF9t61B4hbqdninXV0kwcs+7/qdnrRODrVtpJ37Fzx4cGjF3785vDHNBnRO6nzmnqwBgjTOAjt6oTspaAbw/BKwUnU5y2BovO79dCabGQ3zKWxouGR/1MX9A==
    username: AgBwaH4Q92zDSkGhvkgyOSmnbMu35M+mxDmY1qwNHpbHYKggQkT0nsVaXlEveC6OQRA24ykKb1xwpsahv5cPIzb/31v8VhqS9p46REivOUFSQUsszQJLnZ+7stzoCcpCeoJZJoMxc/GgNsdBbBPo40CVVP7H1v7kNaP44M/eEzcq7aJ0hXRhsKTDrgRhYn0AgTNq87bB90LuUhstKvoYcARAeT7zeljf0HhVq7e+sW4A2oauXdZPJcS4oD3+gWeGyH40L3e+f4QOns41PkMsR/JLReDdFk0SN+ZYejvVlGqGLfgQVqF4cEUBKfjOp3hOEcoqFEcUHzxanJYskP5l8mz7De8kqPMFp/TKYQP1L9PBgjjM9PHa8XCY4cras5dQTBh5LlzJwNA5uxq/uvpjCmbUGff7TSe9eJKCGn4sM8UfqbfcE2bQGzHISmzUo4pBWq0dHBabpHxUqMnx/MmiCuEfd7YoYgN/e4dAreorGVBiIsP2mRcH8rL0pD6WFPs8583VqqhV5NVHaYid5mb0b3+8LSLI+3OSblY6DhTSJgCKfHh5q4QPNjudNw3n2yE7VXbAUWfglqP/k9olWRa8OmHkGT/jJlSob+hWnhMHQvFSVyuJcRsQuY9iq57WUzLQyC3c1WMHDBZlEasjG0RMfyB1ZC5VXYnvJSeHAb2s9I7hCxwNAZGzhjJIH0zf8kej8hmulJ5loQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: keycloak-credentials
      namespace: yas-stage
