---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: keycloak-credentials
  namespace: yas-stage
spec:
  encryptedData:
    password: AgAhxfQA2C4nM5wSFUH8Qcn57OetxZiXTXdu9RS7n35ys+hDVioK2g9Uv4xqNMpe0RyzZYAJEL7xviElfzAJ3rMtnSrcHStPJi+BXJWqu9CE2Lsnz3L8Uf/6Hup1HV/yuEZVIr54JUPu1qiGmxsKJMEQf5X1JIKyMOZQjhYAP08IYlZX1T/73gfEGfQSMv4ICJGdBXt5zuqZgo3J/tOwS2S5vwZ9L0193Ou8YvuaJtD2DqVT3ug3Fp5IIGLlcWfH3DUxOcxlCS0BPcBrfB1Vtct49XGXwJqJ5Zy+m5iq72LmOzP/AVPn5IwkLcTNgcSK2lageb0pF1Jf5poLUGzYlD7rj1zta2g4NhCNhZszfy3bo5CTUm1JacPqXiThN3d/VS5eHCS6SDEJ130949qyju/9DxzoSNI2xT/PWluVAfWATD7BpZ4N4+gGJv9rZ7RZTWuDwcdoNhggrNZL7znnDXNXPkRCg9CjvFNsTQXp7rzLrJlDL7uQnPqYxcv1D8y/+xosDH/7qDDguWoVGKlZOAWwkuB72Yh1nzNKUJj50QUysIbUCRULXyWbhSQgFaamMhIu/RfaV5P17BtQI8j0g9S6NYRtadwVJ83b5ZOkPrJ9luil85KCI/pPFX96a+k2rBEA0OSeXcarLFYWZgHJUq6mt67Qq7jKoqyIw4mRNAsrQ+wSRqNEh4dn3j+biR+RSyMP9+9LbA==
    username: AgBDiRAjmaylBpd10bBTLf5LPVU1kJcRmTXoBP1BE2lhZXXQVIzCSL+Y6zwLMCpXWpJkvVaHB7j27oigah/9/UACQ6pw3PQ/WWPqHXDieJV17X17ohSBz956r4+AU5xerrZm0EdPEqupsJEvnNguBzJfo7H9CyuSX8jJ0gNVWBsUdag9ygFoBHbfQOpAG+IjAt53lstJU1H62FlMQe1okfzO3JsQJwElXOvNghUUOob7rmI95QTSNXxpuTPPFySZGJzBLu4lzSmwQORoZYyqOK1hqaYsQG1rAcw8Yrzzihoh1pRCnTxg4NpE5E/juVgDJSTcr6hwu+JWLAbAzVsrlFIsrrCFgZz9BXVLHIJOIk+kdAVH3oO8X+wEHsLedmm8M35pZiQy5Br658G2ZP62Eabl533amWbHq0cCpBZ2nioBXGlXsNBlL3kC+zbk+dW92NIBJMZ/3dznStHoKY0DKmXyqMS5w7aCP2aKuO2LfvZS9iuKBrfU1oB62xyFiNzSJh8T4blzedH8ZQ1P8nZjg3HTozdelmkv0exMF+/dT7nX8vjL6M69+O4XiqKj+Ye8pzEiZrS7NiOJN8cxfT/MBXE4s/tLmZiwh5r0u0PKJRTipqoCgARILXLRM5umrvoSvd+hmoeB3lfLHu/Ja/AYJpf2w5UPMb5PRpdMRNbe5+lHOuWpb6QjXYovqVAVTHMXDURDqJmGQg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: keycloak-credentials
      namespace: yas-stage
