---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: pgadmin-password
  namespace: yas-stage
spec:
  encryptedData:
    pgadmin-password: AgB8jfdFpYfJD4xdWVuyIktqIXhajyWuBAslq9/dctQI+oSbl27nC16uwbJ+ANftvPa4lW8tneV9ZtxVWlgHsdc+6wL+6ANi4MyCe9E58nsX34JCpDp96UnEjuf4i8gIqu0Iu2ZON65wuc9lPNnA3GawucJo9t1aJdbUHh8nT3hLbrPTLEP4OInaI6UcItoaYhySz623/7DuJ3LgDJv5GX7d+vYTvdModp2hJHvteWSySKDGtYPfAe8OwSYNrAexLMYKPbxHt/4DJf9KjwwRFisp+UMP37dJV9GrgaJobBZUtGk9QBwGD8zuVtKotDTukC93vQElIfsaeCu0vVr+AfpwBSXkROGm7/gcFOW2OTMsk0jus8jSvr4qNQmOQvndpH2DN58fuY4JRAjszjnVsv/9xJXQ46IJ0+HX1p1mnkgOF/m15MmDy7kbEfDxIk+wyfNaITK0nhsH0pI4bL0XiABJIs7NfKgJ+e8nbsUT3Zi0F0cFGdbTDmje1i5TEI773FOy9o+js54CLs5qFlrs6GIB0Coa4tb9bxBzeiecnDcYCYHTKwhIcPbTAjT0bV/bmGqq6rtqg3FQhtegEvA+ArfNqDVnaS1E1DhxZdUZ/jKK6IEuSfeTiq0eG18n1xlohxL7wfN4Qci/euDB30bgutDXKcTP9FyFZ/Y0A98ZEClKVhk12UXFKtTOrXWKuhH0Oulp6JBWVg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: pgadmin-password
      namespace: yas-stage
