---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: pgadmin-password
  namespace: yas-stage
spec:
  encryptedData:
    pgadmin-password: AgCYVe/o3swlhtJQqH21cyX8zAWFLUlZ/Mcjdzktj73Vyt+i/vJoOtJsNTzOUVfoa9VeYF2PAp6f6gZX657V9BQ/Fe+ZSLOwUnFPcHbFXOLMqgt2glkqrlcPck0hM63xD0YybwIpsbad5v0wEHXAAYDmBcw9ixhMiEjpyINn2Ke+r0JjXmJgDvYJdIwZq8eE56NZr0KkCVHs5KS2HWwGZFEz53l3KUy3IM9sffy+AsOZGDd+iwonxL8/0ScaFcB4hyG66qdeoW9TbdiKNtnwrMYuBtRU2gWP3/4V+9sQjG2VcqUJPHsUXKJQ7bGyR3teWgoWmBN4xUL32TprajtBhL3CvBbIyO79FDXqA0drNxxuJ+0wIQgQiy45ZnzeGUHjSJOwac3BKiOTlx2DRClAxP3ApfiRtBCv+8bCk+IUfAX8NBMOouwkK5OT12G0mw3haItVxrZhIBvi83JSB4UxfZTqLMGyzr3VZR6D6MCQ8tYUbUb5a0+AbzRxh301ekWQGAZyLoek973rTVTUSU6xPmyiC4iI8sg09mtAevIRS0vgfjTZk1/2HrzEpdQn2MBmKNvAnGB4YBD1CUCf5UGtitXy77+zzRZJhIHhHyzuWzk1a+M5AjlzsSvnwL7Afu5t9oB4KqLXfPTSI3neit+Zc/CMMu/RNWbDg/tEnO/a+WXledHyZpLBkTcee/PyO7hh/qSf6Z9C6Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: pgadmin-password
      namespace: yas-stage
