---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: pgadmin-password
  namespace: yas-stage
spec:
  encryptedData:
    pgadmin-password: AgCrgAwi4BVfPpYlqVB9FzLbZz6GPApMHT9xlBhaLspmiBCkPIuEm6jhvnEgZsEweQgG+XJ1A6NN6wKHi2bLLMHAJL8JNMdgMlZCj+iBhWuSEktP4wwB3wlB0YKF5sZ2qhBiE+yiI5LLelKETDcsIGkq0bbt+/eAwcMn5EVt1d6aIQkvv83iJvKLRnHIExRohqsIj9hoxoR4DfgsHM5tfS0dMiptdc8cTDZm/jTjUG9M1cGpFneWuJmCWDKdbTxsSXtyYGtaQGZK0omPH/k0+9tOl7HQaB2CTKkZTeleQzI4JTpVPTkr6VqJhMwF6wua9/J6dV4x6SH0sz/++NX9p7UQs5C9UiUK5kR0FMEFmx7biuIlp65YvnTM+YEoisJleLA3+ig8OhLPr/nDY8fAq4Hh7QsuUUW+s+05yKZfodP50ghHONRvulY0IN+R+ryRt+kGsZh5bahfvi6/ZFj66w6gMpbv3REj5QZdkSIxPVzdcymMLR3M4wZvYSC3OrMoOqmqHNgwQQZ/4Bj8xzT2XQcPLCK5YBltzQAWhZV93GMqukNAl7pDJcE3GFHhr0tlX3BEYYLHfl61KDnvIjspQI4ise9l0l6f96AAfunuM7RZndMDtsvGEniNjNpr0UMBDIa+zpedA4bc9c2ELFqPzbH2VfECMMA/9XTq1j404f3lbAPiKex3Mf//4CUCSiF/ioHiTb/ejQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: pgadmin-password
      namespace: yas-stage
