---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postgresql-credentials
  namespace: yas-stage
spec:
  encryptedData:
    password: AgAO+LqZyVUNycHghJag0etlJVJ+hY+sZlURHAKbwFjFFPYE1jiiz8lqO2Lod9xT5+Sn5VyP4gsTNov2ZfWxybYx1SiGDiU5EwpNoF3E958TFVrw70TsriOWtc+Y2AkDoblyST7INNcnuimmok82vlXFuruIAD1gCVZUfFBwZdHOi6I0usxQ1JVnOzPek7ygk9p5md3C4/gsbn1zXGYgul6bJIkQoj+MB/r0nA2K8TTqmX05B1ECW09KJsOm2niL5II7eRS7bN1c7JEi4ECzpYkGpMjrbUdXlFLZb7iMjGweK5a1P32NZCLS5Gjry3r+OSgKJxq4jxdLRDiIrmrpezq2VHJoqvkdXFhPn+qLe0nBfMErb6XR9rHpE99pnUHk0gspENzxNQkA3iA4veMQ4uGIyw/8Ccwi3qSn3VQLE3ZpQrd1p3isO4ghkC8xpVcrPhCTQ7Q3Tbc7rh3CuvxpS5U7NM0ZUbs/2arGVEGVczyhtEnPL3URZdQpvJ7rWHm4+kHPB3jQ7XFy2yY05ZR0zmGLpk92HHGGWsWyEVeSg/k08YnLbWmyqT6itD9JuGs7EkDVQwcEtoVMXY9Ur/pFuwiv4ucKFp0mkDEC7BwSCIm9noUNY9RlpmfWGqKKPi7TdODquOh6TeicWdvlQKITsgXyV8+iXoNPKYd2hiNzBXc2ZpD2R6NhZ1S6NKYDKK7XTKRb4nSkoQ==
    username: AgAHz/uXtpSZdcB/ufXbkkys2WRFANyQgnpw8blnXYWcwUljZxPDGdx4QNQUtB8+RqQ7Nss8mh3qm0OE6Bopwd0Sn4NXSYkPtWq/k2BmTZAs8zu/cnvd7ioLEwqEP4GOggz39h++5hRTO9o8/wBHT5Q8kOPkHQJb07zAkp+2Crq1pwFRvM+UxUAhOMC9DgdeWfEWvj5YdWwGyl5J2KtuFBoMJyT2lO6K0m1QDvC73GClLfk5mTgQTQxRz+DnmosRLGndQPqPVp0J5DXKwfToK5tyHGJSlaKPwBeane6dxsL1c7ueaK7mi8c8Wasijf/aTY2LNcJqrOQmVnOxnLkGEqFX86mOo2ySc6IcJN8eM5pGuQuxB8+HSBtqgOVAQjN3E1ImBJvr3B9uZmReQgYjz3ZDarB24zIZ3qAThagFUbEJrXgU+PQbP14mOeArHCXW2kYf2Cg2H7uNlj4ts2cXZ7aJDNZrC3V/XhDTyNprEnJrv3DrTPloDjwtsxV0T0z0Pv5U/vLmg0Mk41RyWIMIKF9jUMHFTsQKq++/5aBmWhhUq8fN+oB1TtOryj38dXiDI+qOOX1hPxpGG5kSg5D408vwABZOJlxKGBmNZmgP+AUMaIE0l3fveEsOrHn5sntIqcF9fYo90ckv11nb7VIGj/b5zrwdBsZ0WcaJFm4rtVEY0IQ0uOjsN4lrW6neANAhRWj4J9XLmVXx+UqV9Rc=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: postgresql-credentials
      namespace: yas-stage
