---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postgresql-credentials
  namespace: yas-stage
spec:
  encryptedData:
    password: AgAfWQ1wzKbXPV4M5TSpvPVpreH5DVM1D6r5wJNuxVC34CWrScWD393jYtT1SHBkEQva6Jrl2dd7tElY1dS/OC9zBTs5ZX2NlMvqUoXKioVQTBJmo7uliY/USMMyQ+h3y8gkYkQmw1sxzzHzJKM9DDpAQW/nrwFYiwok3j1Q3O36YpARGh3iVVdtMkSnfMT5zStO0RRR7EEZry6xVWRcI+egZz00LOkI/Xgw+jtlFf+BHDSL8vuDhlq1+Lw/nmhqIKLzqjR4TqlnhFiRK7IzdEMNxWY1d4ZH+h/VhxJc7Mm8PO4siOB+PvhVVMs+/iL9ftO7ei3We/E/lEjpixK5naYIGGn619JixdQBPt0Wq2NllZ00prsreZQHP56RmHh4vdtvCzUiRdzNxi/HzjJ3Zr0hVBtUdlwb1vMiJ8UizgjrdC4TtyAGXjweb4TC2tP55cBIOq+SDB9EmZsGiCb9UPOgM01Jo6vBMK52jsyusHFaTdahtgnZo2+zwDPHREKhWhlzJ4HvashODvZ2lZGxP1KiXbV7qao7UvQmc5wQrgxEMvpo+Xqa+R9HAcTIWOAEbnf9PXESgMaehY5acUkioAdPwf9kPbxkIwWlNHAEwvYFkn7jlSX8l0WTtBuiPjmz9AijM3O7SYCJlD7AWOUAiQRad9A3dYPZbwij8I2lT2yUA4bYd9Tc+FCEsVnbfnH3l5NdTOHspw==
    username: AgB2SfFYfGetpPIe/R/85/AMYXmCGri9nSwrDjgof5V9t3d1lzdrm47Cbxy1g2dBBnNjKZoUrOU+XhEilxLAqcdjCBTKXH83ub/3FS5ucr/v4qlPKSiS4IJqB1UCWXO7+nc1CHut+quUS+ONMgocpkT3czl3VGP2MPvigcSw7jhjbRYdukNK76oczefi2XycJQdLVZ+KrINsaZ0woCVCrXmreD8Rv8pVpS8QBqth6FqWZHmiNb9Q+FYssfdnQQuVPjnksEtnpeBNgbMMCnUGwR5G+9ESvhxLxr9eOujk/rAUEZZZnx9ltabkPjMDfVEE8D9VoPGmdUFve3WMZqBIcWLYqlPZhrlRN8GK4jgwRe8+/aBiS9M10uXypFX9CpEupwYo08jAT9E3pH7tM6UReows686+AmwMaSMAJCTHwgdJrCxKOc5qzmmQCzmAdOBrkfnb5GFsvFghrtqqT0DYflt9C6vW1smGcKYaiYNntg8QYug9zD0a5fVdWWvO83sBVgOQfBPI8Aw9R3WN7fIUJp5FoFKc9DvjldfWxE2fDXuAMoLRhPtWB9TxmOCp5o5IECIwnr2gQXBkbYeWYVajrjULrZ48NOZDX18gFJ4EN1v0N3QEBfInxGZLfzx4kVjYb3ILV3vRPo+HnuThncSJvtGc/GJEEHk8AomXu61UqSR3tNT+ccbbJ8yX5Wtz1PKJn6bkkqFp5icwHnefOoc=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: postgresql-credentials
      namespace: yas-stage
