---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postgresql.credentials
  namespace: yas-stage
spec:
  encryptedData:
    password: AgA7khWKNKG0VyLcb3N0uyy6wxhPhFviq1sruHM84kaLefnKj1L94llPVmmeAZDo/DYX3iJnBk5/YXpAfkOHIZwzSsRM1fckMFjJ3qCltef55Lo2DcjDJKq1AS0wJAHOmT83fP5u0u+eBdA629e/NJeaHSuTeSdNpEeG+88WD9xHpR7xVGG/ZMCaqVFmDQ+mChMBBc7P6lLvzvtKlab8uShND/9dNh7vMp810DnywaYigClXNNtPom6sywTMT3wL91q4orY0+7inCsCL/M8lVShcDxHdbC7148P0Ad3QHKxuj8lxAOXFmgVAWd0xPr+NgwRRsT1wfGGcLf5sYl0UPOCuPaadC6r/MoAahYTG5W4zFJ40P0bpe1LZWwiwl+lMwQg8fVgDZfFWRz27o3p8Q+RP89sLet6RmXaxL7kEx+FZ+ZBii1qBJh1idJYqkdf6WHKfMME9hv5pZ2W/bNJZi8D4nNppNRqzK64w7aKsbaDakZ0C9eOPQxNi2GGlw/0eUlt87PaXpJuFmB8bQ39ssKQ0Qk83LDHWeshqJX4641agEdrigXWM8iWYuIHC4Km/44634U9HTXeQEmjYv7fbX5OJHyIxjo65Bq8LjIduiv1rP9TmyOIHHfDQTL9BCBOvQt02353mpOX3D1sobj6UrD6WvZsT5FmWeXFOByHtWgd3FdW2GWEleBohhnS00F1djPs3a9PDGw==
    username: AgCm8CMCj+9JFNz8lirKojHaq+YBQnYgylqMPwKcTI+Zhbsfa9nYtWXj/otXrEsGjh8geDubfJm7Vd560ejaf1U9v30XzGoiv62yQ/mEUwXe9beuWav/JUIveP+kgh51FDaLW5KCKHHwcvokDSHKklLDkWOVcNcxnAPS7kTq8NLJp6ZkbJJdqn3OGd1sE9FhoNXqYXVgXEUnUBO664R9FwoIM16S2MUKmP0oP1r//w8qRG73dioeYfHL1Lo1wmsNDCD6lK17vt872m1UcnXBqtS8nD4o9EDy1Dci4AeLqYlLF1Aav+vJzPu9sVJyiy6ndbh59JflOMfIgx7miinLPJHjBlJ47egfu2Kjgan71M7zir3piDZjikZzzePvNFY/OLuw4at0S+bMc6+yH3RH3xGaynZUu7YMmocNj6qkeQQigohcTAffjIdnVx8q9UV2qMquz2sMreN9BC06uH6DylCspS2/v+TiAf4NSSXrR3brGh9uqbIXSM9rRJ7i1uLKC/rr2vKRrckIqL3s3Mpuq4TwW2oFGDVKIoZRleGFXE0Iip4oKgCMguh+6zea0gOsxEHCZqsnQIY5m5c0yUQbvqlfqsPubaTe4T4/7oFF2fUSGNyQz6tlPobQbN59j28e7onT1mgnMqQrnc7+9+5nRzr4XUwAkHncdcjF5AVSf+ug3OTnYIpQpT1sQnkCKyEzppb5gqEB3Zd/jTk9MJM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: postgresql.credentials
      namespace: yas-stage
