---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postgresql.credentials
  namespace: yas-stage
spec:
  encryptedData:
    password: AgCV8NGjpU2/pF3iZP7tNSQ3Q6hU9KP9d8jqZC7VM+cxBC0Tg/gFJC0hH8UYRSJhlOlNh2/5vsPT+QaQ4NEadmE4lT1g8dnIrbDFtASdJfPrYzE61E6SAEkU8F4eAzzqWdHX2kBOQchxE70D4+732Dkt+B7TvXkQrjEPhjgrLwHS/D9vrAiPnhSYjtzhjk2NDA9XZiyho0kVWHD+ncSwJj8e8BX3R+tdq0TdheLIq1agZJEj0crPFD9Fjy4+3Jv+9rCoX6YkPyCqKdZRL5n/P4Y67QnwPSM7aR8gRWt0s84sI9yPrml1jZjQo3LF0Ba/xy808TAm58ELE8qWIABKNHGbSnYvKNYMBl+YJuh9VKFA9eLJ91E0nLRLYNdQJiOHA91VfOk3V+e8Iie7STFjemFxQbVVUmvaF3yZBHwFFi3DMdqbvWFyNJ2ctiWMC9/rrnb1s0GSIQHH7X4TV13Qq8XituK/cOKnZzWRSwRP4V46EZTzJtD7r8FdZqIH/kZ5ffT+bdBrtKNrUgDI/dfuS3j7mTWn4HATRn92A6gBPG3j1d3NGkd60veDSpN1i74OQfz8TYdRv58FCeBNJTu8pUhfXyGF6lzpOdujP1WbRWJOCgPWza84UyHrkQcbNEJ358eQVcKzAWJ5bhuhLcj5sMrRsfxytrUp1R0Ular7x59fyHN8TAU0u4PmlWwAivnw48q04GMwXg==
    username: AgAEcrwXaweYpN8noX0pMDjbZYgQ5NwO5uOSUZEEttq6ehG8GP8Kv2m6g1e27Mjdhcj2LUl7dy3S8w6gHcoZ5yzMuwFpOlNcCpugGU6Cp+xgR/kbJ+VLg6lhR8UjGnzo1eAt5LMI5wTRoZNwKbf3GGBLeGF+XoedyaC36gRL8lrqludRddHYjVMUV+msg1vw9csxvf/Ot0ub8oAcl+Dl9ju/A3bYOs+PC5Bck5GV9aAc0jg44qBPG69mKEYapDKdVbta9yfNyc+fNxaY5segVyM2Z/mtB5Lf8skTqDDyeD4QCYTs3V4/XD/kYeldtEruFdySi4g0Pv4IwuJsZsM2+nR337Gef2DIAW3vvwE2KmS7divfxb5FK1vq+KFeLg+hqWjlM/RLMKIyr9gubPIzlE3xCyvR8Q3SJvQu9XRTFvl6LixGojsPociOVxZCx2YUBwQF3xSDffHKNvKnkkFYeZH4y/2AlI9yX1VoMjrP/vakKynjJ6syb7D7ulMBiibW6uUrpDQE+8OsoulwXlwU5nQ+P3LStSDuRpsgetdqwkebHZx5kpW/8EwWZ4iQKcO7w7i6nk8jWV/HUHne2UpTOIClzNoSpechC3ab12DH9T68V8PfxQJEwqMTk8TwVwbUDu2LgXHy6+UsSaWtJwFow3mYbtpnrGWVsh/Y6wVPh1DfYmD6qe3zsCTOyvPnxwdIqLMsvz8SdX+Mg6eU1XM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: postgresql.credentials
      namespace: yas-stage
