---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postgresql-credentials
  namespace: yas-stage
spec:
  encryptedData:
    password: AgBObPtE7qKJjBIuhIZRUxNRVl84zAfwxw5Fct2LkUCBbdxkKLiB0Zl5BWSZHdzQ6guaBBLGNiyfNlniIeR8u79Ttf9HSvmRac8g3DsC4GNKYnTvOG94hOQUo79vECgBJ9rGPCLXhsxkK0WYXkgZjS6dCTkBS8l6qX5XLFC6cEMzq3DanYmlUZ3emVQXGGZcII1MZinrGVLtAyZss28EaxSUYAgr/fziQrSQ/pfU0nihddVlF7BkHKrsJW01ZYSuI10wpr5ifcUFndwXaYiLT3vJwZOgG210sC7wS4DttKF05pqIaS9JE8bkko8GH+uQpoj/qxaVJLx3XvehaDLCdAqccaSzkMDXkhNPnAsi1Kl/jx9SPGZkkkO8zfoUJoc7cXCGuxLOoi7ZGuueVWnlrR8ilgFOTGBDWKDj1ypQs0F2mUS/VM1/DJbDgxIrKG0NBcykcg8BkfQ4h9hnfzua7MeuYO9sVESG2to9ExT+Xz8E66G7e8yhYwlHB32UbloVethRM1sLM+9mGzbDQbNp9b6aVH9BqgS/8dl90MBxUuJAx4kVqo1eYUxu8xYqX6fr7+vr9Qt1DtDGT4mDiek+BFPO/50rG/Edob3Lfh7O+gKrh+GAGR2CRK4kALubF/OKp5Ahwf2tPb6SJrWrhyg54koOeNOcs/QQQaoQF/I2o5Z1DhwoLsIsSNoZmPwcTcpu62GnAJ3IDw==
    username: AgBFqott3zmVFmslqCemLMZknqdN46BlDBdYCDk/10fScSnFCKSshhJJ38bdsQUA+HpJKJnegfwytHIWUaU6FKGEWyCswNvEhgcu8250JsamK0aneYcYuk3MRiJgEUjVhU6tgsV9p9h02Nu+glroglXbP85/+uHp7OGXJ/j/LDOK3PTmulklJBveqPxc1kALFTLfmB5OjOqTLRUJjHGQzg3vCbl3dzHhvRMQcgPRVHoff4Tz9RkcIVlR288t7t/HrMF0XXzW2ZLoNV61hQxBiix7H2pwJGbkOxnJfbGka3hOjP2HYV0vv83HlRdshJiyhqSGt9bevliUEZzb7SSi/ASdh6jgGA+lPrvBPg1KCmMF/oizcSnVESYGOKpg2Lz+wIildTZHKd/BIZsEZlT28gt7gD/+/K0yIM3KPZ6PxLhfVVdhpw0apm8eYgwCnui6kTjz4mSVilGgcbmJm/i/ZkkvFzLLFSOiKj3XVIZ30PUsisyPRLeXlDq1PQXVqc2qR0gWrXvE6SK+SBIcaLyQOwNln52jVR8pRVV8Cxm7qxVnQsS3Hap75x9aSPKHi7Y2SKbB7OafmvUsKBvXiZtmY+jig9LZ3CFabxN30dNdv7MSFmoqoPgeDLpxA6z432W/iUIjv/vKnweBNURPi5oIo8KP7uRxZ0CjZwhnOpkwDdAtD4Hl2I8ojqYNPubQgbAskfHLO/EjQSU43R7oxfQ=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: postgresql-credentials
      namespace: yas-stage
