---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postgresql.credentials
  namespace: yas-stage
spec:
  encryptedData:
    password: AgBKpnQLHeJUVby3X1aCUKsaVYcgYaIiZ7Y42V+WbDvwYr3emfz9T1kfQdV1b9/dEEg9X1u52mL8cZ9iBTu/VBPfCVQUiB2QvgDop3qaHwtuhyRP7JH25GXpy3zQnyC7KP+2Msxx3auzF19TZRIBlpIm2Ei4oaQsOe2ylu0uJ6HVlK+ZR/LVL94/yn45GKPi8n8H99FJ0b1EzV3Vvnl83ra31SOtAPhUk8Ig2OLP1+1sm9niroz/K9O4VjRolB6NwQi1ES7KrkwpuOjYBtHuz8q7ZyzUm+qCnG1p+LEdZMQ2WDpu9CJSzfSC63c5vQd27Mr6Clsk/rYufaHs7ubjT5QIlBxkuvhDJfEM4xaKBpNQiCIQFkGDWQ229IIkbXHt3YVaFxm4TjuGBeEn7OHFw5LPYjTY3sXDFzjIe9i3lM9UIiEEgtCV165cgWmU22EkROb2Jlkvztjcei8BRsFw84+MLh+AWdy6ontcpz4xYHLz4A3DD5EYfWNZriedc8dtpMibSk5ef26MbDZ31E9huaCAldtq12lUxSWwC6TYUJCMdWD5K+7bDjf6G3/VKfCD4/ixJD6rnjnhTxpFAzriNHO7ByWgKIEpMu1HNhOVlUEwU2rXO+kJMcclBi88Y7K5LV0DIktt0MfvtfSyBtVW+jtbrJI1DLQJh3h+43vxSQsgiBW4k0qB9Ut/63t7dUlnsfVQ/v1h0Q==
    username: AgCjjaIr1wjHg5jY2GZyYHp9gH9hjwf66SDcN5iFuqMUWSE2BoR/qFyJLUPRhTE5pQzLAFefNUxVC++Iygo5IhZhkHUVXQGvAkIF/XYFSlqXwmoC5F/DrjVBf0Gmth53Seip92d/ODWOt3fO3v1oLlcml7Hp8RFP3uOA2XK9A7Dht+xnGWvHgor5ViTykxrIggvbTTWCdnGAgaWrTvIme7Ll4b2uVJOMHv1lFYUCeiD7XgoPciHo0LBIaK+KF+o1jsJTKv+l4Nz1kAAODZ209LtQ3LgFCxlE72/IXZS56eQTkWIQqti/+nin5bndRXUjYbfqbBFf1A8qNbLz+AgvjFBkU8SrmhBcAJxxlIDbMFpZdKrtKocQJqOXVXnT39/ONK3Jy0sRtRFGdojN6DSK3d247bHX/lPyq/3kU7Mdrd/LGyvN1HrdQzBcFu3ctf+GAJuaEzZhUrC0ZaYl3B/Bl8Q2k/a7sMrPuj6o9HOu/szHCCkVbPUr9M0TC6GodbylM7Z61aqu1XPEzzUFRs/lLz7il7JvxwkBMAyg979xeeM2LrmEy421yIkuN9wMIlHyp+dz4OIhqMD+Ac8l6PPRCPAu+meCY3kkpv/qKniJcPkaQnMvRjskYInqSnzGbGqnLeus9lIQyfmxeBNxf7vnxa7N8P2aFMxyolMe884eKN4iPpWD2Uwq3vcW9AYpGe7lZqTPC8Amg1YaOQpkejM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: postgresql.credentials
      namespace: yas-stage
