---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-postgresql-credentials-secret
  namespace: yas-stage
spec:
  encryptedData:
    POSTGRESQL_PASSWORD: AgBU4vTaybkT5B63pKNQqo7KSucLkMLw7qPImiX4YnRF9fcWmnnS0TeYwRWPiyfhja/vrxnLbPrwHeiXcwD+s/l+Ek11MzuJpC4rryQ9+/dGH6nMSg4R5u3wOMe+CAlYPO58RqIyCDKO4lHDdORwxIyF/fOXE/z9MwkVVPhJHgl0JFJaGfuE+MavNfGJPUKvgxXYrGxPbUCE7FtubdxWtIl3/VZRHkBdk8ClFaecErk6MsIrvFHGq6xwE3RKA52B22qYou/xC9zZUFcGJv2UZ6zME+yjQVPACm8kjd8nUSPXPWGpXxlGfBG7bmcbbLsNU7iKYVDjKcbQ/Rqy9xtottVIja79w21TQUss8BZnBbYegYz/6cMNmmYHwwxIKJ3Og3W+rnShVWcB0LPF3cE/S5zLSQO1cdKrNwSxsRjQvnf3KD7oTV+V0svqcRip7KiitSfy/WxmRXdpdBqAVOjPUE7h7jgtYwn1Cpn+wFVElwja5k7Z23JkuGewh5r7pHi2kSPMWR2E6H05dKU6PAShDGPyJrOeV1yK9iXnCxlbmCSVh5fc3CypGbCTxZnXc8vHKzF56Gu7mfPEnImIPoivrgR6PIfcN/uEGaZ3aVO85TpM9X89D3jZgnLCieTm6ezoXTswBjOkpJIZVrT6wvjfYwr+52HRcYH5cQ5LYhMJRBJnQey+G1tZIt2uh+Ni2mNlQ3iZyEkNlA==
    POSTGRESQL_USERNAME: AgBIhztEiNXG+JaoMCZ1a4baTEEI675sAFObh1RIsKvjutrz2ye2295Lw9OAksEYz8Les+8gOZsNpevKjcok14g6XvgMgaDSOCXnxIM28JKToHE80xRX4s7xQLfc+ZxmwnHrGIxxGUwbz8TBl2OqxmgFJtUXvSdhA5crEqcUz3cqwC46C5FdzQd9UObGcaQZL1ccmwwqFTjoS6PxD+Ucs7F7U5b3Xf73dXYtBrQulETWLcHFlGP2+PbUld3LDlAMum03J4ZpIUSVUrwslU1cjLKBZMYy9eJ80+sG10oHaNO6FX1UJMEXPR0xYLOpRHf+/hC2tz1s3ENggGllDpmJBhXMvoAjWZgPUig9sf8zXNqumc8wCo2ymeUYwpWnAVS/eddv2zjeBbVe9F0amtpF1DD+RqYbagozPs6cEH654bc/Mq8TND4R+S+y3CBUNHqQ9a2Hj+MEZGPbyB5Nh34wvi/c969Gq7zTa1NK03ttsIx2pvkzNh+Gf4i2LD/pHS7B39r1AEpC/eJUSTaYTC6we6YL1Ld0XPKKLX9OyjgDLaws8TB4oaGacC3+17zFD/Ku6KDPdfCmPN7oRMZGj4/13XwbPTqxLUkxYnE3Z8AZsJ2bhNFSa6qdMgvjxPwbda1lPS29fGx2R5lUfPsJ45SNFJMNgxs7Yh/ej1LGP0zeNvkX8zZcBCihmYoDy8tlK6OIFFpp6PMtZJpiiVPfjn0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-postgresql-credentials-secret
      namespace: yas-stage
