---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-openai-api-key-secret
  namespace: yas-stage
spec:
  encryptedData:
    OPENAI_API_KEY: AgA5qkDc66YTeXl+STijsA5YIbv9W1PtvligCzWbKkb89gVQHAoMBa77D1J+/cHJt0QVGSk5Z5N6STgqENTG8JA5SdgxixSL0WSr+kEy5NtLc9XGqDVJDLbBfUMKd0UVOg7kZ6ozSx/LKG6ot5JmwWUmLBfyx7fZ8/Wyvb9ZmFG91b58l1PdZ6Kg+c74okezVlilQUQMCmw7DDZhIW+vJzYPQmiKqGNYT5I/wMuWRDcT4fWtdjlx6S+09HJHeJUz2MUxMhVxMkstsA+SMpaah1QT6Jp1zx0nAVSaUG4ZttnA+U/sjEF6tdJzH2UTCaoIjtSfN2poKJy8vaNp/a6q+QczdNgH+1xCx78cxlGe+TPWQapBn1C/4sHvfiVutaHPN4ZKe7uj369jrOGouaXgqBF+2i1JSRyowJeAekNXvyLjlIX6B5+I3etnyjv8K01X4OWrwCyJWyA4gW7EUcuDwkT8TCteht/EwYg8/TDNwT7O3Le0Xv+FtSZ+c7ql//WRfuZ9Zi8Vjp/L/H0i3QsXI55LCJPYw3gG9hh3FTSW4N+4FA1VyzoSFsnmRQYF2d/thXLC6usmth+R77OHC3Jh9Tk7BIYTwF7Yd2tl3TOiFRNRf0o6GYv5vyPfwChotSgSBZKX65oZIisTZGuohJnQL0uEHh6Z9REZYlwZ+JZdW0QYs+pMP1aHsojVDF5E9RkvPOz0uhE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-openai-api-key-secret
      namespace: yas-stage
