---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-redis-credentials-secret
  namespace: yas-stage
spec:
  encryptedData:
    REDIS_PASSWORD: AgBmNN5NvJImAfb0JcPGn24hvdpm/vZ+SEIqoYV/FlaeooAwo43zvzJHOlp3E6V8TqyDMTWeThQ4cmIy31pzERP3eIfmLnATbQ3UKsfY2knfEN0zfN93+eeCTtLnm24xOOMc4IcEP/CmEyw3ZH6BW1KSZe/7sliu4gCFUbgn6rfBUvW2P8nS50Gg3rdEB1E2dWvO1XqTFTJn7bdyA437ZXvo+WLCLwCn05oYzbKdUAM9nw8z+rfiMPg02Qc0U+rIyRKRyDUHiXpU/JvdGrZv2G5gyGkHh4siV+ZTCh5Ti5Y/TSiRWRnNoloOruD/jW5gexjlrEfGdyCV7vxmBMAk0FLA3wsY8pZxAMLmx14rzH8jEOZ+3tOSscNs6f+k8BPw8dl1odtMqewkj/mw4E0wcwakAlaL3YcQJ15BA5zZksQ6fOkZms7xxdCMLhnnUeV54Pmivof2YC4OQTpMbZF6bbRa1YYOGXefhJuw7XnAD3KfmBJvw6XOzneLM0xtfdnHk5yH4ktU+jmu2WfBMu0RZbEsZHruu6Vm8s7gEHZvIpvmceR7Pkf03DTI/D9wposw0EeXumtABN51PehlVduw8CxgQ0WI5IkBf47xPP2p92M3E3hzfZLvLdVatPb9mwMwXCdBlj0SRzkOkJ4BLxfKZc5kmASP65Mxx1u6B1b9t/mzjTzmTmKHn+vHlrJ/YssWLFwgjcErQA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-redis-credentials-secret
      namespace: yas-stage
