---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-elasticsearch-credentials-secret
  namespace: yas-stage
spec:
  encryptedData:
    ELASTICSEARCH_PASSWORD: AgCnoapOg2jfIte+0yOYRS0/j7DF9IvS5gzIRivLfi3HHwR28+OfBy3QZrNUZ+n/jHKCOrtyVmfIxea3qsHBiPybD37PZT5ilvUTvsXV/Rkzu49hN841v7ISrka0dKNJvLU2oH/GVWPN1SFGiOeUApr7oep34e5N6zsrHsPuKyM1OU4gGTyNpT+xUWCd8zRqfa+Zi5gzxxwJs3HZuxSt/4i29AHgMg1ycXUGe7YBGLAAmK/l7dcY7DV835VVfywzZWYk7Pnz/o5hKllESxbg+qk8VkgSQbasXdZWtHb09dbi5O50HSY1OvEQQSGTNq8BX0gOTnJah29nWp2QEOCKQnXNOciBbG0LDZCdoOB8L4IMFj/IXTBM0QAPs9RHD61uUNaST1Ex5YFLM0XsdXvrB4mWcCG6Sbac+8DUQkWGX/gb7fnoJvFmUnSfAHtmK0UExIg560eqPlWJ5k4Q0IZPy0N+KqNmReLPbsJdNMufCkVlMJqpx40Mp9MKvcOmJRl0jVGj14bkqXLtB7IwJ1qrEsYhho/PwtDiqjy8wUquXV0939hC4yabbZaQ7tjixJf3fzHcmGNBCznEsLKWjx9YR8I6Ha1ciC1IHP4SFAqdfdHqk0DSCDuyeIiKpga5zue3HFPsJHUYShsbUvCjX+a9koAd8gdeDfPs6VZ+I4hQHxwBybOOoY5RVs/TkgirmK6lillBukM3+wq++TJKxNvjf/jUlcrIPA==
    ELASTICSEARCH_USERNAME: AgAWiEOGrFvtE7//jFPQ0TUqrrTPSv8waZMRpczxCyV08/tb4GIj4mVUceRs7zHnfGiazhsT29oQTkaYIxYnwS8AbuIYIqn4AM5HF7LREI8lNfW4k+pP+h8u7UZf1LXLQZ4ViwOKs7wJuRqX6LW598u0MhKZP45l9IMiZ8K4/nSSg0R1Nu6ExvfMWinxVs8nyua/0xute/EFI/UMnKwuKo68TpQXApXSbSp6bV8vwQJZz2pcUOIO+KQNexpGW+QYSrizTXt5sMLL+Qf1OgC7tE8b6CSqp7ihsP+KL3GdLecwCdbiB6RmHEMKl/jf/wddYovgJmnC9qh+J5uR8Wg8saFYlwP4Ub1uRBnVBbdPBpuD6Gl++W6ngqNt19w0igxzz+QjraK3fvi8zUl3htZEJjn5mbjjIpInuYnbDmzWzV0xsDg/+pRt3RSbhOGO4xCQfkEJxOjUXc1QjtId8aQXv5JlNoH2DYBF/2H7+X282T44UyCJxver7MBrMwDx1GOmnXteaQiRKwdB3BYIXjFULENUIbH42+JPGqRHrBrMPdlMUXMaRbhJQ7clR0X/S+s9zinegkDimcTJbFuADqtOwDoczyMRcv0QosJJ6LUdmpM94ZcPnhTuBpnTmI9PzYbjUffjqQdeUqHxTKsZT2zYafcAG1mJav76m7wx1RFSXE0jv1mdgEs4Q+YWTPU0N6OQfJntRvg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-elasticsearch-credentials-secret
      namespace: yas-stage
