---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-elasticsearch-credentials-secret
  namespace: yas-stage
spec:
  encryptedData:
    ELASTICSEARCH_PASSWORD: AgAn8mooqVaw27/DCuOQt/FPhSDGarMn8UsdRs8/bZj2/M/i2KjlbNjuTOcNLqBjDXphdOjPMltXpria03iWJbrXblJYA+PGR9w0jzJYZEnJvRg76tRTBVZoYGoSWdrCSlu5pmkSrJ0xMtQo/GB5om7tFwZIShHkx6PUA6BjfKKCbfeMexiyYJyLwlQEZxmWES6NfZShpPy+F4xHqr8LipAo/6Y4DgE7QgSnWEO88G2kTGYKvBDcynbjufcR+7VjSN0Ibt3ySgJHB9JMdis9wbN2rER86ZYCjL60KKRg3YzC04dgTpyq1mR4E1mFldSNV59I5MMqOKeAm8ADeJKDf8Bu/heIkX3T3qjRIl1VOU6Gz9kwt/BhG0hWH1uuSzsBUziSUfHQ+pIkFW2+AU+j+5uBZeEw0FWaaVdgK53V24ELvohbMuYYYVnJx2Boh+g0mgh1MT909uAQ1l4lBLKkdxoe8Esgaq3Uydl07HpgV61VoUL6Cue3ZYWnGrGM0hxvVWJJpBcgjVR3AaQiE4BynNetzkoz0LARYKkhT7byuK/6BUoxa9pdRiUh3l1pHibt8YqJ4S2o1w71xd+C34M9u+27XZO89V4gfkVEB1b10Mj1wbhw2EQFIWe/P7J+S6xWOgNUwxH9rortE7wGaL94/hMFmlQXIYgdLV3wZVwC7jPyR+PsYklLtSvq+VIbNwoXjpzShXPB2JtzGk7D9c5S6fIPvw3mLg==
    ELASTICSEARCH_USERNAME: AgAesMClMVCXMQEtZOiCNI5NXyZLSNT+CGs2gm18ihr0rS2wq6pmWdnUyrcnBCqOnCxlTcJMSNEDcm8639Dd6jaseggFgb7PoZE3J99HChwMpI8CZewMG73H6gfHClsft9vUgXzCSQj5cY3FMkfjoBr2T2S4m18og6eYfm3Sr4O7egxybSe+o2zVVVzibRJhAq+WPi4UVcUP8Yf7numArZCrq0Coh66itvOfTh8MBBQtBjqdul0QSZLx6NNBuk6DSqvKXIk8CTS0arbeR7MVulx5sZhSPXU6n/IIF2EL4GtN/FdV2kdgFsMbcjQ2V7Wg9A4emF4j4A3Iz4FyvdM77Sk7SixDFFwItbUMcZd0m9sbkW9Mhk1QsRaX7KmNchpLA4tULVBPl5Ff/hfUDVCCv+Qwpi0zJH65a3ldJysqVZw0UPZu9cc9lrWCjvqRCbfb2UvPxcWYA+w2zyUhcnx+0xUpFyZDoudxjbWvLVW/Q5P/vDsTO7gzWR7cFa2L3vfDEu2/wtCCFa5w47HmDOR5KG7ol+wr4WoqC8Ht7wtxeRH7rejsQXNA5p1qgbip5pU7F2urq65O5HOBUgj36xXf6APADZPmvXVSlBAPmeJeBHAL5HTmok1pYYeV6JzSqNJEVd+rXbTz2DvgcS0AxegGKULGRptZ0D+DgKHK+jv8jiVrB2Z23x3q1SdHu0Y+zlPlMXs75I4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-elasticsearch-credentials-secret
      namespace: yas-stage
