---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-elasticsearch-credentials-secret
  namespace: yas-stage
spec:
  encryptedData:
    ELASTICSEARCH_PASSWORD: AgAtRGX/V7Lt9pZ7PfVPhaOR3ZJ38oUxlc933CaUElq2uSGwC19lwwvukv+07zBlM5pEgqHi3SBFv2ayNm6MKYHVtgYafoT8H1Hfo6n14ws/VUbESSuOFuKPpFO8pp0rRurDORmCwvxf0zl2ZPz0KDtokq2HpO612GELdz2pi/8SbyhGUj4Tn7hd6SeTn6KJa9bFqk9FPrL6ymNskM5JQiKnxYusaOJ/5wnT6QBkWfX4BFjJMLUkfqEPJgkTKqHQssN18YmBm5KFhQ98zik42N+AhMuUYoiu6J06MScoF8xMDMWpi8Sdyf3bIUZVopvdI0s3cUQLQ5KVl5TWv+X6/VdnCZ8CnEFkeiz+3x8nHMKsSlfNVLKcx46uAX9qcO5PrWRz+fc4sFqM+k3S9KKIrBXAuwnKL8GlF/xojymBsrfuCG2N1MoDe2jd9135Z9KmOt4oYQBCeTA0dxL0QxtXAaLDrW7Dhmb16LcAfOu5NqrDofBMA9nasit3tfFG3zFaPg5mJSnB4uYzcY/2IycVWFO/1mfmCOXuz/p4pnO1Mw7FlSpw+MAp3brMvkFStzepBRWZm9LwvK7dyzeN+bGGJKOxVDMllPB1iC6vXMTMX7yg1MFZTUTtbl+jsbeZ0pB1qxbUxEua2VtuHsrJwOMx9cwG9+FEqbch8OdDLV9dODEDBXVbCaIGBEFjd4RDCisxofIB3Xqt60OCaX5xlmr23DP2FZHkfQ==
    ELASTICSEARCH_USERNAME: AgCm029eLczXe5zUC0Ey3ZOV53OKmb4KBf+FDsb0qY2snBEa9tYX107We3irlDLKbbnFLIcUhXlEgrhnhJ7U9L059t8frULrUKuF5fUw/n/muLr9rbyljzBZhTEowrpiwGVjXUt8HX8NIlM4jFYtRz4JZwZ/CCKfP9YFmoQ7FPpfC+tHFzXgnXD08SFuXg83SixVGZGsbXlkwRqI33+iyle2yLrfZeBB1eV5SzQWIpexkPrtpcKrsA1+v7OFMl8vffsEncKB1E+stOo0zHWY1B6g2vIDYfhqKZfjAhILThNNzl8S0UHYFxSRkGG436NWWgA18xHMc7K1sPA7na7JlYqSpD99Ab22s3p8Gs41L9oIA4zZkAIs9W7afOzckFV5F+kJUQJ0YDPWt7IT3AS5Vz5E/ISwhc8D6i/AL4OqYoJDfchXJXDcwC1wMJEBSt4sIVXXJAVa8VPUj1c9ZeYHleTsMSuFl4JDIM8sQp4q8RvM5OkVHAq8qm+L1KVTDvbFm5PV03XBsTqPsENrgZyF6sEsO01KOgnRPnZE25JR0VS1dyc5tYpomze+r1SWRDizjWPQ2cdH1hheEpT4TJvF/x+TDZQHDI7EbcZ2uKQM39UYC6kcCLow4ov5UxletgrLQXpYCMgTkW+J+C1Qt05JKcw7tN1uMjk0pwnuTf0AGZh6AtaB8BF+egP5fKM5v5RDHj8Z0BA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-elasticsearch-credentials-secret
      namespace: yas-stage
