---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-redis-credentials-secret
  namespace: yas-stage
spec:
  encryptedData:
    REDIS_PASSWORD: AgBA2UbWGXj5sJ+OHLtWyGsa/iy0oRFfemsPCZIJxXaqZP9LPxs5CWJvRVS/ooPxpxLhCWXNx0Qp38V/C6uLpzDt0ZW//ffFbSmfGIJE/I83W/24ExpScMjD7IEsFr2yMowleZQ+sjJeZc+/54FcYd66vUtf8kKgkytdbc0+U09UyCw2I+Y4y7mzbEneYvqh+wdv7fOaD+VKD9tfzX5Sg4SkwvDYVChQLgYtzU7JJb2lxihzZHXGFyhRQ5ZpyFtBlpzuQmP1id+HbnxrX6js9NCUZl2qsw8Sj+ubBMNLAwnCO8EObVSNAataGqgU+pC1kbGxK9ij3zi2maMaQnPQeWj45ua4WObaSZvM8alO/VnBD8rNjwxTaxtCJJxilvc1ViceB1b5Be3kYD6ID/Deh4YtTidZr8k1CE+mIOD4vB7U/Yyxbidd2iQRiR3YWrvX5F3QtUOfTQ/VVuN6HfVi2zeRtTONh/RcW7FBgi2HDhbJEOjAYH3um9hYQt6rIOmCuh9xl+sQ/3BK+EwRCtPSaz/XTTbywXs2zCXIKyq7o9pIFFqrw746gxoPSFTKENuuBR90N97q99UX0fU6TOJHkVVtW7bytOo54U+l72t+k24M0oSCuDeXpeBcaZMreA8C+MAwITdCqptVoosFi+8TEbXRQkCLNzPQ1vjU7Xr4DtcYpCev4VkVXqLQ3FFX5zeL98at8C4cYA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-redis-credentials-secret
      namespace: yas-stage
