---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-postgresql-credentials-secret
  namespace: yas-stage
spec:
  encryptedData:
    POSTGRESQL_PASSWORD: AgCAou0dyFb29IDTxdVhlFs5fxBOQIBJqac+FTWvmEliwOI09+RwIjdn5z4AP76NFE+Xr6o/uziIDtuBsS3tadrrz7EXtHTP3INXeUWbXyE0Fc9uPiLq+DI0OevmEewRM2DGj0fS5uvVaBM0VnQbpJJHXtFhpqdS5HLy+PIV/oBKvt7mFNZW8DfLButT1/poGdoHzIdfWIZMNRgZ+hVHOuijXJQIsCD6qJZcBEviox2kulBlfnrQoXaTmGjooRNPfqsA3d7DpYPpyJ+BIvw4kOUMl3freyn8qVk4owCwCG3yPBFd6kpCKmvQ8pfkXilFNKdECTnM530/9Cgl1KAKdXSrBvfn66iedwNv2DDRG2y+Cqb6jLNYBXWSWY8kEQYWjaYAU/EX2FSo7vAe2QIabjE+/qoj428/8F/nN8tLQzPlpjOb4WHn2GWuOH/VF44JvSP5etyEY5hUtp1PWSGJfp+vmjBqU8JJj2kQlDdo/0hGS3K4AKh1FQqb/B0LNXgPYvei13I+9leEJlY9QUQfXEjkFkqX77f2I9KRn4NKrRDRHx+jbzVzeNg/9RM7sRFT/Ba3i+5jsGrcrz4TkMzczmv9B6QzThuKFTLja55a/sX27VnwT5vvlfokFv6lrVYvTzaqbGCnbfk36ejfOK62onc00vizlXYo+BCaoB4CF6+lj6C1zg8l5eUccvtE6I6kl+N8G60qZQ==
    POSTGRESQL_USERNAME: AgBSVdBlmV/OdG7WVf+Rib6aF/UkAASGbFuYvaBJ5WSLv11D6u651l+G/EZoinxNANvbgRMmsT74StEEHZKmwtTbDolRQBQboaeQ/EiAYiaO7l5h0hwgUdBU9jxnd+Ne6TD2yVTcL+ehhHyW8YK6ef/xgrN9y50HYcWr8GP7fOM2A7fWHH/xTx7wLkb6tJ5gq+sMIFOkOfl18DcOShC0QeMZNyoXBuWN/LcJkl7VoN5pyo3LB73K3es+Cv2tax/GhOWvxgdlvTbsfWYOBOoS6R7ZXnIOp8lv85lOmCgXzGnDBAnRjTPZNH2r++9hfsYzBYw+wzRv9Vv7aRJN1Sg7aoyhx1Vpt2YOXHBB/oGGglzHpI3el5WNoY0bblpEYnAYx+/je4YsRTfZ63+ojWrEDsGn61ysVZQiLdKAN9EKlB5Y/o/GHS9wgP2n3poMjN8tHyElyLWuyJCmakdk5IQxHECuwFwdvK6MZr0GtY15RqBptHeoWUqYgk0srpn17k1bgb/wHxIEMMdsdoaDyuSiv5sU2FoTE1uLtxzHcBowRS5Eimnq+VajHBNnGEABxcWHZS+fJ91YwjuxxaQcxavuVvj61PVXRDG+fjhnm0cYWVmBOPImPSuS42ZUIBSIP9D9hIYCCCyeY2Ie+RobCJJ2b15PVb3KE/DP+J5rrTngnbgvcWOvjIULern/QXyRhmo7g40kbHAxgjUjcWHK39M=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-postgresql-credentials-secret
      namespace: yas-stage
