---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-openai-api-key-secret
  namespace: yas-stage
spec:
  encryptedData:
    OPENAI_API_KEY: AgBz5lOEaak/v/Uj96Ooh6CQ1IRgt9gCZoQmZACYl5JOFFRD5rBBZuoBdDh6gpYFBCabIX0bUdrvSAWqoGgN1fHz6L1rFnKFQJRQu6jqx+tH5CkODApsLMdWiAKrWnQMttaxCNPR9H4lxMg2W6BXEk8lLHHw1pxRGvVtCLAmUDDyPiREjhFljQNjdnnDeMrB275WUwWhJDhUy5NgfNKcag3PxirOIrqRoQJTqipnN2YEYYZE4Qo2WDpEezWEwY3qJe1gwFvzrf4bX4dzZPc1FF6nKyAzWdajivmxsV4T4k5QpIyBX9MdwCPFdAqRR6RpgFUzyH/XJ8v9xdsmSylmKT80F+d2r2lr/it29C6XiRaTNObvndZ/egecFPOhfz2TjGgYn981XOAHQPHTpwQOzXNGVY35EmRmc/+dYvZSUyiJQ1VUt43dK6PpgWtJWp3ZtNeB7HzcznKmsMsiPFFaTTWd1IO7E/t1rGNYvQmz81wHuz/milrsq05ClLcXo0NhCPv9x/S4k6h/xZmETBmUkdciYDdXZWmZd8KGAJPRW7t+ceb/YvMyTZLnZOBL5bUsj8ewH81cQKPz90OkJoCrub89oXLU4UFvER2Ofdgc4iMnDWe21oTdJMPkqIUZyTR1odqbquehmfYH8knS2zluuzyIJ7K0P7gE/WUI8dfTK+BfIvSfNYY4zWlCThxdpvDnZbB3SsA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-openai-api-key-secret
      namespace: yas-stage
