---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-redis-credentials-secret
  namespace: yas-stage
spec:
  encryptedData:
    REDIS_PASSWORD: AgBy5ShqbtnGC9lW7rf/OkYZtxfGDFcOLeBZNY1seXSf//Fo8vK1VSKXk/bf5FjPyq7pD0qaEHqJVwy9d79Wj4kb3vvMjfAiPFeolZwdVgPDZwtKbirw7lEoTXRScTr4LJczsCMHl8qUgjlPuTu6IQviswqO/0XxAgp0kgqRaRIhixJPO6YmA3Zu1kjhvnhpHHNvcutmKrxlJTFJc3Aocazs+gc5ZPP/LhOGIVwL26X9F6yaQO/DJzKIdZRIWQkbzfRz0o8oytGK62J7SGPjnD/rO90giJcItnduzPumgdhiAEgI7Ui9VJE8giJ9XznQ7e6jONegYWzEnzjs4GPOEUR2db8XQszIGmwHtDBmrSlgfwm73UDHDc9tM+rxiZdrgZOiUjS2tpNO730Nxl+4XmGtPZKSXQ4kKaIE3Rc6BcJS+NhT3dWc7eEKwCLqwlS0aRk3vE5ddn85KduCCIv6rP0kERW28SXZPKMm2eR/H02XN2lBojwSzsjlbpjfDjqGPmzqDQOrDqoIAhAi5tCAbbUyrzMurIV6SnDMen/ChLrttFDsuxTpPPHtB7Hb0bXHEh4iCt53+kbDf5yhogLRMAQDHqlpGQr4sEhggBdoUGUr7B9cIBlWEVyireXH7sWMlqtYCKlfyXCyZkoXANsHHc5ZqvC+oClD2chaetJWjqKGSqPxSlgQDjO8WgwZYRC+OQadncnIjg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-redis-credentials-secret
      namespace: yas-stage
