---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-openai-api-key-secret
  namespace: yas-stage
spec:
  encryptedData:
    OPENAI_API_KEY: AgAPpIn3Ni/p30jcOUEM7UUWQf6Uzkp5DKaPRXvXI3C09YgsVkZB9YQHa+O4h2FHt2VM6U/O2e/9akOJ2Ia2EmGSpHYEJsqNJCsrcPvb6f9eL70CIl4eQKPIRKY2UtZHhTztsfUjX+zS6b4BlKOLGGACYqfYdF7AmdGnLFVlZD3sGWunsAT1VJOgAtUfePxNO/HfSRBZZIqgIgtKrJIu90pldPLTVDa8Dtqf+z2Yt5XZE1tHc7P+ZuGJO1wdDBXvpkDcBf06JnFG2JCpag8ZwJCadeFZsJnPeTvlJbQXpdufPGQ8sN0B4SXfFF4+53Yd450AfoJ7Vws88ZRvLm4RYDPTw4G6Zp9+r6LGdMro2UrtWG/cOVHJopsD46OWZBw4TQo6FiTPJ6YKnIBQujmlyei5N+hWF3hsJnb4kyOCv5tfEk+XgQBDof/PmyjFOf+WOjS2sauZqU3SNE3sI9cHgJqAG5S0ojf7pDGW/hnflE1OjMTMT1OjgQRcFedsCAA152LjSdvyJxCGmJqfy6vPtmBvggA4iiZarLO9MV7zC083levkr4DhCrycKinyUolJwGMy/CcxmYPzIXku2lv9CvLIsPWX9XgJ0Sa1h5q5IDN3iqBGqg+vTQykNYhAFjMdZWK7+yfMeUw70ztLJRudozzX1QyM9pxeAzOoP1nrbjC9O7nYU6P+673XOtb3p7of6PRk5mY=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-openai-api-key-secret
      namespace: yas-stage
