---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-postgresql-credentials-secret
  namespace: yas-stage
spec:
  encryptedData:
    POSTGRESQL_PASSWORD: AgCWtgPBTrTXnWza0RBRO8ojJd8ArTrqLnYZjuFzVOjfTQMbvrlVKPlQByWh/LeKgwVLAB5dLb8mLqnjNThyfYHc5yNJh8ni7laKV7fHs3Z1Va7bxfcXDyhCdQkkXFlcDa1QRDEMrflg5/OFsKRB/Pq0WHpZtf6tXHqpCFlOjulmPNnBWUSJmxuZi/cm6/YLTvBqX0AJO36kCiGrTtw6Z9hO9tUoV9W3EQiliqm9V35tDXE1zBd6IvHHFnOOTwTETv1/FhpAJOBmw3ImwZrgoeshkjeDrBT8B6UsOVeOVwKg2sdPjduuxhyQfbQeSNqtBgqmwoO7k5JayIQi4Ghtlklib8HmiJBhelKSMitiv2R7SCBuND13/elfLbbKhi6C2i+1aGViF6lr84D8IUwTpnpeIIaNyiiK5PZxbNC0T5HRvG4t6tKZ63A9WLaYy+yEsjumC81ZhFKmrleDWhUtaVYVP6AkVNs+6Ymq3vVrGJdHh+dCxmtESMlepvZNm51PRTdnJYOF26WQXy/bLeKefYsHGokQlMSjroO2j5UAdQ7pEO4MZvNFKcfmbFLOAgqq/XwDG1Yjh1WHOBYa8eUQxTM11g2th5YzJivgDA/xVgdkf/PCoXofGSIARwWsEU+AF8RGQ1+3Q8NhKD5vJSIGO/7Xqn4tJQUMC9vpHb+jAnqEo/42FvjwYP3oynJOAMZ8OF/bGuH8dA==
    POSTGRESQL_USERNAME: AgA++Z6xDvX1s1ZVJfyneDJX3gccbGL3OINXu4Q8UkbRTNT93Pzxlgd3ScDuI4pYDDezfANEl3rV1ihHoMZ6+1u3NT+DwtrVNcLje/Uiq4bNHQZ3U8Wn1Xaoeze+OuFCz7Z1gR67q9H8wEC0I4lNIzu2C0HvYsZioAWPTW9w2wW4wUoVpsl3pZhUzDr9vIZ308Nk2gdfxgXqQ421md92+kGToK8eyo6Sq/vrQPANvWvBG1dPrpg8jSG1gm3GnYa1ghf7faeGD++HsHLA0z62P68VxeBkH+EmGTpzLNA0Nq2IwylH+v/eoDHLWXdLYbGyoRm8f3xwhl13cwCPLmGu1uzF1xQ6U4oTS0SGci175iVj6LRZQlnHansQl6MjLNdF8gTlRsqq/0wJ4hAQdGOCi1yEv10QJPjFs82WdFmwDtMMRsLqUWuY01IadmIzSNZBn70C2YTnrnUJ4zoN9Fb9X3ARfSEJ0qpzF123pSXiApWfaKYcLjf6Cvfay+MJt5dNzIfGUQQezypQyZWWplpm8+EBSHIjna02A4gAgWof7S6BwMcTmzjyVwBxr5otLfIFY2uxB4AoPDCtTiqMNOynXvX07K90YuVy9+izxkAyEDlDQoAm842l+Wst+s5ave/jE5eLHdfzTw+T2IL2TbCHQ457vmaVF/VvmdGbJohNK8IuBSyMhL88wP2f0tyGMG+Dr3XdjgRfcrJzDX/bLLY=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-postgresql-credentials-secret
      namespace: yas-stage
