kafka:
  replicas: 1
zookeeper:
  replicas: 1
  storeSize: 5Gi
postgresql:
  existingSecret: yasadminuser.postgresql.credentials.postgresql.acid.zalan.do
  createSecret: false
  host: postgresql
  username: ""
  # Password must be provided via SealedSecret named: postgresql.credentials
  password: ""
debeziumConnect:
  image: ghcr.io/nashtech-garage/debezium-connect-postgresql:latest
  buildImage: false #Enabled when build debezium-connect-postgresql image
