apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-keycloak-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: yas
    environment: platform
spec:
  project: yas-platform
  source:
    repoURL: https://github.com/keycloak/keycloak-k8s-resources.git
    targetRevision: 26.0.2
    path: kubernetes
    directory:
      include: '{keycloaks.k8s.keycloak.org-v1.yml,keycloakrealmimports.k8s.keycloak.org-v1.yml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
