global:
  environment: stage
  domain: yasdevops.dev
  apiHost: api-stage.yasdevops.dev
  apiUrl: https://api-stage.yasdevops.dev
  identityHost: identity-stage.yasdevops.dev
  identityScheme: https
  identityUrl: https://identity-stage.yasdevops.dev
  backofficeHost: backoffice-stage.yasdevops.dev
  storefrontHost: storefront-stage.yasdevops.dev
  storefrontUrl: https://storefront-stage.yasdevops.dev
backend:
  image:
    tag: ""
ui:
  image:
    tag: ""
