apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  external:
    url: http://prometheus-grafana
    adminPassword:
      name: {{ .Values.grafana.existingSecret | quote }}
      key: password
    adminUser:
      name: {{ .Values.grafana.existingSecret | quote }}
      key: username
