---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: grafana-admin-credentials
  namespace: yas-dev
spec:
  encryptedData:
    password: AgCt7W/0JcvjfkibcMpNZE2h5J8Y+DTit7HxeyJLCV6Bc9lruDuvZ1VroAD/KDQcEp5WSCU5s9jwQcQflqasxOT/8mHV/l6iJPemQ1uwOjx0uZzpLVnJxmqiSxeDYam7QdTxRvC68T1aMZDMy7fmninaLRsFMAMPYJRuVefWLHf/89TkcHv/8B0Co0ilSgm+t74UJvmUeODhKmn4OUt7VlNvM2jSVXwpPmLWUllSMZfoXnn8Pyt2VDN0CIY11VecP7aRCYQ6LFFws05G+xIg9lgZ9R6c698RvpUcON2CtKeY8J/he4nx21qyGbdqCwioOW770yIbuVQKDC1Y1+YQvuMvKUoyqabbHlXbHMOAJ1nqkUX6xHyz9s7UXBXDEh8/i4Fq7tA1B2ivKOh6w5PecOw+eD+YaawayWe6VCCe5DDy24+78WMp4vHKVUsHxpUrmbnaG2FVNouXVwkTfVRQ0mSP3wZ2S0hGiUBm3Deo0rudy7/vh75KwQ3ZKnOq518fJIhkuVUeXfbeQmdAWPG80neMyywfte4qJOijNIy9QXmpRpygOWIL+heY0jITai74kVV9uYCfiVR4KrB3U+kZynsJkltbmh6Awb9F5jY7aLWY5FCTMf1/1RH2a+K7Vly48lqjOQKTCuaRSqYZNF/waSdeGU5SaREUqvA5b/r8KDRI9PdyP2kyysM1GG5xBIa0XJsNKA93vw==
    username: AgCOhnOBoknaoy1FRsfx5W5alzCMSCZ/VzFeNUCD9J2I4dhnud3rd+5haEdToyitMIcfzkHAn94A1S/g4io4XiKOpi+I+H/0Mw6lGZ5Y0nzolobZnScg8aEJmcVnZZ2xB39IAWmruv8F9Qe4FnkFT3A8u/GUWfUbR823BvpDpE/0ku6RKa2QtVyTAcC3IKH8WLscYFGOvcGwFyDCBIlTF4sEvq96SIaRh/42dMcV87vP8Uzm6DAQjNdUOIsP4NLZmJHF1TzQwGNtPEzXzv2SsWIWbEtOV0acuJ1s0usoEfifX/T10aKFosgINX7uF0Cq1udsqUkhne7110/jfklqJrJvGGmXws8zWb+VPUN225e6S1hhRU2XfwhRdE3z54b1wDyiIkT6Tt/gmjXsmTJo1xe804nToL9Zo7vEx9/vS/wMG/7wihUqTudo9plLzNVFs7l4xGYVIRBDeL+hPKDETsoSJs/SkVkxtN8O//V6fXZV9+zyLvtCu4yqJnZnZYmOSFHTiWpXcru8f/DD+lESIM6/Vqlppo8t2lTFAIiSna3S7uI80K+YHMxgH71oKPolojbO8f4lHRdt6FF8TfW5L+vK6GxVPGWhT9PybVFLBpXHMb7Wvoi0VNhLX8m8lGGUQURcL5m7IxcYBtePPZy+Gv11lyscZI9Lf+zX0qqY1j8LW1mb8+o4uBBW8DZtQqxu6hNbfK8DEQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: grafana-admin-credentials
      namespace: yas-dev
