---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: grafana-admin-credentials
  namespace: yas-dev
spec:
  encryptedData:
    password: AgBRMhJH3PdHNr+6unY++hjsZs8MJvdLbBcNrQ0uK0RrHrE25D8OsyRqYr2RF72bXTS5T4w9cnT1vbRoPTadXVUdkqBUWEW6w0f5YSpO4+fN4DHWdunbmePFnle6nf6ROCH9u0fQE+HuHV0syXdQFNkszB5eP4nCbkP9QHntKsowaRawWQH71YiLIa3Hd6nvoY5Z9efmkHXkBix6EiVlt9fq8XwYR5i9nxgRWYWQ84Og4Mj3jv88nZhPifacGU/mXxOYDiupRNhiUJiXDrtAVRKoO0H8LXXywLYfpUSg0BdZ1Zqj8bZG7vIMg609SJZiJcQPZ8WlOS/dTEWlZFU82wQ6/wQDgzAf5tGPu7MVlg0tatFO6vuMJtKBd4iPZ+ijMnnVPz3YqtJVUPWx8OSZE/0z8TGvY19Npwi+8ajm6IzviOxUPI+er5Mp/bpBdxSPsh0FR0vCKd7h7nB154P+WpLObxMoW7z+QchUPnx+Fxe1ExbAvInqq1yDP0ZNKC5ArQW0KhYNVmsEeGxWDpo8BVUELo1MN+WXdg/2/1sMw5B99J8caIScQiWnGu11MUymjfdOKr8IvUZEa0TIdadNuz5I80pJxxzyb9k42sR9dwKV1+q2pL793/nxm81dBMm4MVVLnwIrtQcxvz5CMcYiZhpt5+AQ0BLRQmgufGN916fiCR5imLHMIMCa++RsPvqA1QwsalPMRg==
    username: AgA9Y6G/Yl9Bnnu9fgaA+ir3MkoAPari8duy47NFCNYehrq9jO15uenrjGH37uskAhLDaJpvNOZFakTNJIfdVm9gusH9xQQKjcl6ZeHOS0qbxdowcZJfUpJJz8PbBPb5UqSX0ORYxjZdhyVls8TgEaE4UoGnKBELB2rFq9TzxxNTA9uLZpr2NyqLgPrGsbeGx/CXzd9trrg8rxXWjW/g3CO6MDWlCDkJYB5zW+zK3Ndr+NQfN3OWCJ8vgijnQzq8dI56J/rUnqOrfiAsUJ6A0m+7WcfUtC5OXLP/I9yPel3y6k0bzuZWKUZVZN3d452M/HNhYS8cFFy/kUwYcNR9UNuz6mXlvinY2utfWgJIY43jakQOBTOGKWpSiSOwpn5OHLts7ACabdyC5pqGB/P/oiVadMnOxJrEb05rhGgR35Yd5Rm7YGtEje81HQ6k4IJaywKOawaUZn4V/jxBLKlDRFY+iwVMO6wPHoiEww2fuHSg8YYLa+LB4sVKx1OH6arE3hs3IZGLe5hzL4VX4UCHCZZWxwb9IZFQACcbTRi0PPTTE+QAPh4dkYA09JSsbL1TKNXa+BpxG9G//kflk7SIKpDV5o43TK7NKltxtgCIrTnHZKmcgnFe3G8QPEsZpx0DScN9CwIzPamy7ZRr/cIrrxpimU6WNg136AfQX+6MOc28xndXzvbFLDosYMEv2z8MLbVIf8uwWw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: grafana-admin-credentials
      namespace: yas-dev
