---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: grafana-admin-credentials
  namespace: yas-dev
spec:
  encryptedData:
    password: AgBr2/55kynhhuCSCLFTDX8l1QAns2Y2aocprURL39yCxQ8ZXK1k1/z+Bci7yhUBmXv6bGBpKYal2xza8YbYtLULak0B0o3aVw6FqGL2BsDVO7xDgxZhuP7cdnAGoR0NImYP4xcKQ+rVra2oozSQUydqaFHbVBdT9rDSD7sveykW015IunXL49t+4cWJp4HV544yMTkJCJ5WmNBCL1EUWfdDP4XDr3Ak0RcR5fEJCjLlFD21+SaQxFo7BgXO3mqrSy9svka/LWWv8ob7XIVqec28W7x1WiqTM/L4XpHxTxHi1hAaqCVY4UgQUy9DnO9Drp79gpw+KeJojKym2kHEtPjvPFYA2g9CKscNttJcMFyOLfuuxMr0seHfiTr/H52Td+jaxfdzdTjEYfOt6ArrTFQDpam+ULZo7oEyVrc7r3U1uOzdAIA7z8QwmuEUDC190ScIMgPBVhFNaBkGfziUWQTLqLQB/Tjbm3jaFfyIBGEMkkf0OONZHjS9ovfSEOTeCxvSjPRgrqTxalTWIiEy5qp3XJBJgXge1sQPqE/GeeJLCJc7iIS6pSuj2nkFkQnMETxBDn181jXOUndkv9aFhIaMUlaW0DMKOrBOv+ulUtkTDWiAbW9YV8qLpgsCO7uK4s07G9T7Fs8YAHeYZQN1wTeza+ijR3fwjL2B9k2m88p21P54LAATy34O+DDBTOIHEYze1IK17w==
    username: AgCOuDRzvjzSqXg3UPgJ5C4KqKhx7nSYykClijU97GMcbq3R3nyF8Qm5tGOinMHY9jTqukEceGvt6Hy8VLFjKsqRG48wdDe4nNntfc4ajHs744K02Nl0VSTTHbqMnOFVGngV1hITAbtx9WAjFaD9d5JL4ZdFlRR2KUg/SEGUwPqeGSyUetT14fnXyD+PkVXBghIWU2IWlEExSkg9JBA2g9ME42AM8phfGHUzkH/z3cd+KlS0Y5objBuZ5tGUMpvptIJVO0n+x6vfoIEWtysoGZk/ROOc9EyVndKr/KoALWsWFPhV4CkxdW2bR0tUQZcdrfqK7N4kjxrWfLZicK4HyY/LV0DH5WTdgmAqx/ehXvli9vZKLKwHuOWHx9fVxYROi4r10IaK5GMGj43yQqfDf1E/2UWGE62SSFsCv8YPbALJfLj9s0LGoItXOB5UAnpDVDTiVKVcgs9MM65BOOnuovcDQjDkaDgEJN5MhnqBXWd8i+J/lVs+wG5VjUDrKksTSiSfORIv/Sc/73CHMycNzbzHsiY4zVOB998tFHSHJG1bCAhBcl1ym1EE90hQmxq1IOOjM2WWnd4Ov1ZJUQVBWP1S3cwhELhwFeF+ENb0z8b2Yd563PD7j/O8zH+7vFdHdAQp9/JScLS8+5PVyDoijeI4kHRD10Mw4KkfoasilnH8gprRb2QsCfqJaKAsRjLDudTbKoYzFA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: grafana-admin-credentials
      namespace: yas-dev
