---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: keycloak-credentials
  namespace: yas-dev
spec:
  encryptedData:
    password: AgBYS2sA2pbdXrfo2r/22cJT+++dcxOxbfuoGUUrnY5RLJyEDhhhiiigqPB6Vgg6RLNTnUvA00um46skZgDLAmY7PS3cl5Gis9js1b328nVben4rYTqdZmq610ieJcBPCY9ABSXyG4sxKdtTbb+JDgrZhZL3PlOhYwl2uanUoLX+OgxfM0CEyg3ec56lZbKFaWPgCoc6V3WEBHKPn4giHeq0hPoj6kw9esVpnXESMQE5JoEhG1cxmft/8KTMFOG0WXIuNiQNBkt+3qU+3y82zbq4szk8FUAWVF+XHOM348fv/pVQer4+pd2LsIYmXJR42ng3d35MuLyj5/laEku/TvZWxZGLkPhah7pWgvJoewkgra+osryqsys/ueFFzKtOCau3cxpN7tTP3mfpzx7dvz7zZFoLyw/JssKhoVsQJTDmmgtpBxOlmOWuKmQnJ/uYKsJhSnrzJIrb3f534IXbBQ4M6CUYKMsj6YplsJSB3kEM31TyQEjRiX/mIGXgRq9w2Alks2lJOw2oJa2Amf6ABFTlmx8tLmSmQ/KuFrvQuesd6nGXhy8ESA7oxcB96bsXPDOisIQSVlfY+pwzztpFW3HSoYsXlzsr3MkFYlVlplVqgeKM6WLBE5qCk5PGDJ7k2mkCoSgr7EhulATYHliCgJVBp+M1y6+ZcxkMfTvhyT0yHQu6Rf7559VpZDmHtTYbT6xPwayLew==
    username: AgBOvqdHQ9XFJWx/Z5WZgwDWbmVVBkLmSRQ0dU7BIWiSuM+Xlp7RWj53KXkVW+CRvRKcbqmrhuz/OVL7ZhnfnNHmrQpyPppRHRLCPe6xyNpB+BcJX48xNkv1eMsxr47/rTeIdTSzk2+sqUfhky2/GTF4nq9JYu3VQvVzw/BjNJU5czeu7OSF4VDODqvMozfJ5H+gV0HXrPOHYEPkhF9p+Z5NqxtBI27QxA3UtPto6pC4fDbMsEHeMrrn501EmaNCfJn1QXLOLVU5fMcJxnIEed1ELSYvfnwOvkgsZI3KAxfx/MFilwZiS/dosKhpR2TSFuu3Wgla1PvSXs8lpiknzkhM9q54iQrrPt+OjfEu3far7k9I3XaWNYmhnkJS9m/i3WSPTfUBESatZdVWI1C5hFpmJZ0ynIx9JIRkTDF80rF/oCztEJOs/Q3Y+3dNhdK+gB3fkVC5cF7BAD4pX4JDh2zHNmu8/G9uuWplesOBP0+OuQXBuA7CB+W8fEoKSJLU8bMC0o0RTh04h2/Uj0JLnzO52e18+V5aVbv3t0uRmwljqCyaGLPT1/gOeIUV3rqB5nwwBkWW8RSsgOT8N1pVUk+yKNEj/QIB4hF9b06Ld1VoYwrv9fLgZnLsf6m6ygpPw4zwcX1pUasBgX8ABW9Z+OQ35gLGbSITNyFVFfpcEHkxEVHUM79fSx2HL4Eiiind6lD6AmFrJA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: keycloak-credentials
      namespace: yas-dev
