---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: keycloak-credentials
  namespace: yas-dev
spec:
  encryptedData:
    password: AgCY0fLtE+D40lY9MjHa7NDJoGYryN/HVpk8ciL1o/fNtBVafwN8LX0uin7GN8O16BiOCmAuO6vBxSXjfqRuM4gcoj+Uinp5UK2hmsREdKO5tgED2lkPKMfuG0D8R4ePcci4LZW2cW2EFhy1+iLhzCHdheqb8XHL46EKC1pLqinpzGR/gUaVLHHS2kfGT7NT/1JejnJLADCKTxhObstTkjpZnSACZSwhiWXxJ5pBbalIW4LUftf2lLPYcMrIYwflWxrUuHReRhW/rCBdlIawdhCRqRjBk+AyHYDsoZyKdvP2B/59afSy8YCwk1j0PwKxBpXfiXdS6al//FWZ+mDq/6n3gyZ1x+9y710rVJVCBQdNrb31JkBHXwH5F+GGDgYOZLzxRxuwpJGC1c43LVWSyPFD/uZbxDHp8uqRe+mnQWmbcX0OqB8sYIX/MxNhCyWr3SwBLNJCE4W/LNiMcoAaJJ08cNtfPh/2N1YxqsFe+0AAtniQfrWzxKbGJwg6xzA1R8gupssXm1g2+T8Ot1C6snBAgAVJaEeJdwEcFZRphvwEERTxiocJS5vKeIUhn8z40q2hNzSPhwLGhel9S6GhlpWOfgzS9zZLFjStpvM0paPzSqi0YGdc7QPeeFHIKugv/JtyYaIruEW2dQQIGODE950uXzn1EI5kyLdgmIFZBZLAg2pXv1jYXz+Xk1OPUyDVHcUXG0rpMA==
    username: AgBrQ4+Pk+h2UK2DiCF+wX1oY+cFVJTCEevWYbWP1kym4nQADywoeNVeZNwy7xypIC3XqrWppqSb/7iOJR75piHnhrGnN2iUOTWAkWrtB4C1PCL1T5fENkI9txUuNoMO//6FT/MCWbXWWbBQDqRjL+VKzD2uBAbc6pXIeYGGonOR4dgxApOjW2ULOG/UNEdeSmcVixpi62BtQocdnxYDvSa6qJacaBnt63xBIIT0JdVs5rqkePR2vXj04JqXrXRJP06klOJrGQqjgVDiEegPlLz1F6hcFv8vgC3IOl6MSD8cGmc9Ye/xIUeqiKN1Igs99Bq5BuxYW37xGGVsCw/RpNovROExbyYxbbHQgG9KIfK1Fl0kGei/0Xdm3MqtAtx1pkh3NcjfK7zAXT3LIlg9Ov1Teo2DV/q+dH2cscwQjzuJzAdMLUYChmQwdqeqTqOQyo5YmJLcOuJo/EL3m+3ZF2dToKHwaH2LiZaZ3eU6R3TrQV0C4s2Fg1xTtOsdRHqnHMxuLo7fH2NR26IisqdKqQT2eLeuFkk4ZTX1Ir3CWJbMtF4MRVB2EG5MMolftsK2s07ebCkUFG6yEnHmpkSI+0sSj53/0k84rfl0nIH63yqbwzDTQvAKDj4PVknTgbo7sA9sKyiZNp8EBnKT2rbatuFMC7jtTEKTjqLvYK+HzTbDA8GXKtIQab8dEQu1oqDT31ADBDFLbw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: keycloak-credentials
      namespace: yas-dev
