---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: keycloak-credentials
  namespace: yas-dev
spec:
  encryptedData:
    password: AgAv7+BZC1w+aDhmfb8zl5Q7i9JeY9S9zl/xHZB5CgPT8emf8zZmkOKNwDFMH1upc1IWTFZZRpMl+IYLI0giRUoVMrY21upbCh1c7RgamMFihyiKe2OLF/7svc4AGJLfstao+ak463yjGtfWNae92EagvYPUpoK6tOdrr/tzfzPccTOksKTzyh6uew3tx7bBd2mF2PJcjNeK0iOwx2NSWpYWD5V3VzgSOBKQ89jiQaAp4D4at1rF8MJ7q9lGNBa2G2ImBwb2qavCf2TE/vEY14fPCe2jyyjH/yx5MFKjLIWmmyPNJktWWyTFp3MpQrpjGl2GFpz0vl2wmvkMLtRCPaYMvuaM+fliucG9boiTDTH3xwE/Lex5GebuXFJSZpYKua+b8cRp7oZYD/sk59u6WkPbOYKC0kQf3OtI4wIXm3rAPHXuN/8dJYLFdkbQL6oZxnHO2nLiwfH/BvwnG1ssny8WEesDjiOIZLOWhWH5J5QAZJoL0ZxCRshQGf7Xbtajvne5rDHgrslD9vGG4THdJjknKlEipi3trwWFZBpYsHFJqnDxVXRlcfS6ZbHrFNePRxmAKuhj4V5rf1Vzyp+JHL5CA9l6axNbFcvoD9BcXiKmuQc4FQ0sm9pVJr/r52EEWjr2XcwPRdREJuTqZl7+SyKlGKLDF/0HdO8DaZIp2LOjk7DqpOmFZwQWAolYpkwgbVSOO7PDKQ==
    username: AgAMtV5oscX8/t84XklBa5pMpVaktr5ZoPbnTLNZRuaGE5ryCIkNFSe62P3xmqvKIZkAEMXCP/F0rkEZ3UWqWUB8QCKZU+GyTgAiftmRql2yyX5yTRB++C0IZX8D8NbLP5fNcZib652Ib3jw+vYtem7qqPwddYWi4WzGW8tAEBhBKyHOo9dqDhu63hyj8/2QT0WpLzHSXwtTMW7kJblvr4Wvhd0RgpJeIT7UEzWVnaCGSqD4fyYw4msKCkraTEXoBV/R6FLgAVckYqQTIDtErTfTypZpWcTr3WgyEugOWlFyFbz5bf2y6MnwHRZaVlVbGBVTBYcq2Zx92JMSgY4eStqdbxr+HXM/rMyn5+mSGssfblOkVy/Z7jb5YMTSqeOdEzvwruhscVHY/Gikkbo3vKurtJ4NA+TaypBuqLBFxYapsArFMjuRf8eqnjAVnX/0LTTWcXNfO87gw3swNP01monf0DHT23D95rtHaluGVMVTX+CEM5w/gijyTi162uYX63N4fj73wWgZGh2ToaciIIQKBY8x8F66puDEW0cVq+qYxP+pcaLZRSV5+c4Y88yVOjKKPOO6BG1JxYDM6l1VQqkz8RGN+Y6rG+2XC6gbYZjy7nuNhtouvRJeWB68cmA1HK3uqCpbZB4D+bwMYYjj1SE5aCnfp/jKWfF5BMhl75Vx1s02Nh1XI9NoNyGkmA1DG7zY3KyQnA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: keycloak-credentials
      namespace: yas-dev
