---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: pgadmin-password
  namespace: yas-dev
spec:
  encryptedData:
    pgadmin-password: AgAiZ7S5me7T2VfRfvlHcQQNaUQEGAcLPfYnBGvpndi5tSJxv8TUY4OXm8frAaQyKYj9bt8LY1/ZPcvAZt9BbY4vyt30qaiwG/THp+DvHTtHPXCrhdeEoxUYxnw51KS7KqTNT3yDU6grCBsbLphzb2BrngzhcdXgsdDQVh3lwqcRsF4VnYcD/K7qStQu0iIbqOP90nLXcpLYzhnS9ZKR9XsM4SDN3fEEyAqg5H0IG/1jiTrfQh1Zt7UOfS6zalh0AnvJtGGHm75v/d55+F9anj7NZ1jC+C4HasU/psAQlwJkssPvs/A6+MOM84GYIxyIBLgsorWPQllO8rU69aFyVviYIBZGTSKlAgHIvRgNZR0Ore6TYbnkCVFKSQEPROk6dM1mTWDWJS+kx8RRTNEiAm2s0UHFmbuWPz58LymmFF7ecaGNm3/hjthPSFu3xSSjAzaDeEDZABlzvP0RsRNMBL1r1zoE1ivj43r6mxu8/dbHpQRyI97InDDeBbZcBowOLarhas1uhNeL0bfkipF/G1i/BRuBl3VGj+hPZo+81OMJuxkb2MfwZo94Y+dlPmvMKz66B4QFpoVRLLFncNPJRnNRQzkK2LVZ1u0ZP0xy46vPgORvdJ4MkjR2cPF1wnM3WRrgvCJnR8h2PpbPY78CG6qVYoKbpzgIE8bpli65SmMm7pLFavIghuQ0BQrGlyzArchWRw2hPg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: pgadmin-password
      namespace: yas-dev
