---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: pgadmin-password
  namespace: yas-dev
spec:
  encryptedData:
    pgadmin-password: AgA4gc2tikvpfgk7Or4dqbs7OqOpyKptF435pjRJy3Gws60csBFVLpXR3cPGu1XFc6nAlL/88iV7kxyjXmwjWXVIfJHBHsmdd1MnCHc/0HGCFiLwAMDyD7USQ1EWolVrBDlf1ATQuQCTQgfzHZ7RxqTdnZSdvdBJOZ2uJ4araWQ/hKFmHEMs0Z4KFDdHYafImyFIvAx6DXPad7NjIVgHglSIBzrSTrkwXXWQA9SQUiEWHFCQ/NJ7Bu6iBfDKPMy3/sf/eoF2aHkuFexvi2v0VppwQyS3FxdLEFmdiU7Ec7fMRKlDVHqGFTqTju1XHlIyu5iCAzENe2mT2yJHylwCuOu9AqDECgDRdyP1qLeesGwg/P94CQ4qD4SFKp3ozuNuIBdVpACy+eMqqv3PtNGPTkWBPVU0JanraAfHtV0pXqc/ZYQXD66QXI0nlyyAIAq08YfxKq05XC0EX85VJqBSkG8FWgsbqJcPUw8xEIiB5XGUS+htEz77G/8uI7h0N2G4ToBmDhHjR3JlWiSR4WQWaXnboUxYhw9JFsyIijDkI3OvCSQF6qb9GM9DgPwYJbUHt1YXEYgtv3IKOCstxc3TMzK9i9x7rY8/kIKQ/Xeycko1SA1QytJzfgS3c37R3NDMWcsYHriI3rVIKeUzVW4UyW6MRrddyOhBRdEJkfZRsNNv0AhwoOTkv2zzlIVGwtH84GKaAvhmrg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: pgadmin-password
      namespace: yas-dev
