---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: pgadmin-password
  namespace: yas-dev
spec:
  encryptedData:
    pgadmin-password: AgCIHmXp8f1avOP9MqIhqYaSNaF7V+vCOR4lmIaUqTxQBTfIrYgrEh+UCfuRTNPcngwR40VSd5Urdd1Q0ADoTraPF46Xc5vchYr8wzxQUNaJIhlgbKXOzOHiNYfUFKwlSZ1hZhjQCASr8h2K5rYGp8BYp2tfmONhywfj/CKS3/X6rphpxb2pFifsWd5VUgOTSXD79NOhhkcGxUXETTBJS1z709rf+C8uvDWgfWDaEEu1RfQkWYn4O1mSEI7zbsFuNzgVp36I/e3eOvqH3BWL/5cUkcPUMhw8gzU5EV2478TnPpeSdfFQI27djN8v85cbRh69cFRLgogV416MJsQ1JZlVt1g7PInw/xmj7OFslik0UZOe1Kh1DSoshUMMr4iWHPswZmFm/BOqYqu/4Dq3whnxDFFeW/PlGA8pjtbZ+LTTGAL89841yHIBu+DYKfXGFKX4oJoKXnTENFHmhp8V5kM0qU7tHCveTt0rTjnTtRM8ePVUHBq2IqreI6gX0WLzi9ASv891L7XWtAnKhCyKef3gCnOaHfOXWDn+OzuHv8zMDfsa+s63p41DqHhDHZcXZv8mBUdiwD20av5aV4oophH3mMH1k6pif06cJJ6BUBDKtKuWvZB8nX5FKiy59DZuPQA8UPG3wPY+PBIdxZncbojgEaHzzQBF5VZudmUh7rot5QOcLfj9a43JE6nxWC8tFVlaRD7OQA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: pgadmin-password
      namespace: yas-dev
