---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postgresql-credentials
  namespace: yas-dev
spec:
  encryptedData:
    password: AgCoIsdxUsX68nr2yvHnXV4/uOMosbN7Zf92c62OjbcVdqZRTQGC9mPGirejL1bhKsMhsN9nVtOzBXKYvcnKBQ5OA7YSioxv06s2jWFdPeaX3QAraT5N4yNl8GDjRGwErL1cQCtg0H5GHIZOBhXgDmHdTKvvmV1X/LYPgqJBCgaQA1KrovxwZyslReF1456lWnjwz26KnJkjaYpaJq1RK8YObNXzpyP0vv3PnQYVs1Ai5zx3xgfDncY0vJ+73Q97BpqGCxanm1Kw/bMsOG7WB616DnxzE5BxBpBPF/3YsXZWfer5F/xd8sEcEy161xrk/4ZTD7i30p8yztrgqXcQWcUFSY414duwUvp5FC53XP6h6u1TtIH5lVi34M/mZJoRdG1IR86wG6IGAcl+IcOM+E961iQ2fxFOvx+3q7qq43/489d+bENDHU5ljclk+wBfFOAc1DeAbHOHIgjDdJlfbqiZ1rcg6UrkP3tSZtlz2y49P/3dFWmZFMF8VqMUGxxEhK1AJn1NUwJSxN+NfHV+ExFPxKcS4lzny/EQAZ17zSr/6F33QMhzj4NZz/yyhhN1OYcf7wSsNrZVN5eUnYCMZnYUCOx5R2brch97+ZMBLZQskaiKFoppySQ8+zrYxvBztVlPXJOJgm2ELwqLxDWRu4l/6OKyzkuM1b6aRSjTpPH48Q+9JPBgA0HJrOcScbC12u+WLt1vUw==
    username: AgABPLXREmr2sXlHS7h65Ut+NZQziHI436v5eCtCxPvWFJnifzwGGp6pe9cReOnTv30Am6skSUrBNxKzeJYqxno7UoDS30HLd1Nb/MEDsg8VZQu9UcO2DQP6HefItktoU3G1u4DeJ0/3hByLhvrPzAD8F81Boa1oJ60CYuoTVSTmufLDJZdR5NFJHbjURUgMqqPdRWkhGv/DJrnDJFV5EWBpVMxK8fxtnUbKH9UblQXu9n6YfmgSbArqYv1QiR3cK5wFvWC4WHK3CltaH2vD6p3znSgHO2mXUze06NNLJsz4wrcf+bE52pc6Qg3E+oZTEhG8rveTPWk52DvHQ06jiDoSUfp1U4xzv26c+39160TzpPNJj8RLlyFZPgl6SESCEESRIs+a9SI6WZXk1hSp5fJHY5banFC5up/wkdU9Y+wYfDG1cO0VtWpkfhcRvY6gsBMnp6dII1y/FU/1HyAl9r5+9WVJHPr0M7mrTL7YjbSgQoam51A/9x6FUHuCPode8rTCH8APLnzh2vAgNQejpF7qP1yzcGwGSbkXst1sAn9jVncRACx8IVGXuG7Kmcj3PtFq3g59kWXeqhBo9qMS560TUoycKq3dnuI42mGcoaW4ktjqPgoUUD5PhTn1yxGBdGV/NIFIL+arxxtH92ncpmfs6LueZCoklr5M+Yj9BEBnQmIxvCtC0Vy5MbN50fAdqJP1Bqw2LSz4nJ4Mkf8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: postgresql-credentials
      namespace: yas-dev
