---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postgresql-credentials
  namespace: yas-dev
spec:
  encryptedData:
    password: AgBsarYkRCE/CTDlr6PpCFxFO0ouHQxfjRW9oPfwQElXEM1YdF40z/AXCVVf5Ox5DrFgxDyZrwQrvd+/XpRW8mfTDuXwmVImyaiq6lvLwSk3RCdgYSAEM5iqG+MKFcGX7gLjtt9fCrk+wLRqagotdxVeN040nLZc4mcugnUr+AYf03mVKUv2EXrRmNFyO0re1v2Yun9trunsSN3jznSOKLwZbL9gC0puMb3yw3STL3OJ8aQc0wRmz4KLEKP2l2J2K4CnEr0V0cCjLIZYepsWzFVwlwediK6WQoW+rvImizGr6Xjr3tO8PvaCajqJDizUmAh7+s/6aBc7VYYQzABH8KZxPNKrd51EBP/IzkDYU0/o91br41K9wpBCjU8JkYzpA8SUMt3A84FedxhdJTuG64OtF9mcw03x6biC8F4yvmwPZTnrzY6AfAy3v//eCPTBA4WmcW9JBc/rfUOwvcboMcntA1Jb/lUPcYHRb1qIIo2Fzl9fY3QQZoY15POFmkAannAKZ673Lq+Gu3utaPgMuG+JHkNRgO2mjtp1CrusO7pGedZLL69gVSe1XkrJZgBtzOd6H1Dqg9xfipN5iH48dlUFUcN0DAvDkvULBGGmdHcDsJpjnYITUA4wgoe+Yy7OVaT5pImOjlNiTfZslZcV17vcPh2HuQa/lE6XIrqdul1RKz2DbYFwBzeno5sa+5ImDmAigarWPA==
    username: AgCc5PoBteHy0TsOPXDF1neUVfWle1Fo4bXpe82MIhVbEBBh/DIvoDxAL/RKSHctLty2DLb5PfQsqG8M99nUXYNhPI9j0eUmfV2Dyrn5tFBV5pN+wju7c/XgANEQptpSRs2sy7YwCOkv/Lf513qjPGLJU7vfBCGCFEstr9uiBpiGPoi43l0IcsYY+3OLTOX9JSGKjzlrVjVI8v8xELFl+ENZFohOIEITpcdH7UMMpMEsv5gEd4GFpiW9JGaec8y1GONlo073x/HTfwig5kwyDVG+bVXydqFycMZjZRf3ovcSccfd0wXPkutxKep8qDPUojX4dmQlthszy1j/igL5JiriLjZSEooOSnjK+eXhk+Ec1zm+DBu5R3xoyIRVe614KMCTxfnnM77GjcZrNXK1DXDhhpnyLzDCFdtywMIE5AFVvHNosPuELOVEn/g9w2fEQ4ZXGihraYOstBzKzbVw+6K+VQrVV9hxupulHgca7BaxIC1stqrXC2O2mx1489Qy/Q3yQtwwdQMBMUeEfXje0bYlZq45laa6XFqFI9EXC3a7lkVUhMy+JOuXvAIdr3LiKUb80xnZODwjYfw453jE+b7lMKCo3AAXIDDLEq6kUsTH7CEu5FH6yNn4fa0hfvnjoOs1yawCgNxbRpYf165qv+fhhLEmekBFZRv5sKnTmJ4oxU3V7tISFgyZLnSGUxizyOZVvKVqJJYH+EKtjZ8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: postgresql-credentials
      namespace: yas-dev
