---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postgresql-credentials
  namespace: yas-dev
spec:
  encryptedData:
    password: AgCg/bfRw48pMKFL/xA9BNd8x5xkbH1fOiO9kEsMjyIB817xvFkf6t3fo9up/tWmSabtJovLETj26nU0TalKkvZP9lmuDd4cetZBTorKHQjmIrNh9DeOCh9NnRxXtYjmx7rDhnFVGBEb7yzC0fEEqVPzXuX21nVngAVw1x3vi069vz34/rn34S0/mnqRvi9fWGTJjAJ1BoKqx9/JrA+xADAxXTXefDKTs3lRAhDtXRDfiV/vgpKizdlKZUM5WJdylE/WENNazpyuO4RJW40hgDrfKcOyhjtwi8tGU3U1RMxlJ9rKgNd7L7wFYshWgUnXDwX5jb4kD7FSaFhd5Ixfj7/I108Fx8a3PKIHSDg7DTXjWUaRyzZ+2lYD7TitaMN/ubeeK4iJYNWu/1DdEsylTlPPzcCbqV/R1j+kM2RmQ1OkzWQUUxKKN7E/GQpjRyDXYg2AUxaB3VnRdz7q5ucxNQq4WtgSNZwJvZ5BSvlS84wrC+Nu8jGebaHj4CGWdizk0ZLHDlYNmYfFe1ttEwXgyXqVpEWZeMtiBhlqZNM6WRN377wqLt9vVidBY+meJ5tChz7a/PPN8651VvBfin72otcR2/s+G67dfUpzR1rF3hZn7+05B/Qsq4FBLJEtiFpJsN3MW4t1wfRinCWbd2/YDUzZWalxz09ADTC2Ev6CayjAbxl911XkHoyyj2RFVUprSy/NpTD9cA==
    username: AgBe2ojflIa0ftA3JkOzq9VgnuMnodBo2WxsKhUChibRKLBf2s+4gMRN0oPc9U2foMejd648LdbGd2Ux1fRwjZLZHNSGnFhPsfD4HAfXc6W44+qSfnizNjPQNWDVQdx0IC1/BI5rq0UUfRhntgNOMj5Xw79bCX6JbXFM/Cd6f0vChGnn7lUoDgYLoufeBWiHmscqsVLUvP4tD3vDbnvtrh+jPFY0bBAr0Q+YMNBte9/vLvus+98AnHpYFIUSWXa2B2zJmziFpx+/aYXL/uWrtUu+K8LaJfllNJe8rYHPFQPqZnUqk+2yyBX+0jeHwuLpKutu7F3ptbebNBgjxVgJ4hJRB66nVMkwaLKF0fTnkHSvIuhqOlyqzfoL6/i9a/aJdpXGpMG4OTVoCwLOJTnoZ+CQRQ9g/oBQ/2a+eFhmhtZsyMwjRXqSoNE21L47zvIgjHPOvLo5Xr8hdinbKxkLJWaSOtIDYThs/PPNcMDAFAcvmBhb0lFisKyAXpCfPkljT+wvJElc7aYnP/QisANtjan7DneTINXWAyHo+BZaBFlRvuWgdrByaw70hP2WOHNU0EmdgySX26rypGIJr2BVm0TBD5oPpvuUrDJvbcmxrEs6n0LDcaUVvvRrjRIXv7YXJ1B80PA2cNXB5ekeMJnvb7eKgr+lfLd7p6iwmeGQLF0s9rejRVD30qGpH5FMAkff5MQtcuLNj47i7Tnl2Ng=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: postgresql-credentials
      namespace: yas-dev
