---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postgresql.credentials
  namespace: yas-dev
spec:
  encryptedData:
    password: AgAdir53duiDwkT/iAGJjmVuB3VkX0WCAR6pMIyQZ9AI+tTWNr6w1Ek1847UnG4g6GcL66HkoGUe2wILkT2XtosSk73eZDZ7Y5tLJR913A48cZAcuEfWO3Rsqi8NDUNVBXwCRtxX51WhMZzokIe6F7Zj9XUi8FUUtjkf856QwIkLY2q0ca7z4mPHeDRFJWv+90U2Jayj+QQv7kHyJe+tm+EXl9vmpn3sya3XxPrJUgbLhKA9RRPa/1GFY9jqIIw9Hh6hPatCyPckB7xvqGrc10rkBIiAZGeN1Ex1Z0MoO1LakkOgjAnQTNAUicCnL0lxR38DIFayQdd3/WNCSEuLyDWLT6DGlU6mlH4bVFKF3fzdgNLx1/zRTh7461pgZiAbVHmLVHNDH6c2zBYVq+dxSBNfda622tKD86ltplHDbFPN+v7xc9Uj2iiIJDXbaJ4ioSF60SUt1NdRf5zXTraf+M6i5etjFKqiMv3AGdx3c0cvvFMebKdHE6wafyyEx48j1SI6m3L+2GIU5OIP4dyskeVcr+rTL97MXJMvEKO9zP9Z8c4hYZTgmBrG3mXA3XCmNn2kceAV1s3UXTPmCZqBE1i8vcgE4Wo7q99exEAlvBrix+KXjYlHmSLNWtZUNGC4xyzZ136/W1tCAV9V5Go8l5iL7T6VXjLHv7N1KBLsQC0xHJnkyDc4/URiMJ7LY0NSP6h/YATc4g==
    username: AgCSgX/a5CCktaIW/njC8SUS8zempHRfAItZBJJx8AJ3f67yNHy8LbXWcFRPvpMxcnVhoUOj8KwnBgbLys+53/WSQ9pjl4W1KsBjgpr5sfvZDhVFD8y+7RGi14FoKvKA4mwDM+woBb+oE9OkIzuDkP5JbpzFlddGTA1OcDhEqSAmSavnFypYQBhiMrO6NxnRN7ie0le4m0n7ZHDau0Rf1hvYn8o9WdoycY1gMpGdEYKeuIIuxwm9RUcnwZmoyP5fsDt8NGg9L/G5wVKBtlCdYc152BeM3xQZ5+XHw7fJxKQGdRkYzjgIzu6wksQ5eQPKU4xaoa5TeHkNi21NGBeElaeBZB6iTtAFjLwFI6f1Pif28TwdPniBj5f6MsXpEucPgOIIIR7l49wnn9M/STNHrKNk0ynOhYFdgqFPuiZrHodF4YrTPQn21r9M3iUZeF2hoJ9vTesdMsuWDkJNNo5bsDBua+AOq3qCq07E0SH83+VJKuNfCz/gL6CQVD4RyJUHS1C7T5uiD0Ke/qyh+fPTCEDru2byzMUk1g37LypJEiObGTPp9lPIAW/XkV4Wzw2Sbrbb1pUuG7WtLal6ZkH8n9PI8GjiVV9wyM3VjYsOBvOwfgw3to537Q692rRWypQv5LXD8q6Lyvy8S0mglvJucSF4Tgoc/Ak29hcKBrJGIT/zmMVWLu3cbDa4VVyhtrYLQTxAecoR3owssDNk/u0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: postgresql.credentials
      namespace: yas-dev
