---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postgresql.credentials
  namespace: yas-dev
spec:
  encryptedData:
    password: AgBp/KRQuZcxmQfGGdINwibWkjmfM7sV23wVZYke57dJVVV63zaE5qWuFu4qzgPLIGGeVwWNkVc2eTztrcWnZISYTTYB96SXiV8zEfnQr0+Z16bf7gAtF8L0POCM4C+wIgH3IXdB57QUYxMMCZrvlKVjtpfxwvWozoocKrrn0ZnhSI0OcHEM9x9VcHfF1XpIE+spnfD2UQhrJZB3bv8JFsOBU84KgDXAUpTZ3z9wWeLgV2O3Ei6p9mzQvKX3OJnw7R9Gt7pb0H6ubwEY5IxS/1QhEkSwXRNJEM/J2NLkXPzvU2wsg3/KXAlANNHJNAxmJm4RQxGkTq8A6GtmqQrusKtkKTl6Te3xAy1aWSKS+o5WbZHZefCP93tAQqL8wZ1cXdZV23LS1TKpPphh/bgo18hnVJnisdjBnntAV0mVays0ofPe0+UBa+U6Vv0SpKTh8ogEFZEIsPXrBTS7ywaWWlwitccFlmnK83Oug9BRLsE2yOE1LyXMkpYDK/uMUHHaaS+hJymn8C7aEghleedR4vgZVAJc1EkWvtX6VziX9MvNGDrJxkymhO+zIkD+xh3NCLnvBXcc7ExH5t+XyrT9JD7unV4DdyX1yXRfnr3xn2xocndWWjv3A6tOkBl2JM9IhKnLXTZSgzKSWfC3jj0Ys/4gFJv/N96TALcEyKJwQjU4CVSTdYNqaN5aGTYyTx7xH9morFPnqQ==
    username: AgBsa59oUv466bGWqtrIpGTkJvb60j0Xg3qVd53TdFB00jF2q+V4k03L0H7N4FCoMfNUQhV3iBeeAzgijfLt/agYM1ylxg1pN/M3/2MV6/N272lnDHeJzcTZ971REc54Q6vRycsIsyxp8kTmLkg/Ka/6YiCoMO5NU0a/2oCBxBHX+Wfq4Iz6HB+aiRt+67n5YXjF6hboVXipqXaq6CKuBw0InTxLzIZ/IOfEbQl8ou6MC02VJhI8tkbuKnimDsR//fNSVgPQIq/IJETAxa16k/E3abj9E15I5UPW5yJHBOnKRFSuRnxU6qSit95PNEGEDloL1GLXWPbBgiT5LksMXPglvoHjf485wt+FxL63024FKO/ojJH3VIHflUHlxOvw8THNQ4/95cccwF2ln/BhxGCEQUuV8CfL/gV35Gx39u0SdGKdPH1xBSJN4Md0MG8zYoCUtphuiM2H9YrW/Dqoq4imJhjawp1sx5BCZb6BkonZ5YcRDzvTrtmttzTH62uPKc2w953yWIaUmTJypOGju1sXwDAQRWecRjsL5SIJYIrdroliWzONdTdWBb9ntTxO7X+G2B0IAiEdpmxFl6llRbJR9MOd1SKnRxHg/1H9NePrNHCOMYwxOSebJvT22SbNpjqDfPSgsMXFiUaD3fP+0dWGfUJKWdqWOEzN7OIuP4kwC6aVtE1aJq+XgyZCQNHaa+JNxJ9NmK26hDQjZY4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: postgresql.credentials
      namespace: yas-dev
