---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postgresql.credentials
  namespace: yas-dev
spec:
  encryptedData:
    password: AgCDap7tOGj12M+59pS3HLY8i4TIuhl9iHoEkNuhWTpCVmEPpgNXpkVbGYWNhXvE09S2+7RkvNSHImpRDOyclcuVYwxwaSVQZbYEkC1yO1YqQYjamO93hyzBblDy6QppfnTXM2Mh3MZEfDcpT2xiS3lnpGKxzw7nvzMklif2jKSwRBaWUDK7BNU8dtfhJ5zKs9bEZu3u1khjBV812GJstuSm7GAq4dxHNWYlQTYFyncBpIkfuXYrY04Pqv5mU8JfxoaoScNiH/jXtH6Q0uG2StSHup2RrYHdbq+S66CfqYKVP89gqbUCSxTnlTj2QqQVtgk0UN/923d20/yhyespPLNK3Wr0NuoiYFtQpUq3T/P61sRNQEhxuOThswDhmzRfaeE8KeJAZ3Tou0h8KqUTckzvcR6UXE39/m9lDHuNKkQenItebFJ/FtrWxwtzkZMkjpq1xdwURZmxjnHOY/HIfDMguymLPHh1iwgTJJgGAmCF5mIgZkfuwXBPMXgFc1lHYjzwCqc1RYDmTXfXdzg9lTawetkkIx/cSbSflnnq9POpvEpvz9filt9Yf92YfBHFtDvZAuVymtdJS1wdlf/j5RNbfPIxj7maXKMZBU+T5z7NHHnOBZOlD7ANXFg3YaOwKjfMX7Uv6ccylCdX98khjQ51OyabgKzS5y6RcD24dfAgIGwSMsVB8XltqYD/XzX09OG8bwAztg==
    username: AgBvXLwRFo/yvo/sZ9+Q7NcWwydVVoM9g60kwL6dkKkc9PKpHSxAKXEtJwr3VHc/XEIJrjUWJNo5l1bJjASScSXFJjVxVkuynBK8BqfMbkZF0Vf8BPlgExjMBb1mwB0Mqq9udhd/Y+UWm/C4v6d1hkvOnBhlrhqu7+MOXG4WSqfrkwuVz/s7YHhkq45ydob+II0cr5iXbFx5Uk7+o4AdpcvkuY61yLU+YkMXTy442XIYhb5C39q2uf2edP0AxhM/0YbXepCIdyY7S/Wk8lqpM1GjWGEvBD7QKu3WcP9nXieJcNpQZyV/XIE2YWP7khlLUSO7ROi66DZwl1OC8wDOBS4khmfi6dFFqDF/7bBjNveNMTmnLf+pznBooS2zwDwVfTByGWxh2kooskcbwRfbocL20qEnG4cFnSWth+A3k5Hyuwdpb5ZhGsKbHAz0S43mm/qpHIkap+7e3BRDp9MbLE1WIHedhwkaPYbvB/FGrULB2ayOeFUPZlH5KNDLx40E/Gtwh+cnNw/VtE6XwRpUCRfWDvkmDu0AtepiKkYwk3ORm1qkSgancKBkVBfqrJUCrPLUO8k1IZtCPqCbKlnYyCP234Y8kGrs9dUfZLm41pYWdbJRfdcAeencGZaBazcBNu/LyBzUmtU/lC2Orn+NhFhsWJ4QDQNWW7xxGPDs9qbFwhjQgMZYlGml/L17RZyc+Y5ucVQxs3WesS0RJUI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: postgresql.credentials
      namespace: yas-dev
