---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-redis-credentials-secret
  namespace: yas-dev
spec:
  encryptedData:
    REDIS_PASSWORD: AgCPPGX5CDZ1sOUSv5UJ3593LqqAA8QkSE8Kt/FK9wTDDviWbj5r6X1to1duBT/Z7X4/WAvWNrtupOGniMqhA/IJVE1lsPWksVqnbFLivJarWx1on6QUhoqa0z+ds+1PglAECs1TSMag/oiCj+l+6nMgvFCaNQf+sQwEZ9g/Ps7Ats4fRI2xgBcnmJxaXzfVIbcS3UJbs1bOENmDWZsZPzasm8ZaMk7Ykl/prMzvJ6ajPh0oSSSrm2bm/bLI3yOa5ybxCH0281SqaqOxkAwOuSNz250nJBx9c3+KrpgrkjmIJIfBSyTbn/EffZCSmByO06Jfg+FC3lxEjV0jHDaoWwWihW8e/V6vuevQjk4kFyAs73ePDUEn3NskZF/c9B+MDPj8hB/vRSmOL0Ykupv4q+N+xhKrySkNo/hc9m3Lsw4g/fyM6BpVAXLwTbfIlnbiNIJspsQpK/3oP2vn3NSovw4yAHMJZaT4BT5uVR24/IgudrkxHkHPa3kFppFA9X5iyXSDmePXYnoCFHaO30kGCLuik/bWzWT5j5tomd0bHfjEhFbou+0Wudy0HCq7KDTrpx5AHAV/v/Zqf+KPF+ddk7eMrOuE+0VzzeB1QVqeGw73bD6Exp+yoKE3ODyyJqsDcokavZAvhesKfRPw03P7frNtjUQ/m1SEVsu1PQqhwimHvtrfFgGeysADmK2dOvtc1fyERA/5qw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-redis-credentials-secret
      namespace: yas-dev
