---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-elasticsearch-credentials-secret
  namespace: yas-dev
spec:
  encryptedData:
    ELASTICSEARCH_PASSWORD: AgBozhVc/9TTsOtOUGAke0SDLgb3d3ZK3ezgvouKmNXty0N9luuAGvPTzpyL5EK8fsj2WnbBgA0lZHoRhhGxK15eEQcmZXjQavZutaIEjboPyejIMqG+c7/zYcEyx/hUDEQkqVD68P5ovfCd8q3YtliwjYPFl0Vi1sphKc6VqF7CHgNbQ6W4KmAdSh20R1Yk1bEVdw4dZbXNCnJM2ECbyABNcyyUNxxDl6YOTkjITbYmQNevbY9zUtXc5cUMVPn0DV3kYUQlGaKbuK1dbt05FtjDDfhORWZg18WJ1s5iY1NTive19Weyhdi3ZNI5spwu+Os7llqzqSEUVE8Y3bQe+ebIf9Qs/3WAX9/NMq6Yce9IqpWDetm+jm7gz2W2qKc/lNq2ofCPUI/yZmjsoulvp2o+9z/1vgiACE17CO8JbN8tcjwE90dPUSqGpcVXQDtnLWkPnhA4WiNYP0Lc47Vo6/E615aAGNM7GWqpHLRyLxQ8HYjPub1QZ60hPz/8TOMNrYR4G4JKqAbkDq38YWMnGauFje+N7dod6fVjN7tpo+n/ZXFE+3BCE6t33yKAqPDmLIC++H4DdXNfgzVhRoOwcZRLPXDBNhsUX/b8Sj6gJ3AwR0Ojsgatqi5Qxa0x2F5dxn0h/ls082e5ZZu8fids78oPA2CnAFoulkHBYJtrBBi0emIKWvqPCoyS30s6JMnSm02e38U6cOUJO42r7eEscVLZCBn+GQ==
    ELASTICSEARCH_USERNAME: AgCKpPeML9lYmno/4ouk8r6yigeA9/BkBYnp9uwCWhz0OjxYJmXFywZcAQNHD9TTjF/NPBjq/XhojCdK0EEgMgvyTohjmXBRYuu+udDGJaLyjRxgkg5jrwfATSErd9Bm0T/mg+O9qBK2lI+AtJw2xERLp5uzrpOI0xTo4rzLowbWY7VvQvrgeTKiJlGPd2qWqZ7NH48ou0UuGKiRwBCHMZ/WwVeruErzJ4CSAe63IjPIivo76TkMUJrGy8o1mxOay2AwmRVSqaDHIoWVciQzchLurHzvVV02Ygnm0ELoLLXIJc1zeHf1CFa3YHMZEpeOV/UKoXF/xAjtFcPU6B9qUomV9t2nueaFMWEqrNP+MpAxmOQv4wMueRqS250qIxqqmQfwsbS9jnOYQ1JAGZOaZ9MMMEo35hkWkC025MwtSW2GhOKcixgQKbyB6vhQD0fe8v5SHm5hhg7mj2Wu2PovdZIm6vL23arB+y+/fAoZrc5T7IRqXDzuhPHsZCXjNpJ39ZHrO/JtBIk41/IvKO7rkFR32a4jR3+PLWUhznSHpJ1s7jUX9OsU2opGGLAHq9YXZ1zIKhanZ4zdQHZaVKb3kQQopBNSeQveSdgyF58rNYFPfAahbdKmJj17+muSYVL8WjORhebOr7r6NW54YxewnXVEa7ZjIzKI9ok1SxYyrRx3nvY2jGFFL8ajNGdr/U95QJn9HV4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-elasticsearch-credentials-secret
      namespace: yas-dev
