---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-redis-credentials-secret
  namespace: yas-dev
spec:
  encryptedData:
    REDIS_PASSWORD: AgAhfutBjTVH9v/Ml1fYB7OlK8T5AAYRV1/5THtVRRrYTXZGEgc3AZiuelh63V9QAaTXJ74zK8IeNo2NhnWFwTfwIyYMZIg0RFuOSS9tL0JaAxB1H7sYUYymakjxYpquOSeLOlBJJGuzwpNjrwq9tqZV0+i9tdyIy2q56FIsM9Kgwf3iigvw9LT69O4JmpT8RPIXRp9BB9JeT+qCoV90Zopsd4srVuVAV8eLbOwzbZvFSWl9EQ+tQL/D4WRtKlRIwAie3iyCOzOxFxZSa/otNEU1XcPgG0AkeOD1LQIviM2zv9So5qrMVuiFlcH8TswnLUgFrAB3CJuvy31J2m0gBidZuYuq9JfvE4pa3P2Cm4gYvB9zXjFOMSP5x5wC1w84K+bRg8xvdptW49npH7Y0P6ZTa4AOCHjTk76Il9HMsw+nm2Erf5kY2UgbtAzOS5BMkgqKPC8cDTO/wgumcU/rvBmcGt9rCK6xMMM9J/fFePNaQOcHr4bve6d7P/Pfuc/Xc7Tt7SWf96U7yAP/CBi0tfg7hFGyOaLdWWGyZ0Gek9ru5arNQ0ZwHAcZp7e1MrC7W63I/9fM8V8ef1rtKZ/WWusxcEWUBJBXG+0ehX6qn8aaft7hve1Kit08+u95VsoaNGf/qiYQoQiVGKh3hPhuDIFQvxI5f/oxoP1JxVaV+vBO59fnr7dRGJvn9XHJgMioHolg5TV8Jg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-redis-credentials-secret
      namespace: yas-dev
