---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-postgresql-credentials-secret
  namespace: yas-dev
spec:
  encryptedData:
    POSTGRESQL_PASSWORD: AgAB96yax7ZGMbwSYQiWviYZ5GfEjec4+gnICJwxoH330z9JvIapS/1wO81o2WiG7djPauESq2vrVBtCVGtpZSHcGYuqPaweSup3u5eUgg7LACpjw8EG6yjdovWU4rGI+ZqUZmBhOw3UkAf4s4QN9urD/IxhqWDDaxge0hFy5Y0/LBmZRSiqSQXMA2dnod6/zv5MidYnxwO4V7NlPJzG/TDjlMDewfCKlr2mRWSz7XqzN0WMWzY0M25+0z9Q9iTa0leH7PUYHDzzAATY7462yoD6cDpS8KjBpJ5IXI5JhfNNfLrBhCiOvU94EpemEjszxvVRWFAkn0WTXoRYdUSP9ULwVZ50GNUmq5sYcSFNQF8hNYX+Hg9KL90MC0sPUFdl56bZ7IZ2lXnkILvN3oo4m60Mv4hcjIZcvVZ0Mrsp554k1ORsvZlVpNfA/juPUsxtlF1mWBCZIKNBSLrFXEmkjMhA+OF6gz7ZuKnI/I2aQkIE+g5fh6KyfOqe8xFIkE+bynuPLxiyyxXfpeYoGJg/h1f8jWAZJGVklKh+9Z4ndxxlQsqH6m9DY0jBa/b0Y2XXX2kUL4381oNmq3EL4sg+NL1A4TvnikrxC1q8H1A01VIlNnOLtyhkU0ZZks4S/9MVuRJqNei4wJqIxEd6Y2ZiWXyUc5W4rz21aMvQcwU7GBfSTXVisRBtGzMykgZg9/0Yd98H6J8BiA==
    POSTGRESQL_USERNAME: AgAONzj7Ivpt59/bfjNFwBiCAzAzXH4Ectog6Hjrbr62/Lk3HhA+b+OsAf3SsLa+Dtt5DSUkMDXtjuXpzF/yv+AycrO5xIVMG6BQSCy0IVUBnEjJRuS8AhR4Xs/QrSvnMIbLEhAaeEc6Bm3fjXFBGt6qjpBsjZb9EhDWhXO08iobtH1phyyAcF7uAxxheAistmFiIqe02ybCmFqRrtnXJWHiY0RGuyNM8BWWNy3obe7/bM4616wY3nbRNx9TinVcyHQfU8O/uPkBgzKlcXj+N5yMHrdf8HKNnaeKG5PpOVOOmIpP3YzRd81ObRiBiBCQWaGyi118QNCE4Rx602LIdzrADDPoyAv5KKL9TgQzLQeMIzHzhkHLPH+It+tMQnmARiM6LP3k6hO1ScWyfYm4W8cm0DFIdbf6b1FxuW30Z4jsZQKhy2KD3Mo/JbeUKZULpthUp+q5+MMeaKjd/RBXxSN21M+FWIDU6sp8Mi0N1HA/ObLtlhWSNLjynMIddXoOYPDBCZKvwNZ80XvRzzA7PGcpsEdAeRTnrvqoOAUGCdetJyF3NJeSFgiYyT5EGezMlLOCgSakHQCqOtqqihjKJh50PJoBFWOjaZF6vU6wzpCFvaYLsqqZSdzatOMVvi6LgBVlJTkkLnOST0/yxVnLQvF/uWvOOf0SqOYbfZ2aXjRXCr0PH9kcUvl77YFZP7U76RqLcplYpnylGm320jI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-postgresql-credentials-secret
      namespace: yas-dev
