---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-openai-api-key-secret
  namespace: yas-dev
spec:
  encryptedData:
    OPENAI_API_KEY: AgB2/hRLgnt6+3ibVbNp/IEhimD4olaRNu8XjCs1qEa0AFqwrKlXjmXjCWBeYQmNB3px8Lw0zbjJ9kQASPyAcnSKNH9KoTJcCtwWwhJM4LFkOxd3JlIgVsNpilfo1D9e5WlmKTAja1+yY9V6cjvoX/90YPR7g86KQsa34NbYYNK9nbHECPoQtx74XiX6orqtCTJ99bCqJLhq15lkWEfPP3si6AGgdC2YkWTkPjVoNXU7b0/eouCrE1wxjLF+I+JYElV5Obsm30Jsgn0LNi8N5IpbyEelNFnNN3qUzVhNIX7EaFMVtVC97HdxS+Thbmxd4E84tlvwLeoN5qgzE39mbHI8kdZWQAKp/VNnesBUku9YiXs1FaQ16KYEvYlgwsD5mbAfzKtSbkPpiE14G7L/Vv0X0wd3582GNS1+Hm+1cyfp3Okp6r3EtbmZTjYMdNHctwQZJkNAqv268BZWdCXqLb/B9ZPp+69C4d/UBAvdaN+BdAYSQtyu/uPGx0Hu/QEs7XAXUiAEMSFqd3A1S9Cs1AeKbFBdRftKEAUZllCknG7ngx/5ugfm7iUDJYbeLqes6hrl+n35HUY8dmiqBRMogD8i0hRwz4C4o7f9HVyTF8qQ4kBNtZiW/Spi1YsCIS8BzK7w/PV7Dxe0tZB1pKiZUxcToNbDwjooLOGGKgl8F2juIoKt+iGCk8NdUsqFSiqYfSgg0RI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-openai-api-key-secret
      namespace: yas-dev
