---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-elasticsearch-credentials-secret
  namespace: yas-dev
spec:
  encryptedData:
    ELASTICSEARCH_PASSWORD: AgBsu/+xl5KR0XvB3t3FKVO2uYK9l+FkDh8NjhkK1Y8mTje2uXze+4ntEga6kj8wxZm4TEfbdLluZXVnkCb/HX8/AoNL6ZJ3BgtQkm+pdt2YXVLSzF9VP+5IapPrXn1+sa/gtlpcPCuT1eOuAq+YhXaYdO10my3xQ42pmkc3ObI5j1ubRF86ltEy1yWQjvXQVNvX72P6fUbSGtC89/1Gi7LInRIwVvfNod0SnTpdvqjG7bDKUSdfHN/MSvJ87CZHXK/Mq6zNL5y2PUpta5UlUqtUg4D6s9fzuyFkz3H5ME7HgfIZVmln/pVDKDXvjeu+sTT7S5kOm/C6eFSzyy6wO03CkiXSQp2QteKRaTSRw+wqJvIPan6mnLBFxSgJ2Vt/Rrc8Gbun31mXy4MPwvrHqRt5XGd2jQjymSJ1uOT6jPdAaXQDvw7XWuXBevMoWm8PTUVs6pcEGmz5iK+Z2OCbt2fLLa2qO8/OS/XbnNGBaj6RkmDWobeTO+uOPHD68Z0s6c7ET921Kk1GbClYUH0J5VBgkRt9A73Z6OeRfLS6ZjKgtyANesBa3hAs0fq1kE5BidxV8dlfofykOby6nKyX/kXZFTKiZf6gXZ+gDcN5EguWx5WjRNIo8eAUdlVHml4oxrKAD1R+/0LTaSHkvhooaYVgHAUfi7XR831dMNFVl/HiS3fE7REBiiZSCjy6cusKuhHpVY+yCRqc4kMIt9+AKbjbreFJmA==
    ELASTICSEARCH_USERNAME: AgABMCLval3e2H+cJyk4CUoZAAv49TW2QucWzAmsJd5V5wAmMysy1a0oVJ3adOuJWr8R3fddhdRsLGh/3WPtXeMvhyayCqrN+5G3T1aiw8l+Xru9VdIVdrGuJ55T6GW1/3moFZZsc58kjIFqJLs9O+5od3tG+XqR3oyZfrng95i3KGbHcdh80HvyieiJR6cvl3ZJHJnFxMWOG7m4iY39n+QAY8r0ORUq1Fz+c8LD0+J5ni7l0guTRvSlxn6rccBUqXrrnpxqhztOIDzSPRaH8/AQNYlD1hfmG+yZceq6NtSN0mk9NPtJCfCw9FMfvRHAg7yGymVoIbvravB8YxJcQWSxQuN8x40K4b5ngLEp5AVGfOgs8M0ss2Dv3pEassO+RpSpUskuIw3SIwp2adF3GycfilUDgTgtzcoA0mmigRAaY8V2u8kLylf/Hb70TpGMLEoSIM0Nst8+3Jy0FtRdFbJCA4NORxCVovTzijM/yoOaH+bmITlv/3iNh1VAfGRljDez/qTxjEsE2bixGbG1qPTx2pT4PDsu0aWW0HdAbcx98sUiwDki0DP4M7+l25pTjzpPqK41oK/NC0CWSO46WFUPRPdB+XJCmUEBKts7otH+bxhqP6CV1E21RALeZjFOKDa9tHOjcWU78aMB6sc6hLGi6Xk8a7Up9x7GwWKPCXH0H0dTXvzod+s3foQ6CEjeC7AcoxE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-elasticsearch-credentials-secret
      namespace: yas-dev
