---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-openai-api-key-secret
  namespace: yas-dev
spec:
  encryptedData:
    OPENAI_API_KEY: AgB/fUGQYX1ih98wW+KSllcEuX/ONU3isxdo1kvDOZaX5T5QrPWBPSe4EAqlY1wEklhC8ss1J08hftrVKoJ033oAnf/YIFmBsKZIT4E0olbRlN4lYQCzOFwWpBO6fWk9GgsuOspGBR9q83ZeV973DfAUUNZFhitXsaiW2wZfiIQjlAcTUt8IU/0llLJNKfNP3girGrwmyFaYmI1VK4bYgHMsXipnR4rZvaNKAftziRrTUSi0frhT6XCklOqJ7E7J74/hMlOzV5DQ7t6X0kh4cfR3vBF6F3dXN7M0IokHajQGgylap+GtKH5hMAT1gKci0FmcsDQTQ8PPoeZLHhMN2gWCxEwIM2qAUh3zfnZ4oTkEeW2pghLGUXppghnjZ5eWBJGzVrmM0ROmXJ1gC5UizKWdXeLq1y+bqfIyZn73c3/2ng6Tmh7HT6c/eZmIlZeGz5A/wNurKYhb/qWNZm0BVtx+cK0kXgkIt9a7IQRawmc0M3VFMeh69X0XY5FHQTy4TpZYVo1FydRC6r6E/fj+mg/n4moUZGFlK2HOMFzotuD1eRsKblXykXS/9TYtNc3rQwgkI0/BJiaGYLr/+28iPr6QoqGcUFr7OtVIqOwiQy3qDTeIM9H2uYq272XCUXFPZ1pu7Nj3JME51xFXa22WY+qpd9M0mFmS6ngm4LJ6vH88Dpc+ml8HD3fqEcAr8Joudt8mkYQ=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-openai-api-key-secret
      namespace: yas-dev
