---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-postgresql-credentials-secret
  namespace: yas-dev
spec:
  encryptedData:
    POSTGRESQL_PASSWORD: AgCeDIz5OVqmu7zUKV/cfQrfWLMXEr7ubE/hWc8OhDfXg3CIsyay+LnetFuQx6I+XqYBkzQOZNG3XM5xj/T4IhchndqGTesNowmsBpS2pZfrNzwOxRnlO7Bdafq5Tr022Je+a8ykzUUxwMizfMNX9OQ4oBAFdyC6Ayei9YzUauU4MZN7nXOEjEPfD9SxI3NUP7oJSc4FBP4k1kxFmNsSzg9bYdq6nL6rSfzve57PbTlr9w8/m5rP4rPRj15mC8tT/OamiUiKRyFW2RpIhj77iV4IHKJuzhzB7k/gSjn9TjFNKDoLYl0OVoDPGVypywYX48ibWgXXNvR0rK7d65QiwF6w2/nwEihPOY1PX8nb7z6f08DgsXhniAYcfSclgDMat/In2+yUYGZlUvw0RDtLielNaoQHLmdnS7YbdOKXY8h3jcfeO5Ngxn8jr8nm96OEb0Wso7MzJng3QMvNsKjJzWBLkTon5Lq9qxWrr+a2jdmulsHtCW7TFKaQEwsxP9OKrIQLkVXcWoWoIN1MnN9EHaiS+3Cmuxa68+I++3UT57ByclT4D3iZhmHOBqVkH8m9GA0NkjjJ+9Ju+JTUSeA9KnBa4+fpkSTm/ZyrnyyJFePUFke4Wp2WX1tQkibsEBTdUZD+fiysros0oiB+bkHPh+yC8UKnDn8hOKV2Vtd0V5uoJdbDQRiphNSiDqQne+2cn0fqvX0ssw==
    POSTGRESQL_USERNAME: AgBXNGiOpqh1kBuHvPcqrigJHE04cVYuD5SugewGdN87SmR/PEWfnX3CgkfGtkAJBCxT/Z5AmdxfYxiXls162pXcPt9v68nqjy8fxh/wxWx/idMEk3qu4XacBaff4basyij+VdakEXO4G/xn5O+RZun2Qd+SFKpKXBg0BzHs3B9HzUbG5EZxsMBp3l855g3ZbvBQcjLTEUaESk/neLs6lMbeaHTjheyjHcR4S7j/svzvFO2Lm6zNKnlcjLbwWQCZUHZJfep0wl3qhxpiXe6G8uooJLlS6wnEi2faYY/MGQweL0CGngP1uF9IK99XixJpukPe7Rnq7WeBOB4iUoQM8/Y5owp+DsdBuvsqMDDv66Df283XQU8HJwszTBpD8aXrn2KQahQKy1GOlTGa/hp+xUhv9NlP1DRBxPod596s0q5Ko+T1BoCqjnaUoHTXo6Jq0P8poBT7ypZqAjqQ0R3Ge7p9TWX6hA8bZ6L18MDRdNqHRUFrixR0BA5qz7tl3lmKIJN1cwvQ9F2HZooKazzdpPeQFyKVVDIVDyHSTgmo67hgHPUWg2oytZT6FIUnywwkj+ksPGvecG23S3SdkTDdgtyPhsxu1C7OPEdZN94t4CsjxQPmGOHqpvY02XfgsFGkZ5zjm3KuqHF2EvS6db2n0hdZnukscq1rxtSrOTAAwhIIkYbxJsXt8OnoFqvyDjgvQiBsX8fzEw1GJvyttjU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-postgresql-credentials-secret
      namespace: yas-dev
