---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-redis-credentials-secret
  namespace: yas-dev
spec:
  encryptedData:
    REDIS_PASSWORD: AgCGUBIxfXXMgDs2aOCwr6xMLXCGwiDYw6V0qp2mghKIPdw/hrVZhQR93RbejhPxP4iu1ZVECqA/m8zZnp5ny2o6ZMiDiYhY0PS/Wv9pgQsVogI6Ql/vxuQt5OWFQOvDoCHOtR1/FTUW0PC1nznJzXuCJVjxfPVmWENGTH0/MBE6lQauY7uIkWGKTpN9V9hWHfxb4ic+8V4CPTmmuQb2Bg88Cj1PYSk5caobmDx5sI7dnk4TGbeh7WEELzEdPwpMCi57l7BV3DR8i+zDQ10pnpYoB3u5tPpkAj9A0x6cCJZLUDk3Jt54iYe2WM1C5nQQd+Bgc84FHZo9yCoABzIm+q/wmiYVNborGpkBydQQegyxS5D8iRQwsOVMDneFvCWi9pD9rairQiXHDbcHommz+ZCCQabgiNFOQ98JsRCAwkG/As9jLTnZFV4JaIL4+YTk62gi0ABsxV2iQ0ZChXsATABpab1y7cwmJk3Z6c8uvHVJKCfrnmD9KJKd842iHBu8IbSJ9zuUC/0o+NC2YAjKIjhUc2vesUTAfFwCSn/w8KC9kLirIVpHMDBlSVN7hQF1hwCnFMpeQqR0tlNjy6U4NhtpqVgywFv+Q3qXSBa9ZCM6v+3R7nMZDVUngmJswafyBpgIVScJep0TjGtVXhnwQTMez0PShBFX7cs2HTggUqRQ6PmMZV4GVGIZQMv9OHQhChzDsGaRew==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-redis-credentials-secret
      namespace: yas-dev
