---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-postgresql-credentials-secret
  namespace: yas-dev
spec:
  encryptedData:
    POSTGRESQL_PASSWORD: AgCFdhJbugTi4GMP4YaTdeUOHt/oLeZKvWM/zjPtFnFEy1MsCDIqww341c+dJX8pb2vySTqzPgFvDFwrCXA2kYTNjoqMqodJX3Iadl1jIHpQGE74bLIp51pZPU4BWY2AOWIua4LKNhAzoEi56iFBdFhzFN8QNdE8hQbOGYTf3KyDDBDCES/1DIIhWOefp0PvFb0XN/vVG2wHTopLfqsXNj5+vBfbAewIbnYZYg9MOn2NvbQ+hyp6BUhiaW9KHDY2DBx89IoHhlHAHsugRpYLzVrK+IOgKNJNNi4aPuf3fuLGKALggWVWJ/cja/sDiorh+eTq0Y/XJjf2K9Fa3s0ba8DwGCLQAauAz1avDKsDiNwd+Qu9v9AD1UM1QhWrme2IytjCb7ZyhLPJRXmGB+DwHCitSzhCfaj0/2i0mFti/VrBHN8ZGlbd3+h8aAqikbYdco21T+jVzPl+AhucAFW8L6vBHiRfFVziPMArukgoonSZb1U+UvTWAIJckarnRAV87gqSCZi7AkV+G4i2vnxxi2pEsOwcS8/gH623kkPNVi1Bx7Mcs8TEdzCw1+da8/2jQxp34f8X8oAq6wEjhcvQlp7vhuGMjDb0CqAOWxB0ffsYQK0Bam3YFbUl6nnZlTHifIqjFzy8fxoS5YewD3wvFAGnIkjUIvODBCoDcyK4LGTk5Y2yAPAq7WGiwXmUwWEQejfgcWIxEQ==
    POSTGRESQL_USERNAME: AgBOL+b4khQahZCmsMfYdOqrW38WMUcjkS42R43Xx3tODUFhUH9OnqaNcfosJO12E0fD3xMJo0B2RXwWMtoCNvv6Naf4b/e9DhYNJyB8e713iTm4w+y9uPth5Tr4Iwk84KNjY7uucIwtKSr6ifgUQlVMRvAefd9sZvgQLMqEewfe3SgoaWeh71n/VJC3oxoY379LIS+mneXyLEwHSmu2eupyqo+xS+wxwFli1xMa9C6thAkt6JK3oZGGAygTSP9eabyh365Im4t/b1DAmHwW9TQ3IkaNoZWNFWRIKJvZkxFQ88d9mpGvkXrnuNdyVd9cQDGMtiK/IAY7uhUig9Je/jgfJBmFRHXUof2CLkFuYfRCryK0bFIuQacpqRDX7xpLz+YH7aUuaQoeujhx/LrVqT5jNvgAFwGRDRm9d3W/2BYFivNZWEKUak9pM78K+uPpX0n9EiUeP3h13+oPTtnEqU1YwkhOYiM4fu77QUdpr6nNehJ8+BGoVzekOKdBXzP6HPtZdLSAmekTXajuXMUi7ENDmsn8nUdYk+avuznTxdxiuSlJFddDUOxp22G/nir0YHXbHQPNkvyBJ8dWf9C7VTrS5Z8KmxjJrcQxUe4bBWY5Tbrd6hCJEkV4pIzytJEl+x96wl7xwTKsZb687DzzNePQhvFFeN930+QN8ZePDmPqa2RYxYvuchUwd+NgNOSD14OY6OQYd0mcCjJnIHY=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-postgresql-credentials-secret
      namespace: yas-dev
