---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-elasticsearch-credentials-secret
  namespace: yas-dev
spec:
  encryptedData:
    ELASTICSEARCH_PASSWORD: AgCBOpPBDg6E0QAVmvG+jUEdMx0mDn9IyXqjaKp+X0vvQrQhAiyOBtjS37gBo+o7G/qmP4gFstuP/VJuq1DWCzgecOsegMLoSeVmak1KQU+OwqCaXR90AfnGhrzD+36w+eVA/pVq/YfjykenCvuyabiamVdpINiT/vihKgjrc8x05KwmJvpT5nn+DdGTx6t8S0w/BN59HORfqw4ykFybHvwuEdhPcC/ye918g6gPvDo5uD2XDaPqrdwN9AzJ5GD5DBETWkqzcZ8E477pXu9umLLWP7/cvXBXAUMxSz4mTeNMEfyw036DqH2Asnp7S1qROTb4qcN6Nit6siujgsxVF9/s9S2lrGQll7oaOY/cGukaeDe0xkJG38JrJHWT+49lvOc/uBLn4R1cX7L2gDWzzqp8rmPcAOxYkmKuDR3EUsGQ+vkKPsM9R3As1ULJDbz3g/rXVp0bqGOCBZ1csmEc9WAyMixUhmHowHDYXAZd3EuRD8Ah56D+1XVOU+UK+/PjzcO+ec+ctRLmgKkeL3WYUodTpicQbpO7WIQKSYAsuFS33PjEZMGvdA/SxrD8Wg3OWXClnQy4khQ2x0VbQW+o7rDkINzhXM0lpsPyRAu7mDQCFlQDs6kWxNfHxEVD+bmsYWpA0h7OdA7qQiWaNl9JfPIgs0Y8gZgJnrcdlcnPFpkDBYKrEj7/uIj9VO6Le3HHTyNyi9xX7xCYzMcJsNYJ2WaWvezt0Q==
    ELASTICSEARCH_USERNAME: AgBzE1SrwCG1+5IvN/mywBBeWkOIqWAbwMXNn3CDcGL0oAgUPTjShNe77ZoO4C9MN+3tUhpgrd7Num0MBxIe83DnQNz81gATglyFhKAhqD6+NFeOW/tmaqoHDdWo14uRE33un3xqkdmarfvN/iOF4lryzqvqk56nZH4C0pwc7dAdeauFUc0XeGfsErHF4HujKew2dctpaav/ePDGpa4gy1HX2FINq3tIvZlYmSczlsae13lV/GmQPz2CT9qnoN8v6wcaqID1fpXafl6lwtEr81JLe8vFsf8TagqvjHMPSALx/yyLpzIY+HCxMM75y6kdQXv3VX90PVCeyiXNlKhx4luTbEjbWI/Yl8kCToGDcM7DkkCLkaL1lbyaV7kMSNEqG2TuKoqdW4wQ0K25w+pIsl5KtNOSWsdItEQnbaHwy8EJTPxozotuGJq6y+GHXMa4KT0dvxz8TdX751Zd+EBA7ayL0ax9xMdDQsLFPCPD1tjEGEruQbTzrKJnYTlkKMkThjxLUyHKjWRDDsSnkrFugjaiFzFNvdRbnbBLzAOHbY6PmevAOXVU18PEi56jRdKb7iwDxsyBxL/3pr7HKmGEJb1u7LItQ8KFAAQ2oHBQdle6CkKEc+tpRd60afhvSuM3b3Cjm449WgAFbQKlHI6w0R1cIgQCF7PlSOAbSTnns6cXKRxlKxMs/jVjOSrbfuCkNSH1QJA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-elasticsearch-credentials-secret
      namespace: yas-dev
