---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: yas-openai-api-key-secret
  namespace: yas-dev
spec:
  encryptedData:
    OPENAI_API_KEY: AgCJCyc+msO0qOJi22wlN39ZPPwGDQ7nUf0Tooq4xjAv9/5m+vRWz17MLHxkPT/Njk2lme0z3m5a1L5LvCi/LjEl4eolT8PiLfY73tYMkaU6NTIxTjU3Yoft4JIb2F7jS2Sc9ObMrM7BIzr6cUBPd4CgBW1rExcsFyRc8x9juzgTyWpCu8dgbr7rsrbNc+XADj+aO4w7L2SeF4I18xYQRikZD42RpdXxTt43Db83rEexLtvghQTIao2joKppwHjCqn/KE0WBzD2SwWrNnKelNBEH614J7LEnS1SVKDp1H5ev5KJZbEfmBo57jUmVtg+0oOMyCw2nKx5pwiRTyHpDPa/dBBbHTi5CAMkAds4g1n4qZDupjagsIvw1jbWGBmZND/HKJTvtMcPQqBlA9LWtvKbmmZuVK4mMwyJPw7q/pu3HiCybV7ZFeaw4qXd1wwUQh/SlFaTrNkDnjgL6szfSwZWLXK2iTKf3vylh4rCgdNUop8EKg0TLtgfEl7ZwVppoqklSPtSS5t8qCvItU5CWCuQ93mHJgsMyomsnm5UJbDBWXBs0DR2xlSTDGiB8yamhHO0ImWqfHWASwjybRIj+k/JAH9C4a1f4oLNOq5zqm/0NaTjWFL8gpifvD6n59BrBUuSnXXQ6X04X9v8eCwe9EGIMWLE+bopMepbliE9c5jmhP0pSkKfu+aL9esbxu2OfiNjcBXk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: yas-openai-api-key-secret
      namespace: yas-dev
