{{- if .Values.pgadmin.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgadmin.passwordSecret" . }}
type: Opaque
data:
  pgadmin-password: {{ .Values.pgadmin.password | b64enc | quote }}
{{- end }}
