backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-inventory
    tag: ""

  nameOverride: inventory
  fullnameOverride: inventory
  databaseName: inventory
  ingress:
    enabled: true
    host: "{{ .Values.global.apiHost }}"
    path: /inventory
