---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: grafana-admin-credentials
  namespace: yas-preview
spec:
  encryptedData:
    password: AgBHEPrChWpBmYYvoiGEqeR9ZmfdYYOPH6rDCzknWWRxoDwJQVKbW1oxQUauq7HKT4diSVgjmf4AXhEIbL8LGOC8fB+AUgkCIjhOwsYZL734vL4cOJ32qu+HbFe98WFrXSa5yP3pYNtqB5Vl+BkJd4uED2t/B8K4OFtuzkKTABoc0TZaITQtyFZlGNqvagN65rXnliZ8TfnS5czkpl1Ym/YSR58Pzul1YBpmDLSa9R3tjtT610Uo/DnT17McV///7+5l3Bmldz5NjA9iH5uwlNz5gtgv+wnIF8RGA3BQoPXkdeD83zNbFU/yOQG7w0bM6lUQ0HmO0+deE/ylgiMeuA5+wYmCvk1DSMp1fLrLPq66UrWh2rhofx2m3PBI5CHfi1BieMGp0M6RcHET8vAygV2wPQSGlNTVCLRJLOQgaVgZvmO/V6eTLLM/+ungCJD8D5V0bw7LxF2JhTnyDCbgz60dFsAwelBMDv422zOJgBUyMknUM7rUkC2gznlH6sv1V3tZevzYuItEQTstKSnKG74Y42HiHxo9xXLCNjHWW2BP1PXYDb2Z8W6/QpRMi0D6aa8VMnCNlEdplboGPjHuQB3p09CYHXiUnoY4qnEwqgDg7dtXZHpjuVYMT9H7Reo3VQ6cGUpNs0Tcej/ZfrMIKxHTkqLoJJx/+LOAUGXflX74q/YR0jVzTksdidddc6g/pCtbN98pSA==
    username: AgBObBU+P602PjcH2GYVDVi2zTx5rOEc6A3iqmShVZpDnHw4ymTvoYDWhnBnfNsDUR2QLg7K20f4c9rnzMn0UfjlhE/meh3RGbc4OaJFsfKm0WMqc1bD0f+N2gL7VBKuHqvOJUxwyGhFrViCMkGkhvebJVC86CBo5YlOmbWNi02h7aW4XXTfy1d8Qgkiu+qMdO6hfxydM2H+jdxuGZwcSFyAtCK/bTKQ8kIgu30h31LamYMAZdmet1pVlesncLCeCmW3/mAO1RULNNOo4e4VAkk14fgry399vLfD8oMoDjoMsDRSJjVLEgAW+oRnCiaTWFkFbpzQOxW9z8uuz4hs4zM2JQdRlehvKe0i7uNG5TxgbR+m1LNdnwjYk0pLViidglV35je+4ltQzUeb9ODPkGOG9I1/LOJZk54zJQlDNBhdwFeKM+noPgGcf/zlT66kBw0AW0sWvnwAbB5p9ABTp2pbuTzFFaIxS8k4Xxvw27t+1Nzv4zsRMKWXYvbHIbymc5WFkI2/ZpvQbeGId8Fu3MwPPaP4abuA2d974jWNFm4ZqGo/S/xbIuYzwXxPJrVF83j1Tvem+o83kdjgUwwNlnAOgl3EAHP7cWoNatWVyABUwyJbyE5wgKTdcXoRrVC6f8eXMiCmVg/n0KY1aOjubyLQB7eBooGB4oUwG+5FD3IKDsqqZhEK/ALkZFTqZr5vDF5JnLft/Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: grafana-admin-credentials
      namespace: yas-preview
