---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: grafana-admin-credentials
  namespace: yas-preview
spec:
  encryptedData:
    password: AgCNulAmjPlzQ6pFllyb1RGxJL8c7HtaslUiBQnNACHqN3kZ8x4P7A2GJ+lp0J0agSNkzjqU3LZoGsK32rNbiuMLCRRy2QIaPCRsCvhkCakJpR07dyLapN4xMmqQXzcIKhMWr90rXE1P/tR15HkB9bcOmS2cxX+v/HMrmaTZ2d9memceljUOojHwa4uchZeYS6WsaO9H6J+Oyz9spRbE3tHUC2x5tvzKojQMjg3XdsB3xCB05gI1rbqxu3Hd3eAYanPtOxzRdFFitWFM6Tz8WnDVfuPL+vSVw+/UQFQ+JY3LtYTtxgXTLlhPbhZVfIH5FBksOs2KqYA8vbnT3Kz1ZG/zJyno9dhpnE3j3VG5Lk4hmdZVrWHtNF742atTdLsH4OILiz+twKQJhNWeAibUv3/hpFa0mFcfrrZ6MzgfyOEISt3PxraetjKoP3pKPcjwnIZyUpnEfnFZAaWGVMftetS+kzFAiSubTytQ5anKhBdmpC9sKBMr4tvo2xArs6Pj+wWNVhy5PjS3p+YN1TmumexXHQral2DqPvSJLLH26SoM47rwX3jQfCLWK4r8ijS2xkT2jrd6yiXt14PQA8L3azQesjgG7AlJobgf+3VEVfAOTgUgkFj3sL1WhpQ4QahH7qe0EitLNHUBa2zT72Isn5/0Dl1HaDWpyzyhtGwFi+lAEIoCiDAYKtNC5pX/4i90/f3fyYIVvQ==
    username: AgBm/M/hEh0bruAupkfsuP1ZFVIiYRL5IopenI9wmDjh2NwD3xk3CscFBkag8MggDkJesX1bLjLlcWn52RcMOkXZsl3M4Id7Vg36m0SW54WmbTyNzvmmcoGulpi1RCqKYn/7CvyMBHBGUs1hLEEFVSYoR1pQtBT/4CJxckySTWwxU2eF0TWEKqvdVcgIAeJ1y7pEFo+lCxCBtwHnqv3hXlmGPEg1Fi03W3bpkfwxWoPPRO6OJ3VGWuokzTX/N30CIZmUbP7F/TZ2iljaNufMpAGixEaN20O1yHcn4+tHIo3OMRVSg8hALOh84eiylKQSDSTrXVmzuXxRrxyNzLzfhP4SeOQCwflGq37IaqUgXydDL/fPganozWkILTEvFgH5T2sWIv/2U2Ojb2dJ+Scp/JxY1mbqSogkJIBYLcQQ0aCRXVnBGQ3RCzKkPSIJ72eM6kZag6ReuUWwD9MD27x1g9uw/RUE0Z4YT/DvjZpWuG5CEouLwcf3Ql9dBxJ+iYwPLFnAGC4dTM251hLKahRLrEqHW+rv7ke0nMhidBbrn9esPULRYAXQSaDBfhcJI9YARqCzf6M4JlcmskR7eTI1QCBbZJlig40FPBp7ccFh9ya3LSD1v9qeRI2qLv8Q/uh8kUye7/87OfbZJySmsK/d/yoS+m9erJVST75ZOQhy48D2fy+CC3vGEeK1ifTWzS0TzFEvzWW+1w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: grafana-admin-credentials
      namespace: yas-preview
