---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: grafana-admin-credentials
  namespace: yas-preview
spec:
  encryptedData:
    password: AgA3c9E6mGoO9xwFLcU8DKUIzX6vF7bj2UDpz1DOotBgvrx72ZDaiASkDZ2Nnl8iRwDvfmt6PG++xpKTCFkS8moXREDxmEwSPUnMk7mcp/Rl2UlOD3vo31cUKRy83EivTu54UDS6hQSq38u+USfMZ59YJbT5FBrIzMa1Xje1mrALG/mMFuqBzvYUKxB0uc8C6F+KuGcZZupTjKYPaMi/Lwne7kDt8z9niqP6RlEdrbcsiFlJiKURmbYODghKbOYmj7N5D+tPIE/t1kKdlm3DkvdWrZflMeibrsWIPzd2rQDMLI9e/wg6ZL5JFvPxcQEjRlSZw2ttuCfi4y7Lf2eBfTyWQnLRsUokLa9sF+BUEuTmUqMBHev+oEp+AJMyRAV9bVotsc8rl9smZ1vJtQRUg330B1AOX+B5L4Oq+++xDxI/4D4snwYMX2cQFlSPtRHIt/7+karYqhjp5Qh3Ig1XculOqo1Tnh0xeFyonm7wzpZY+Xmtd+DV/pxU8vWwtrTbjNgF2DRZ16v7SjrEcNLX29w/N03zfwAaTf86bJdyBugIg14B7SL7svJwc2TynAVo5vr5Ff7uX3sFmMFEOJGTrlAGVIx8rGi/NTdAk4KJXFtLDQo7mn3hMCRaFbSCU5x0RVOwZpRSwFFH95+2smZt7fFNEpYx4LazS3AYAbCHZm4CP1WXmJ0T5ec/PZ8QSmEuux+prvseqw==
    username: AgCHh3G3svvQ2IMcxpvbB/QEAdcHaJz7vebsbLIUl0VEniFVZa4uI9JfGywSbMEuI+vhYhSyJIauwd+2Au7ZoHv+1vvQs1pbtC/vhxuodJWkOwEfhjBIutk5YDi2IyiYL6xZK5VS0fzLQ4QQw/Ysi4xHeUhouJxPkfzGKfva9LsdceqKGOv7O7JgtxauiKUnArH69FwzU1MI0cROejpRaShXP4eMh7KK/Vw6kTTrR80pQNurWsrad2tu1u4Zv/+Gxv1N4XRgnnBrquNlbKnGIddDw2ueyi2pa3XuJARseBrbWyeubMA0acolMap9ysaDI74uqRTVIehxcJ2d+1HPjSMlDEFcTjwvmbaUNYvfL3535wGm/7xvc8DjvezUA2E7N4d3XvdtKZpm/xCJf03MlQUhlBQqTth7kaScS2tClzQDyQnjhJ/p5QOvPV2/dR0SrNDHRcdfZc1YBxBHS0RrYo913BWjM7nygs8ycEu8J8D1FAySf0YsCdaPhltSWnbN7up27OoSIO+WdEJPDKZ8fFnm/plEuavORZ2y8IHrluEEJa4YrE5RgbbpY09mPhVUNhDF6CU/HGUy3liwYyUAySaXZyytFrPbL7XBDdf2MhCAu3uqlM7qLEL5pRT9qax0af1DZwcxovJqVHroX2tYjDE+vfxTzSUiCeTvG+LUG/vG03xE1bNHm4dWPftyMtkI/JASM+g8LQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: grafana-admin-credentials
      namespace: yas-preview
