---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: keycloak-credentials
  namespace: yas-preview
spec:
  encryptedData:
    password: AgCHVecIepnVxR3Lci9VQSC7voGzlWnha3YDiP9wBNPjkbn25IRgwNc9biK9+ZBz3E0uHmJu6vmuR/EX/YIH82nM2W3CFtZ7cRYjcW4GWejAvX0ErtGZw03bB+sEkjkMa6qHZAO46Nye+6KUIjcCJMwWv48ovY8RxL8eIve37NPrdFRzFp6pDXwZOrzdHHkC/ffBeC7b0LOWe3/yLjqoRhFeSrhdUODc4VGfAXwpA+PP7EMO6rqjSiwFn35ZrnXvRAU0IyLjso1QSWA9gV5oDcMcILNiraskfzg2HxJ8v8y9Dru2viMg2Ng8lRO2wfJYCilXRMA4afmvlZSmSTDPwaVwwmo1Lw0GPyB+c4OzceIft1SRDmiOwXZeUYD7ZCN0SPXaW1aXz1g4sFIGkMEqZgKPz+z1FgB3e9njSCzi4+0Y5Q3pQm/tFa2jxCmRdE1r8JnMOaThFFY1cMV7P/mcS4Ua7nOrqp4E/HRInsN9TrIEHUbCaAyVgZ2o2yzuJb2mNw7e10vZS1CAS/O93CShE0xpucE5vKCfYySE0X8V6PUFnVBgG8W5+5nL+o2Gmf4RXekefDq23PdoYmFOtVIzuB9Wo15u9ygsPMC6fghFxB0JO8SXtW1MZBeN8EMBxyXLMXKqNautqAz5+CB37o8LQRdHLapFSJSt/U87AK5A9wZVMyKoC8hph478g6e28cZ4u8jcLT4AUg==
    username: AgAJNahTY2DMsGP63ZvP3vuT/3RVmIcxcmpcPqF69DXmkZ5yhu5qvD8Jd/mjAsqvKxJdD08s5sVOzknuokuuRv1vKNXI8Rmu4nRh+By3I77xepPqbOvJJEbfKzhA1QY2HUyl6qoV4TA/w+ojWNrUX13mbsufj8glSivRkJWwlWk+eDdWmX7EOQ7xNH0/b5uE0QssZVZpfhxdNwiNPaq+bB73q3BR9vzdmfn8EJQ5a3XBFJsb6nWHFemTfXvxTfcC+3gkwbX7xnHCp3rEd0V0Iw/WnP4CyVDnRxc4lwE4/lhGheRDJ8sNa5Rha3FqKytslaymA0N7wqxfbgpRF6f3LwuTXUNvTXVKIDRxI/F8/3hhPA7Djo1QNgavmKXM+VvycMAWZXhnuotWOrjYTIanrKG7ZkLbQylcGDkedM1AWGHBVzzhAo2OoCQ31pEr6X4IaNmWNMK2cO0vTh5cki6FRP9AcAURplsTN09t2LZt+smBNknpEB/YCJpenI0qeWZ+eKJ511iaFQhc22wl2fLdkhKHqoIUqsg80FrgT/5Dcj+qL9WrwbWHSKPEmgmeJbxatPP37UOu7KFc0yRD2JkAhy4GMFlUfpljyUgknvrLg3Xm6au/0VSyX3v/SVbi/PkmrfAAtbog8j6yFqTl95DtkCloLW8UDbfvU4YHgGH/4gSDx3DdquH3v43YgUAhr4w+ych6A+RUjw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: keycloak-credentials
      namespace: yas-preview
