---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: keycloak-credentials
  namespace: yas-preview
spec:
  encryptedData:
    password: AgAu7fu/ifT8lPJG7rwyKRhqIyDnjD8T3VQSSSEG1/KR0iDLjTk5UNEkLcdDLKeXg6LeHuzwYG9MJpryNjt9UlbXgscX3McorF4L1AAZfxNkwBnEyaeLGhoJf3kGX/G71Al2yiGBKbV0tGIRfHyjPe+0r5zwjBdAXUBt2fRxzkcCPSKgyPJYYcpTi9M2XZ4HGXzCVwk/Vr1ZDygPfoFnKVtf7t4Ed+WwLUn/mWofSmw81eKSAsHsBrE++TXw70RzRVkdT9RlBFVw2J93IRGCAbTmQ4nHP0N1tquBVGFnXWzBYMc6aV+JYV+dHFgnmqUd6q15cPjYEFrYhIysycke6IJJhnYra4/FNbW+LIto8F+0Xm1XrI7zGhghGwK4sK3Eh6yd8uhhtxBR4B3ScEzy+dbBmqq19Y3w38qA6//0e/EG5poxMaU6E+siKYu9C9qflnZlfvICOtNlgYR9pn4hAW97Lcd7K2mDk6QSjq6X77q8dH72gnXZWcuYvT2U/WvVReZDXQB3CqfN/Wf24rPy6Tci6QfsdzvHgo/YvS6tYKlWzs0Z05RAlYSm0Ckuvbsw0SK4VkHO8qg+hRCLDJpU3YfPZ5Fhnpf2o5fmFBp/JspBopgO6XB38V3V1/TBSKnXl5hljNTUdnTAkxSV/2AkO+QzwO2OSv9N5UfcaKO6mUwf/y6HPbmscu/b37YUdYS/kFONOoKpzA==
    username: AgABwwN3ZCAJJ2JphDFbV9HFdC7evddXpVVqTNUXCmEQAu1ye8scGbW6c6o1cgQ8cRKPfZJkcjjviir/dTb7rHSdoYCPgJVi5L9PDTYZN2Vx65muf9sCoxEPK+ORSNYqfwjXklw/ZSIlMrU/2B6vwJ2mXmTkcKmR94pKiIlHAvUsrwbaapRPXJnZQ8TVDFqHlGy02xFCN6KiGvv/7Vx+kGP1qBNR2UPFG5zOFbNCY4SS6P0GbTlQGmO65b61PCssTlmygrJhcjEXns+plGZwbY06L4MAa+3eD7IQbXL2kpe4O/8yroddi/wmngd08kvTUtWyAL6BNLib+V10M8w0VfFzAMo25oDzi/oDiYLCVPW0aj5ZFPsnBNIvTJj5/yEcDfWkcw7yW97rpjL9exsRfZTJ/SSaMiFj2i6Bbm5fsYGrNrmRbvTo8BKCQInSRelGbwfJkLS43BEDDE7lSGaAAZq/WQnRzZE/gwd+is5NIWZ7iojuE/6RsqHhSWX908o6M1vdYcfdAJxdC5oGCrLqhDj3BYCIMZLkGcxm6pJjXLS0pBg1XRHJR10n8lpHSWxMfgKwETRjzEGWS3s4i/9XB/CmK0Wg+M5s+4JOswJbmeieW2ZelDrjCfzGQXQ2PoCQcZLupp9l4hEGf46Hoi6I71h5mTxqdARGyjGL+0wERRdK49zla0wbgQB3fszQrg0CpDXGuJPwQw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: keycloak-credentials
      namespace: yas-preview
