---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: keycloak-credentials
  namespace: yas-preview
spec:
  encryptedData:
    password: AgCWRz+Ff0yJRRDgALbG2+krBi9foH8ykWh5BzMQkQTweFB7snfZ2M6UaTrZpf+LA92NURBxnixlw+Jl+HNOBKsUKOBGauu/Cf61pg8RJAJxzqpzB9kE/pZ8e/rzgwc0t68Bb9LmyekG4KIH7NvVU7mXuIgmA01qh+JWHt0mGhk1sE/gYu6eUSg/SQg4CDx2zd8bkPGryw7BMYVg6V3zB8OUkc5uIT5qn/FKCRzAu+XTNcolzE/hiJSeFcfwSgwbRNuNqPWWDaPKZlPg7dsU3cwdulFrXhP6QsRd/W/b8GavBeyUAexjFEOXj/NtVWybxDHbsN7MrJPblEjnHZRiFyP0zPInwZiFxWJe+5AbRMlRG8cFLylqUjRWJXdV3UBW7OV97uwI/AvLeBYJIWmn2aRvkkkXwbgSRENhuSs4RPAq8/fk+XzVYujH4ZemLswgztnC1rLGLaW3ByIqITO07R9ffLnUsAXfQbmbQzGhRvjIl7bMHq8m6kxgWXYnp+Wasba+mUx2JA5Zq5TuMcXZfjqKRpP+l9/4+6r+4kLyA+f31pZRajg1ex704c5sCi7IfkhS8s9OnVJsyYQJclyfdpu+3ZBHbYR400tC3WOyO9+Ylk9JfDreXV8icYkFN4z2d2pln8thnNQay3vk4eiHvfyKMEPTNdpbYMv2eRWCCJxdCA4HULdmreJSJv4GzXkp4YKbbJQnQw==
    username: AgAMu7xY3AEyuRu4dpw1o/Mj00RNm+fQCzmLSKmanWIPZD++T5RRCJDxA69IOewSYPZ1mdSIw8EdtLCldED94HqgKgyx96blV2LEka0AvVTYorKoy/UMpbz72zOX6XOdp8cH+9ukEytRWUlHOR/yHvt1CjgH3lEg18dMaX7MIHAQ1TX1KHGudijcGhK6YxzfZVlIqnATUePXJAVf0Ss/RQD7Y1j+ym5tLzW2L6sZKMDIMfv+G/zudGh98YFel86l/4UESIjObQsI0tNs3MgcfXK3XrlUSluegG05cQ7FI9cT2hqaFlSppUGUn+08G2BOUaMp1HJXihx6TeGfxHhNXlYtupKm1ezlrVESfc3wON/Kd5VajeqQNGY4yJpQOXpuVwpsqHXW/KxDnpu/B8g6TCPuWCanz0WzgV2hOtgbGpv6H/i1jIphaqu/qlrJaQSo1KdLoQn5AVwFyoT0QFM0M/ca/ZnppplI7RuU96Wu4chcQlUnQnyDZhUhWmuv65ssILyNLjxJAdeMAaDlYDnW5cGNFsBGiRZlMfRi9qnUJ3jPQej2axMViPK0El/J54rI80SBbTzTwYWmvuPCDrTV8MXw9Cw6jofh5aLxsRPXPYmXeOnr3dtMZjTFU0hvHIBM3Hb1wMZ4Wg627/gT8L0ufqp2uLsghXbVkk3jXnpWM1+fCnS/T/fF2pRpgeuDnYYwl1naoRF4TQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: keycloak-credentials
      namespace: yas-preview
