---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: pgadmin-password
  namespace: yas-preview
spec:
  encryptedData:
    pgadmin-password: AgBx6if03rF6TfqnCowf46ZZZAd8mK414JctGQccQ5UyYd0kH7oCZOBoI6rF46ruCbqvLnHdaeLZqCVbNCMyF0/YQWw9NbKK2BbNm9aWZz5Lb+jhqwMbKtzVvLOpuCwVvyLPl7znaVfFp+GFWtscI057B7HfdaEXBHfRDeS7P62G5AsFsANIt/kT3KO1EbIYPmYis6fikGd7hTSh3MTfOKsPuJaAjymhWxGZFZWLczaO36DJ18uMH1AoxpAXV5Ii/kv0CW0w1fcTe7/W/B2f7qSEUzb6wjnDb3gHp3pVvaxuOeM6f7LXf1Pshz5MTvRkaYdDWPMyDydJh8NKR7YtLbsLHY2aSV7UvyesUJ2O+1dpRsGQSJE17xbYAESjklGAolyfQA9Ih9rvpSWRDMu7QxDX65WQaSrg/HuXTTNRylZxpohHmdNbSCAISOeTFTYlw6OwTFV9ks+8VgVVFSD8BYK5X3YK3fn8NT8W9MwOatFcm6qRe8TJ8d+WpNi/CYTU9jvq5XLVH0WORz3sihDmzYUuXJcjjj9XexEKdinoFe1BtkVIEnMzc9SXIhDiDse0GSMuriS8c6mUu48pCT5S9kDxJH0E3QWMhmgwKFvJZ0NUd8+dhnrUW1sCKYXMCSzlU0+numPfoE46ZXv/CsVeDYLu1oii1Y6AtjqFQUiaa8sRggOm2uUMbB/xxOkiMhjqnNS1hOpeBA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: pgadmin-password
      namespace: yas-preview
