---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: pgadmin-password
  namespace: yas-preview
spec:
  encryptedData:
    pgadmin-password: AgAStkGm65iWjlis5wLWdwTqzm8Fii6xfX6hHNs41fvGC5D6/zg1MT5b/kKhQgom7BoesSDltVMvIfXa7HHqn39vBJU/RTS5etnzudQmQHAoPLmqsfjunrWxy544JH7kS/1/lYvkam3K1V0LtZNKPjJFik/2afaaPfeVddJy71ODmWF+QRB8eztnpXUeiXlCsEGHE2xr2RUvnzgVxdlt3P3lkmF/LRWwAQWhfFR9nu04vATInJpViVtRutzCqQEzbHIp11h+lAxh7eLB9cMByZYCCuNjp7kftgF5GJtOkg6/X96srSjxfzZ5eSmF4jtSoZIqk8wDGC/SSIZbtOfop9ZdP+aQso0gzG/hjb+gYCr6CVZ/GHvBlFBKjy9KwX8snUwohcQW76AImD4+UuDeu5FUfhFtifvnE1kv1cWuKruubVpZchm06ZuZXWaOKFaoslpgpvgEC1M059YKfUUQ0H3hruC2XdgRPBJSaB5KSiy4XCHMrkQ3zD7VX8wh7uoFTOGK8Zn+s4IVptuMIxl+jkKMrl8sWWD9SDv5xiZ34GVAZAs9nN1WXvCRsOnxyljbhz3QEW2nyL8PEVjN19ZGVIOIT9a6QK98Ekch5jk4HouPviaPgfwXvxQ9JaNTP0NSbEyx00cUGLR7wLgjOXeiZDmran1cbLf7iCE8/hipP+G4kc59JaRtTDoPWFLVkCyLDebzJLxH8A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: pgadmin-password
      namespace: yas-preview
