---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: pgadmin-password
  namespace: yas-preview
spec:
  encryptedData:
    pgadmin-password: AgCOy1NhE+46E97VkWEC52n3BpBesCsqXhGRQOlDxtoJp3x6RkCKrMfP6JbCt6c06DmPx/PgGjIqn04REnkd0ieLEZ3feU7dIaD4/FkLVHbPyU9MxQCC1ZXu1+v+fPnhHgjszcOBRts1MirncKoUIjq6HrkWkFKFrl7u50BCbJFR+wMCJFrTUWFsu77zjq39BzDUya7J/cbF37NR06Nj1iFu4b4JWn8SCVtGPlNPZX/aVtCjFvRllz4JYECVSz4zkN3VIIogYMuJSo9kHcj9whL1R04g0JU0pGM9ybssCT5O4C5P/4h7U9f+Ls0EyI/smMl+ynegFSE2L+xvx6aTUdQBrJpYQ5D+Zj2nHLDH07p7bMsqbpbQbU1tA2BqvzVZ+7+Bzcoiqxb0Uls3AQVXVqqAN7AtMCGdAahxLfQMNmAY+hVfHF9GMWLG6xdhk6Dn4xMMptP8ZvZw+zpwE2pbTmQgS00VQ0De90UEZCoaNbkQ6Yzu+31Bax96nDKwN37scQgn2JviOj9H4ZhVEg3C9nW8pYXsNL/aXUbIs8VZXveFf//Pf5mkPOfV3OYZ+itpmZeFg5dqRZUZ0bABcbGp7KrsxLS3uBgW8TWBOzw9MZE320xo+3HAl35cMUqXdVDrHcDUbGoR5VWiHTys29zxM9W5Q0UCrZoEydKbhHRzCcteunaaJj7pwxwVUKana06oaOTEmYl/Rw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: pgadmin-password
      namespace: yas-preview
