---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgresql.credentials
  namespace: yas-preview
spec:
  encryptedData:
    password: AgCazcPzyM4v9lK9zvjl8+JGvQv7UWmKa/TdrcenwzOnIUUV5r8Ik1mZtA89s+nmFFPaYdNRMWC9ptbFYco6LTBZVLwz9xOvw0jWsGSGg+jta/D3lEiWmCMVmVaZJECRZdrxmR65w79c/lt79UQ0C2IMCw4nwOWNmoI93WEI95/f/7Bv2Tjz6Pl7xvKkRdwWog57YXzgNXpugVe7y0sdZdFSGUVt/dP/CiyAQQgYgWsfU13tdAgiDX5o+i1d5z2FFLhc0sRiS85szEUovpAkzrbgTom2tBtNxXb3KgqaGszwb4RZ+DBgG8wcEN3uPL2uM+e0gRPi6sZz4zbj4MfuIWbTntzASEsu+6q92yrOw9uIRi7FOHNr/ruawcRDJuARxuDh4lSagP15qT+I+/S7KRqngNw+8OdZXQJesfajBi8kTGElxPvP9vTS/sYNzjeEJgH48CasS6Me4wG0Bp7bcu/sK5Arw70lPNJYaoDWdTuDJWfWvwS7Dn3Pl6Nx6sUOKUAPx7RTng6ZxHCtNQrSart6aL26ZPQljsdI9RFpoltODYvEpOrBvOWZnvQHhn7MtFflfcFmf9ysXGht9pe5b+oeBwbZG4UIYNUaAyycuRAMNyb28yyk70rZnu2NQMXsYSEicQ/lJHjZY68JD3NTag7+esQQDQYKHO3XFnUxn4epMYzNF3eRGFAIdkrs85ksGPFPdABNaw==
    username: AgAyK3XU3o0ZMAUWLAGdaAJ/waV26gD/3XVarlYYjQKpls/im7x2+v5OR6/qRjR5KolNkETzJR1vQ3I+kFlg5Kuhk64ZSP3GzKfDOko4ZHz4wgqswFKSmRd+Ha8ID2G+LrEYJ6vbfsgKyiBjy6us+EK/gPMu5IMnI/M8MwuKws4e0KYUw2lF+P65J8zc15A9Ro0E2/sv1OObt//MYViuFOE8FoqiVOseZWBrz3OIZ4mR6m+iSNELC3Tl73jeCGfWsMjqeTUNoFtVzwFZCJSXdQtek0IyIwbSmxqQ8Hr85DOQSSGcWKEhym0BY9z1qw5tSoMCIM2x0TSqtvGLERT2tKNydE3Q8mLjqyZxVCLN0K2soeDx23vYG2I3uXDYncEUhOscvcdQ7tXl1RmmOlcX7GxDEdK5jp3OgcQaQU5FrU1ZAQSftxQGeXDUNU/I3Hr9Cr5z09AWmCbB9TE6CbbGQIEIp/4v0SYYghD9eMKh6ahxnwRvt+SFAimbY0CbyuNYENpR6blkrq8vh8xRUd/7pYhuSOzPB9YYblP4SCEiM9csvir7DG7DOHWimlygTEkgiwQdZGJ0iju92a2hT0Ra7QcGfbiS7HkE1EeaQARfGSDjtA6nI8IFava5ce19e6w3tjC+UP4RNQxYT3mrFVBEyL6qHJDMl1gQi6ManB+tY0cJJKfAiIK5IDye8T80QXXZl0M+r26yWn7y0ik1caU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgresql.credentials
      namespace: yas-preview
