---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgresql-credentials
  namespace: yas-preview
spec:
  encryptedData:
    password: AgBbaIJxwsFwiG5e2KaxZ2PqhnBq/G+rMicmfvBC263WZhxIJ5vmwbqKZtYmjrYCqbAYUZKtI1k+dqLqpmlPqA/ws786qvD8H+y8vbCrSNPukmB4TVdaSql0rJWn56AvA5gEe+zZE1Vc66BaoqAHGr5i1mjc9osU1dHVFoMm7+qMqLb03luL3EaJEa/z2geqGpNnkMiNxh/26PcpfazJ1Fp38ZHcRaC8wGaQ0FlbwagvzEA5um79canqIU7hokIoUo06DSGvRr27uLt8xsCvYetyPbrNvlWMhugxDxw3LeT4hnR9KJiUWaDHc8O7TrQabmUCZW6A6CGU1Am6onoL1UpcLwlFxYdk0ydg0mKTGA8nWKV/WHjLHqGroDIHDTFDAOjVNxzjmL+9JTDEhBjsrMtrRbscsTCuAUBOfF3GUtq/ca5BnvxTULgaGyVKg3kH/oRfEEYG48MNoI5wVtJ7OX7r7COkMm2946AGdZmu51YAXxMaChOZ56ZL1u18zp8ixipAbVsjzDxAW+h3f82MZ6TO9DJHQnCUTTw5xsdWxUI11GyA8o7n9RPf0NIsKBwOmuak2RI8ueL1CujYAJM49fXAc00+WEFNQCKM9FYGIp988xL+k44A9KklykkaV2/dI1/EIhtmXYSQwvO521FHskOD75CEbr1LIGgttbPbte9VEtqAO+8j7vrcsB6xCf8r8ez0i3pBxQ==
    username: AgBjrOUVH7eGdaSYofH7Co6qXi0dlfu6lSrVj6WR5abvC3gOvlbwylVl7ZceIgyukzSrlXKybEOcd7zcRNaVFuPcxFAn8DqN83U40eGyDQpm3WBfv70fP7+d6JKOYNChI7/7BOH1YfsPacVFEGe3kf8R4Lk9eJz8owerMub/GDCEMCd2/zpdimojTbbN/0FMxcMp8NGSntQbbumHUJvgNz8CSuVtQbm0Mcr6j0rhWIaOzbHv5DAbsqqCfmRM4N5/OcUa9UzgYoCV/LFeUNxfrwOtE4p2P9PKI7yTMuMRrRgToSNy7S6MeUjHwi7Ugh2yX78aZv5wOBPV6xCO4psuCUlZu4SNC3OAqMLOFiCE1qburzH9+wg0WolLNtNn/phPg998fdiuAqCb6ugj1mar86FI4IjojqoL7k/sn4Od/PnKamqDt0szU+yRDwTfUdwSmmMPAWaNgSZ49xIv8IUVAzJfNsjECV0+leUYuMC1Sv57fBoQ5E0SZpUnMrSs7RnbUAvqX1jrt+BvHkC69okoH4E45k//Aw1gBn9AwNdt97/tg1cNvsEt3giVgYRIV4cBop64+jCyNk5Kmj/S7PNoyEvnJDBNCGdeeVfManJFg6BRz1Ux1/kCOzR+LfwEkrHMrvOUZP1IZGCVORKbdRg7EGI8grMqbmU+288ZblceSuHZPG9fC9vtCtHu9/yQSmre+NTm5sCqenODqPqrUQg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgresql-credentials
      namespace: yas-preview
