---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgresql.credentials
  namespace: yas-preview
spec:
  encryptedData:
    password: AgAoxTRVxS3g3Tj2ZliMIiBTeBQcViZ1Va9DPGCVSrtDM9+pjbnugvUG3lmtuIoZ5t03mFR7Z24zBl5l2IxuPBcumV6O/oIe46TVtfRpZJNclcNZUCdyW5T194DuYI0/9V6G+2HcbjG3VYl3lkGfh9X0ygFkdW5PTHzMccLvtoNe9VST8pOG1XhF3vU7V4pn8uOUQo3Lh0AQgpRKpaPibK+plCnKgfh6w4UFF+HZX6cx9E6hG7hioSCNH5jVPHh8PRpQx5FEWlQRgnlY4pFmzsr8EIlVh5ftsHDYKacJYt34gPI6g+FUOc+VAW4hwI8HfC2P2o+vViqcyGpfo81cFujU5oathwbv81smjV38MK0aSvwkB7U2v68J7wFbyLcBELVGufJ/SyBIhHtXDMkPDT2BQ38GT9mA2+myQ5NAUFZsYPQsl0SlsI0jWCqksjgnYB5ylHitqKsFTf00PxY/Dhh1E6YcrzYFKw/GILLb4AEVgbf1OoKfbyqD8CKk9SAKw4CI8AnN8YCXb70FAF1phKZClRS2v4AVeBE1lE2Uy30jsNskXbDbhHAEO+tVyf6b2hMDdWQgbcX3uDNG2ww/z2nutyrPbASdjkcQQrNYG216hwtKvDFbJYPnJc1/h7LWnukcpqdqza3JLGvmFkrRL+kRWRCW7bv8z3RZuJYHMJbgLXB/k54UiOqZmKj/2pdeD8ewJaDxZA==
    username: AgBxXZL1G4/kbEuam5n2pNeiqE/X6576vCp7i7HTjkXlbjKO4cWdICCeQVhuIBp7AYWKSdUmCoPsSTSrFV028k1wqHXfh7/srspWsDi78QObYkyv9I24xH1a3VEQ/9P8RFLKqOaiXxGIygoQibBGTxpnJPEoHfP4RmdtHNk3Z3hZkqcZ6aOyB1vy7ahcf8sjcxqjmuA1Uo/ROt25Q2rq0fC2TJn9a9BFkE3nvUnvAaGR15pJbT1xPAMk6Qu8iQkDqrV+tVV1ed5M/X5RcnSJY9vrckKrJsxKnqsXojKLzqE/j4VLIhFEVPVEwr6z3xV93/mkmhpwVrcSYw1eUOJNkGHAEWtbufGChJ/efvcyn4oaUwJqAPcywLnzXqzDpRe2Bum9FayfJYpgVpldNgoe95QjVKaS2sNi/GKUZueDrCcgCGoHRPe6MiFIme05HiDTE69evCVAOhC03bH23N/9pHQ4IaKiD057CPjOMCxikoSVdBWnApfPpeX1KRIXYqWDP/1+YETn4j0IHS+KK+hpvt2X+IhHinQtgg7uQbBg5lRCyTZkNh1LhGgSoIvUg5u+c558EyCCPA22XYjeyeO++E58VIyQobzsvHR9dq75dOv2V00T9DtmwbN4ntWxNqOA0956wnWjOGngNQzkpxFYPM9WdzqH9qbTIGqhcsV65bX18UzxrrnYliOQU3vZ+Sm87JfizQX1h1I0F+Ib6Ag=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgresql.credentials
      namespace: yas-preview
