---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgresql-credentials
  namespace: yas-preview
spec:
  encryptedData:
    password: AgCVqVzBg68v3zhhcTkamza22Mhsh4D4756lC65V9qdNjRYieHrqLKp27wfVFcuPGctMbvh1CNBjZJb6W23Rx8SbbI+X8J2IJ9cpOdWRo9ysAcTVq4F1fkrxpr3PdA6AGvuYN1Q4y36TEchzbNXIvHfO/XfCVwAK29ATRwDcgObxele5Gva1LHHIkwweWjnkLAWScd6LxO6wZ11bwKKmlQLI8mE+gxgpG/U7vd+8ZIi/OzFjHO4QyGqdpdZ2dzqSdAOhISKr1DNiejRm123VsE9ApVGPVEdXRbdANHVhSG00cC3rBf7NpBaCrT03rnExyVsgq+1t+g51EZv6X+yDPvldoekybVqn6YXuyocI+s0VkRUOJfqos2CFpTE/CmKwt8g1dGg04oeoKMKUGPOIvee2zCdCLBULRavLFb+KVdV6A898eUCUD1DQNKrYdTbCaUt/k6af5UW3j2AZfgzSM9KaONiHBBOvR/mxkLuNR6kW/zPIQzxoHS6p29azN8XcYDmCPP6E2i955vCFfEgUG/pbLs3QaTnaxdysLr76T1JMj4AiNCNOFTDKpL5XDkfiO7Ar8E5Zcx9gxUcAAL6TIY22vLMLf66bOkYYQEQ/Y54uODTxrhSDyu46pPglRAbG9kCemD799EP10NS/1P/891Up0VOOrnp9qPuCbP4tZPD6qY5cdRLr4o0nxud62wHT6bR4PtljTw==
    username: AgBGj93MqlvvcwTd046gbfGwEOtwHKblAZLUpe7v0Xal9YBet+Pxsm5tq5EWAqCHUAbpl6nha0NsF/CE2prOOpnFPzRxzkxF2QPgqJLZNOhvqq9ai/WAoOnQcHfk/DtytENLooriDuSQkh9dCm+O04Ou6QSbS5f59OKeJCkupm1hMjR2ccBIQ0fWmiIJrcRTow/tv3gJLSLT26C64EWVyUor0worJVT0UWQBZO0ZOAp192fZgUgjgflmxMUSag9n80QShwWxL7cW5piEq4R1+f8Rqheqq9MYM9Aqu+2ok13NKMxsfAjIMKkBNNSzrInR/I3gf8B70gvZSvMjQnI8YDIq3UNHeusC6tbVwdlE/VCxeZl0Uv2jueKBDlNuEFTgIFX2uyQ5kloFhbpMQvL+g5hD8r48kucLOs9d05Wd9uLqqhYQmPVLJNyG7l7YzxqSFcZThdE1Mh10qZw0zu7iEeFK0THcPNGpnPV1/ICdBoa89H4RbuQyjycE7NMZHjF9Ufkbg5e/S6+SLes8clH7sd3fdYZK6eQM9GNTbQU5t9kiv0ynmbmPVuxl3HS6+TKAp0Ws0minYzcS3clMUkl9JRXXm/0Qs/UqXFjln76oCupzvmUfUMSp0g9LAZb455x0Zs4oJZ+/DR+Qf7imM8FRtNWmNaureHgYsGSPSZj8rvZNOT82HoLaVWgQV0suYaiDKno2H9mNFWi/yprmkOU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgresql-credentials
      namespace: yas-preview
