---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgresql-credentials
  namespace: yas-preview
spec:
  encryptedData:
    password: AgBsiEv8VD/4/2gJWK5YFYLE36WjD8cH0OvLmGNRgOxP8nT45Kxe2h+yn5DVjbK7niQi8a9UiYFGy6isGniM/bwEYFujif6z1vTIGa0488aqVfwDP//rlY2smENYfU+rRlQFmSEvuArH7VilIlMLISwL9THPep+oyr0gMMvgNVDhryrBJ/PvRRZMYJENWX0Y9cKubaokad1FuiQ3fou7kzT/eZ54BYbjN/9mDFSN8m1L9WWHWnBaEZ8FLYXl24qv9S3XbxWXhTnnHP/DopRMd0SWHTlzrW+ZQMyojOJN5sZPFmnXUWWfAr7hRXRUp2YpCBx7oxylE/WDEfFkzWJ/JxiQeHejk80rVPpLPALcnh7/cP2nys0cqsPRQ2V/e7zHOrGDdABWYU0RwqFYo+y6nq1cfK+GmHr1gW19vqtmAqqut4WRya1BdTuP+H3RqpMFL6NmY7KgiZFzoNzCZlWY/eADsrf0DMAnOtsGi87YZdGsqT7ekNN78l2KGsvRh2zO3tXKkWeXcZZqCNMQvd5cYHXEVOEyHWFErRp5yySZWqlkobGfkczHTpRyZfZUpmWvoF2BzFwQRBYQwVhHhRTxbXfwp8N6fZAB+Jey/Azl0WKdNGauvB9foPx/W0Cn6Q78+vHQlfKAi4GMrrHL4z/5ms//pmomkM++oEqiQzNLGL3U19M+j4cvqYopkXNJVnh5WV0MCQGcWg==
    username: AgBU8LCSTy0N2ixGeTViYwgngdask+3QGnHgibz7Rs3tKDBjtwKuogJK18DlxBUAAMD0kuQ/JQctY7GUAW2+vM0x5utyMKzxiXmi7lh12B72eJWW2EUQVHNA7KBM6DZIO3d6qFgLUoc3m2hCWiskbe8J9dORqyC3ful2MtjKH8SKEVh/u7lHiouL4M227PYFJ2LG8GD4+zVFIiYG5g3hALncywIUMpBjgkq/DcWNfPF7nY2Mvw0UNoEXOd3cx9VCkZCah+165a2FKfW7vkpitpRBwLU7+lxcQ/ODD2tO7Kttve1bXPCe/UGHSlidQkEQvru1nTufQNHTnPiBWqHqRWXUW9N2XHVZuPdfDMEOKaQB/kBz76DE6Nk8WHKxMOhQ7mpYZzUg3UBm1TjMIplOhbGeNQxgJmtWTn90oswBnhB9OK1QMBWqX8BVLZ5JxLTJHSvGYUdEJUxLtUxlLxLDo+LKuXjKOjWS125HKR1jQY9tSltzjuzjmzLyCCWxptOCCq5MbFlChr/HvSH76nX7Ec9TvaUVtjNE1JOYCpp1h8q61sXqg2eK2WLOKMP0IeUOpbh+jsu6k3M7bARnTddl7cAFUm31q7Cwzoi/JwIn8efJnfdk4MO9SZFr0tFRlep2DsP0E4/0eTNAO8X0ViIjq2mB73Qa0wyTHOpkGpqL6DW7s6TFeh+5xcxy50Mj4IVcVNsx4X+9NGlIOV13Xxg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgresql-credentials
      namespace: yas-preview
