---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgresql.credentials
  namespace: yas-preview
spec:
  encryptedData:
    password: AgBMivsOcZLKQ0kcoSy1TmqazxX9WWcOP5WGgqrhR1xwgY85lIuXf3rxEYSB62zjS3afxJu1Racb7YN5ywyExvXPcLiNccwLO5ZsDKzaRgWgc9UbBaTmzWlNxe7+zOIXQOo0IYgJXgm3sbb6ZQrxMd6x43Hy8uANIbmEsOpDGHVNoc9+U9nGYSfo49++KBwSIkgnSKd/b3YG+FAvt1MG15wxbzcsQz0wLiOZg2AaFen9xjUUQ/6t0+n0pxlAkaPC+zuZJivCegcj8J0cSGnW745LV4SA381mdz7f14J52aSvgdbUL3MKbIY7W0QT3rOr2UFumf/T/E7EkIpZx0lUyeodpqdoej6HTy5USh7c38+Qq7x6IKCSg7rhLcZIJjauNaDGgKwi4PGy4kWvpDJrbtT9N9jcwBz9cyYaVNtl5zZu7/A72+US3SBC9/ReI12yDlYcYvtyX88BCoe4IScWx9cOHjiLFhlXGT1TqfFKKLwn6auoAIz/Y0lTuDzHahZ4t64gAiMO2BuSUu+efC/TuJGTuc+DrPC4CzfIgSrS04n6j36lNZZJg5k/5PfSR1sKvpFiYWI+dwijHJ5XkiV0Ta4dw1+0xhHXBYVqJQF9z19oigw8lOA12lyUwWNAbvljBXKkCTH9eGTOpk1HbywRJ9xEyHNumlLA0UNkWmkFDwMzhlTGpAwCDK0Xs1xh19qCT27Vz12pcg==
    username: AgACcM37ruJEOMbfmoqEQuPTKuPBoP/IxVZtaT6zYJnTIHCLdX4kzqxJ9ZvC7jhK+KdBKERDW/OWrmg0yrmcUb7BWbk/ztCfFvov8SLa8fNmmvd80rvPHmfQOgsl2eQwOK7jXY0po6AUBVFZivv+q9147LqbgIOFdET3NNU6Xwtapgs0p3xLUlovGzlU8HuIZEHIHtPRmY9KjGp2E5eNZSLD/Pm3xS82fcfScIaVdYFSxb+HMEPnD8drn05V2LEq+ceBQLOekyziLxev8UgK2WlTvx1kT4AIFsWMKNHUE4r7A8GVhn3ZClP4TgZBAeNZDFvCoSAtn8mdE+TmWN6c0E+fRTsvXP7qeRrIK8wsG08JqMR5oTuyp8b8eAVDfjscBKzsd7RfneHYWbMIzp2X1/1t8Sa0PUsAwvDufMl0hg7+sQhvuEBE7OgacM2nOqXJaoPJBK537S/97soUzlZ3vkYkz9/FBtgWnCzmv3+JV6Hnocumx42OMjemVyV8OE8R/ASWfSZH0TGOFzbwc/OUIGaMFF5VSj4XbBILVdVslqxZC0MjOu+uqAQT+jklDe4G/rI+BuPlMY+0493ksCO2FrU2AJiHUWemyHz6XHofKjKjeP7LewVgjV8heXECFg1rMAx7p+mmm0WJqTXGNLaw7O/+npSemgZxEur7SWWu/S+nRti283CfL3Dj+zABghvaUl3stra81iKLVuqI0NY=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgresql.credentials
      namespace: yas-preview
