---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: yas-openai-api-key-secret
  namespace: yas-preview
spec:
  encryptedData:
    OPENAI_API_KEY: AgCUeNx3Fhznbq+pXf0JmVlXO7wiGDeKl/vtqGGDwGFhroAM7kk/laF7JvI7RU3MTnFpGmm3LU7lNleWdv5t5RY/5Vvt3YxXld3r+1VZ4cter5O3+JEk6AZAJrWPZhzkhQ5yfHSZKaY/jUVGmaYfbL/jGIWtqJmPxP4qSvwGiDEsbkAx9V4q+zDedAu4Mi/8i8JEXx3YVC0wZtB0vDeX9wUaraf9aYaiWc7jSSNQ5GOoFkbNFBti3XvCx50kev/NfGTvpPgqZTHv2cwWcmxGhxzKCjHToe8aiik5q4GJPiVNZVNj3YgPZvFS975LxMRcdASvFKKNibnCwx2w4wGVTp6gkUzKEdz/D7OWgEkHOv9AF8LT2u1tTsBw++40fbRNNXL/YcaHnP7HlxjmjlJKX8P0gFSB/d78LLuxnfx6TeZhTRU4hmFUqeQHGaDaSHsUx+Wo9YX+R1ZWDKyqU+Yu0MI5CDaPpsdjiMj/Q+yq0YSWRMfQggrFMeWAQFoPEjKxB78XP7qB01ktjALyF1WCPsYBCTn16/oQncJVk+htiLRG1bUFckwfnmbWfutDypiV8k9IK3doopjUCTsVZLI63uNFgfw5g/srqI6CEHKGueNXwG2jAJrXM+uTLsWHLZahd5+kJS/hOjui1QaNhFkBdvaFIs/AaJYfYCakWRtz3/IX8hLhxE3d37oDqriJu1zKalhQCnk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: yas-openai-api-key-secret
      namespace: yas-preview
