---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: yas-elasticsearch-credentials-secret
  namespace: yas-preview
spec:
  encryptedData:
    ELASTICSEARCH_PASSWORD: AgBHS3oTBdDLwMQumFO/d9AvYs1OkXcpDs+fLdZZqwWzhlIv+k5Fgb+9RUX4YpgpHHxLyddqXvh9IAxRqt/llL5vtcUJT0bziyZ2C/r8/jG3p54aKmL1+C2LSGtYE2P3wriqj7vpxa4aKDwOv3viLTpzBjDpnuo6d8divNElx4j/qRiDxrlu/CAuceLbo1mIQxYKzv+2AqSjXoTovlj5ccqW/NjL8TVl8cMH/vvxa7DdRbpr2EgEX3RRPfbD2qCQNavV233Ov/GXIwcFi/EaoNfNLOqJw0onz2oQXeebZx9h0Mx+/B59ssqOFhhQwOxLcHGlzqFfNxJBavSb/yAADrF+3AaW33ghJKvaUsdBjMQNdAqM7EsqjOi/YafEivzm4UI6DFuNNn+wtzugD7ixqbIs02XFmJIiwsVVcF1ednkPCWHHGmIKWHPK2M1v75AFoIHGq6VVWQclWdZehxU1N651uNkO+o//cghnd3wzvJFM3tkWpbmfWKptFMZ07Z/CdD0f3VIZpySTstYhinonhaRwTQ57uC4Lvw1Y92Dt7gvGDEhx0ydz6tKI5p9SKNV0GkvtgRC2rp1MzDgVEhj63Dv/DWalCP7fGlJK/iYsE9pLP5rM9MatY3FIm01AUKf/qIbGOyTb8EWjzfhzRCYam4xZ3X32fnXc7PMUTE9aWIKDM0d+91Bo+I2ET5YZDoWjSpvqv/DWBYr+4yeO3QRkdYtj2rjflQ==
    ELASTICSEARCH_USERNAME: AgApZN6fUNDeFVd7FDnNpsEby90S16MPrEGKfNBSS/paYYXrmg86Z/7xXch2/31wpapIKXZx2rNGcmK4MgNUuf1a/jcRRNu5iT22CxyoeLOF+K861GmwhYrbdvqgb9KdYfd2PbSS6vN9c2AI6GJHfgTaRjd1dR+37jZoHqap6YAgUa/YfQNeA2S9ckt5CQnCoFVloSzpsxiLFgywoO5qGG7XzGW1htUG33HGTEy6TRLzyOGExahSLrJU7xvLouQwqz/Z3vSIDHIjRWNikzSZO6aI/u1Yosow4U5b7UzBmVXUXqSredJCyTzYlv6ld7gbjfe3wSCj0SPBrmJXgNgq/nGzpwhvWaH1jGSr5bN2jvqmqvpNX777roeu9aaW/du/E0mmttU4AcnUs4w2Qtvb5Xm93y6BL+9eLHZG/2LSKhdeHoAk8Fw7yV3lxoNUTR7f9QQ0B6UlST/md6b5AVOyczVoxCqp6eB6yCnBmHvBizHC5u5UNRNl3DitVcC0KxIRsTNMqBEirXpyI185/+YxNuv0V3p05nKjLc1wyt+CQVyJGpQs8Kgm+DXP38r23tByPciuIlS18xSBovXIVpBeaM55oL/HjRv9giIyNMiKIFma++EnssnIxzC+JjpwrWDTpYKYGg7ZISed1/Ezu6JIuBVzm3fsJ3V+HyOZ+XwiyNOHofNQXr8meDIQtTgsSNw84t3nsEo=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: yas-elasticsearch-credentials-secret
      namespace: yas-preview
