---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: yas-redis-credentials-secret
  namespace: yas-preview
spec:
  encryptedData:
    REDIS_PASSWORD: AgCPg2aPDGZ6+jmgvGtLRVHITEoxVyRVVtKA/bDMcdE8/+hoA91kaaVLIw3iVDQjM+UDb5m/hfx0oDJPyF7mxUxlo+xAPxz/KvThcwN/Bs9OQavkcuWsTPyQUUFD5lm2u3KMwPc0TCgvRom0CEOd4MOF3VSSDgtd44P9K5AbJKtZw13Ose7SEIEmVFdLAi6bsonBo2y5DwA3CHH8gX3OVp8+wkiQQPja8ivJVgVenkKYE8YCKVKIYmiNxxwIAc0EA9SEIZe5r1ZyB/+4mofn/mBhdyr14cmXuqQ544Rrct9xvxJCzfStvnb9Jo6IXhHsDQAKqZGLFU5BWx03d9V51bFmHry5/ekV7BmeCA7Hf0y2I5pO+1aBeO+S0pJEu7lODu3nQXuLiGNGRoOLt9QyNk/MMWYfbHGeO0IGkS+1C5hRMB8APayAu310sCvRoEaZ1PWPAT4S9gBIzgjievw6K9GrXwZlVXHMUgf2l5JvI2G/f3t6TrjquxkPd1GAh2JbSPC9YJEs79w0sPmXSvFXZBPoUtbxKhf9V/RvpiOsrVtmtWsn3m1NRrojJik/HFGTfQstyQt3spYzLUr/HhwvV3Y2TaP3Xv1YeXX3ajJz3hpxAUZJbCmOj4nS1+0uegbEBiWuJPcXnFdBRhfu9NlUdnvE0VQdSBgLfoi1Ck/urXtWwiRd1Gl142noXCkfPY0TKfUSS5EAfw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: yas-redis-credentials-secret
      namespace: yas-preview
