---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: yas-redis-credentials-secret
  namespace: yas-preview
spec:
  encryptedData:
    REDIS_PASSWORD: AgBv85KDVKp7D8RsbGP3KYNM4w+Gw3JQlwiiyCjyhqTjCCgBNT6PlDP1WAMFae6kHUhzqLxQPa34CcViTcpdysm6POmr69xlzAvNuZftwN1wswyiqV0krEop40fVEYlZhC542eciHv2jLKOE7VBFpWQojOs1+BYz7ZzhcRtSjwNj4goArrkj9QXtpM68T1/tXbb31nl22m+Ei4sGnRuAaSOH4xPggTHftvX7EBooQkvBh7RP6p3aIxrUEvgr64wMOjje7H0HygyDSFgW4zbFk2HTltESyqx5YRKFd7Qhnfs9ZyL30yVJ95dOjc+AF0KhoTUpRETtnW5YMrZ6fOoe1AKnHncHciRv8EUqgJHdgnUo+E9uGyIDk4aT1PJQ8Zcfx/afgR0oEmU9Bx4Jw7t0uvE39LWA8Z2uveBYnO6w8hNkIyEVUW4QenqafNdLZoiipDF3YuCfuyUD82QG5Vm5p00QQ817k0XvkmzgXHpsAyV/nHNjed+rWiMJIPa1gJu30jGd8mxIuwToVbnl5OG51Y37SOysgxmpZLoJc+i15OX79+Lo39YVTenSt2we4FmNBEdjIGN0/efRAI5V8w25vk/x3Gee4aeHycyRQ3AA/4DFuWyocYc7VQDxJX6DJHfi1idtt2v5LDUzbZCvwU38KIOOTYwJpujp4xXoKDChXrJ2YcVfu3cCG725k6hddwwjUWS3u9xhIQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: yas-redis-credentials-secret
      namespace: yas-preview
