---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: yas-redis-credentials-secret
  namespace: yas-preview
spec:
  encryptedData:
    REDIS_PASSWORD: AgAO5sTU4cx1w1+uPtPwHTSyvqVtlm2R7zohazV7yfxajWM0SyOIUqzAeMF8UU9+DiKK/KmYBUFgujhwdAygiJyxqWR2AiW9f1m6kD6Q018A/f7mXG43fTNSYIwVXMYcIbhpQh5jU2YgGLCLL3v1q440m/ijYpok9TYRBkTC3rQ7I82bZK8p7aaqNRBFh+9S4M7DRJlzjamel3xJEA+Uj61jLwSoCtkxyjaHaxfoKsIWlO9ilTaubL/dxK4CQhHDL0sZiukMRb5rO2gW0VuJN/F1uXE4gh9yh9EDjGPTQAJo/2gNHt4/9AXpCGkzFzA3aoaF5wKTuy78QEBec26JZrX0duYqWz++BEaQufxwYgeT31OPOT3axAb2OHZrD31C+npe1EttzCNqB3KKi0XTr/rmm3fDBDHOizmemce78xgNv+EyHleNzhk8eAkLss13fbXU0lhg4VUKwttqq+K/SfZN8TF6gLKlRCEw++PUIK9wYtWGFZ2mRzJVmh6EndgACrHUSI5xCE0kSaooQb0FEgZhOJUnFLMkZEGBH3RuzZSqKXHVCUntKkAsZQ7WOc3JzjrMQd60nM5mx1QSGnlyP+jGndMZT3/4O/8ZLO5PgH/kCkXZVh5q3RkSFS4rZfT0UB/6aw8LR99uHZS6Eunyfd342+JLYtCNdFQhyjJipCF52WgUJU7ysnOgqW4YNZ33Qze7KDx8uA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: yas-redis-credentials-secret
      namespace: yas-preview
