---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: yas-elasticsearch-credentials-secret
  namespace: yas-preview
spec:
  encryptedData:
    ELASTICSEARCH_PASSWORD: AgAL6RUL4IbbTPJJBCZZy0oxIB+BHizBfv+Z7f4WzuoucI9/uU/t76Mvv57+YTNTnWzi4ZQh0l3yEPJNZ9Ok8eh91e2MazAU/MBjAg5J1VHaeR4IeuWGNQIqpmaONp6fSD4gj9fCRk52GN2Qijseozgr6dD8YrB9EvgNTUdLxxBzpc0ADWHOXwBNmPpHDxtT7azV2fSfr3enmISgnpRpSBsuwCL4JarGilgzYKuLEyKOq22s26+Ezif5b3YDUE2cOAuQR2nN/xAoFV3Wej4f83EDPt04iKDok2H9QG814Cv1VCTKCC/x8/Mh0kDbjirwov9+/rEIochmSPx/2hw4JSBa6ojDLFHpryYvFYhdeIdEvCb/xB6CNbo8LbnGKjUgILBZM5NE8EviPphArO05WiygF24fiUdypJ9vfI3+HfPtRkVODiS9LYTx57wuP4eJzvAQrpScuFHUyw2W/OCjLm4pyF+ookZaqeW0oL2zj79E74k5IHxmVDtcz3KWzznxQLY7ZZ9yhqrRiOgUP5gSk3ycGgQN0ZwOn2yY8b42Wj2/My1NiigxNf1SDPAHt8SM1sUwFZsd0WetmY4UeGYiGdZNCN62H6KiqjDD6szfrQZQtlnsGVx1Vfm9B5Qmp5u8u1TCPJlqB/54vI8qWnf4SnXdJsm9NJPK4aAUOcFaMrE9OSlYi+BImOuWDHD/g087cBV4d9tTaXLy7JBNiYKpQJE0SeO0Kg==
    ELASTICSEARCH_USERNAME: AgCXN9z1fzuj1ohlwJhorhFD2s6Oykv9HhDGy34NWt3Cae3BItKpFycea2Q44FPclbhxEfi+cq1D5HArgVjcreODeLlwHAI0S7SG9w/Axjb/hfaNdZpFa1+9gB59VR1QebfHntZEpNJ7KESsqYRSCWu5iYydqGIONufnc33nBNs2XkR6/cj8WGBlEXlBa63n02sQmTOqsbJZF677KGY84d0XMWMXxwrHxsl5QYdOtxqwekXTjMw9tmp5yF2zcWYYyuDuzAN840cG6RFkOulYttgIr2ZVmMPcw02jrKw0evHIkBqMIgyU8PBFpSKxryZk45AO9X0p6dy6B/qcup+ha0sCInShD9DsKaKqm/DklLChws8HgG447AHaWnVYHwNq4C9+fOkve0IBNjGCRtzReAq1CYWEs5epfuj45BN3cZl69MvS76JvRQvT+vm5gSU/wQh2YsR/lMBzjt39NJkdrjdfOBTBW8eXuGzDPEE3EB5oaM6Yn4hVI+cfEyU3bJFP/fM3r3xkOxASVcGmZiybdCZW0CAdGEyAuPmhqFSswi0gGww01LikcxULtEMzcLsduYzwqHnXJHcPSt8AeLKChHVGmFjDH1sb2yk1RluEOzVU5ctBlXnEhQ3Hm3j/R+Yfw5LvayK/nN5hQ7cDM0MC6uL521d3pxfpc/4IazVyKE2gj/n4Xr0H1MdjyAsFfsqx5mcA9uM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: yas-elasticsearch-credentials-secret
      namespace: yas-preview
