---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: yas-postgresql-credentials-secret
  namespace: yas-preview
spec:
  encryptedData:
    POSTGRESQL_PASSWORD: AgAWJYYB6Dd+/XiwhvpAY/RcsvcdDno6jVcAfqzoUzqvTUnYnz/UCLviuy3BvROPGraG0tR8v3oOBPTBlhlKp6XEkln7oOuylpFU59mYm+1bOoPI2pN6h4ScVRzdHjsq/EHk5c+Oo8Cp/uCdHnUojRFxBiFSRaD4/FI/BHNq3cMfew/te2yy4ZT+rK4j3/miEEfaQrEz7HhGHbrqmCYKYkffM9hExOWuGPSPoVCd68JI+aOhUTOTav1vDFRk7Gpe2g6qW9mBfKHg2XKhe2w8t/GPic2kWCjgZU0QImkImCIGIWIPMX2OjkVOX38I+QNddYttHcd0rqMvXb9etUw+xkrqaVbJFT+21/FxDJYZ2mvurnirMZknGAzYgud0mZhNLs0fVKrrBRvpZyvtS5txVwJpkYxWlXbeAQre3G7cGnwefVh3l7AsPlyLLGA1Wb4toN8DgSuBQv1zj8RPajxi4au/KkNZlo6LCGu1er5IVDGhYxNcyfGEhVQPJlYerQkkpdBGy6K1/mLhzWCDSFE3PQXAZTbgMhnhhP66Sx4HE+wqA+8XSmVP5NyWFr2uVl/xQA/g6qOcGRuKeXxztUQ8e6M4q9RilUxP0Gwa71JpGWYxItRyuCh0bY3xSwLuss0s6XNO+97EyOaxQ2mDiKvOhxJIkb94693IqbhAGUmi6bTNzrPiLWX2U4msKsqkJSBpwtR4y5nu4Q==
    POSTGRESQL_USERNAME: AgCKYaukOQkia0nRjxfVAm5f2RsuerP/1OBlyZH2Lx8c7NnIfDejeBMbpCECA4ZxenQpkTFg85i+EWzp558pkIIK7guO/mgv7GSgMAk61YoqATIx0sQQ16wzVTgZHLbfDmWcCB0FcvK8570YHukOQqgVvbLSBR0+0sY8139htd1WfVQ1vJkHQ9kAuy3rgMAkRaKDlkaJD7QzRJW81PGPiwH3eWB84oyKCLWgARSX4De2sHNDGB/6N6wpmITyxpbl7L3wYC4xhdEvGpIfVyOPhAjMJnaZaBIzqtUWv4S+fe4jSBt9UcbDlI1oFgiFNJ0SZAgQPP6nofY4bKvzbKoqFqxePMGR2gFa308Hbw3whlEPXiGIQcF8md1IZWOyDC5qoqYqH6KvMzq7OAAMMiPdGf10WJpvl1cKr4+bqVpKc0X3GUmHMBM6m3Mnsig9ew/YCI2eOgP7zWM9pllcp4nvAg0Pdw+7aZlmtRMtwUzeJMlZx7Lz0rUKnnRX/aGuFPcYKGUEO1AGzuFsSKU36WOMUZj09FfeAd8ycnkozs+Ulj1shVE/Dgrz1yrpUAaf8GclP/gv93H0dm1QwvBsg7z0N6eufuWgjOK39dgyFxwVAW6PvtB5QOZ/UrPVZd6PzzI2LKQgtMh9yergouOwqb+omqIFyUVai1uzlyWKUSckV9Uwq/KwY4vazEvMB1Kg06CzRkLlFWHVRO739ay4ewU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: yas-postgresql-credentials-secret
      namespace: yas-preview
