---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: yas-postgresql-credentials-secret
  namespace: yas-preview
spec:
  encryptedData:
    POSTGRESQL_PASSWORD: AgBMXh/+mgXKUiMVVPdB7Na7rgpCii6mutrfGVH+PPgm5AIcxDBtE2rICIEWKs7Rt6McWekrPvjFSGEXerkfu2KCrBDkTs99PeYFNiTg2VlQ2uGCVoU8gMudLiLaZmxbyFPIJeCGdvUdcNQ4tnuG5DcJv56pBPs94SuIqto4Ko9CXGScUV3iziTMIbKtcSQ4wYuPWLvxHRg7UTWLrren4QeUcUignv6KzTqIPZzHmbSCuZGLj06zdGFyW74uxFI6JJCsJbO2nxIl65QGGZz1K9QnasYHKFe549oTuEgU1WFX22V+HFSJrUbtJO8HMuQnLe8GaspRnz4lAc1c8bw+jVDlogEWI+uV6atjYeIInrZ+aUPNs96R+l5BWYHoLIKzvrJ36kf+cZz+ZVlW5O8o/IcepznG+ZeZAMGneJuFlhVjvffsmvvTbLJXKG+eXAeH/0gazjmpi7HK56QzdJgyayH3dONIIqC/0GCe/oa0Mo6xVjIr4Vn78sgFkSBI6YuxbZcqZDXrG02oajUyJ2K6/pA+wyFjZAvceLmkrY3t0LqxP81WPL7latuxFRcn8yI3wIoAw1Ld2Vni7txQbqH/jvS8p89yjamUEoLQA85ZIO85DhQgORVoptOPz4hBnajctr+GkWuv86g3kqWwu9k/ZwEQTeeZ1U8a/HYdaNHLaXenjy1eRo3DhJDe+koZ9/WKX0sClLNPXA==
    POSTGRESQL_USERNAME: AgBW0I/Ad81QDTJnm/7e20Y0DK+QiweCL7v/7C79D6VwSAwJ5RhGQePB6gtn5d/yoiMvkvUHmFq1FgKoaAR3Ir33k6EC8oLHmhO41b3JoMyuCFhgFKaj5aOTPUpQe/RVRulxJB99sUmCGscvzQvYWHJBZze5W37Caa9Lw8QFXlMJ3XkDzOd6UoR3IX0eyKuK/x+TJ+A1v9QvhBhocikXWaXz8ivnVEAij/i53DPBiaIlNCHIP5m7HfN0+zYtxqu9gXpsum+xXlebL7CzrKZ5OSEwTvhwiro7OjTkqNt1i8R9JLQ9SwnbYDjUpDXZ/aYzLI97DSvqwQRh/7iQEhgS/MHrkmr7aL8s/fov8He6yvMFJUaDin9Olo051UTPP5XhQ8EJ6d5SbRFEUSlvjYjQp6hFaRQvC7Bi4CmtdXOEFdDv/V6HHq2EDzMGcOhxmLTznMnRQW/58tLblsZq7CSNrRfRedoCm1XSKunQgnlAR4SUkqImkkfmlNA4TaTmBwrfxuqsu/UTvzS11a+A8rfpMaYOqlHiIZtdihoFQeymd49kyEoengJL0/rsZTV4VIGP0EQq5gQ1YzSsi5GkeWmkZeKFxKuTP1adgo2F9jfB/NSi1jq4kfPsVa7FP7RLmAhz4bSU07wOSi9hP9/nvIhPwAPtehGz3Ml3FOQPttWz3NSUs2p3JcKFrn0z/ElsJT4D3ERhppUar6sny5ClICc=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: yas-postgresql-credentials-secret
      namespace: yas-preview
