---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: yas-elasticsearch-credentials-secret
  namespace: yas-preview
spec:
  encryptedData:
    ELASTICSEARCH_PASSWORD: AgAR7wtk34p9sM03cVGGc9XHuQGt63zKx2NDQmapUiIVIAM7vZs+SEH+vp9wGjr479Qy94Ab5PfZtufxNgOBReD6P5jCRkRDzIW8WNd1+p7pE4CrR3W4RBy6mggrBd8rgQ102z/CIPMfLeThr/X/DqvmNlGoPWoBDCivrkdiSCVEc2EaEdFylZdjAnhpd8ywOXK3ddVp+OMkOdUveGTH7EorjA7hV6p7zzIJH9VaSOduqXLfn/FA/ySntVXBE+BQDe+9HrKuDK3xXtg9pQQAC1BuQmPwg39AqUZlYmFV33J5rnPbToP7SLlao+mCqN5vviEVHXNZezksOmaiLkoL4t3lPTgAEiT9ZQcoe3zJ4ePZfBGMFtCXg19ZBJfRF4YMsqeZ7Zc11YwvgegoAl3VAJpgcXn7powyZMo/zR9Aj7WB8pV8PAqE3BDC3F7/l0x1nkqRU7iTU0xWv2ogdZHkPgitiDGf9B9ZjBtrGCHKZeBFoniOR6AWp+dzcjSt03NGWHWh0mnxmOdEGOJdXYXKzXWfhZtq+C3wdcwpUjRBUVcAcgyUHUJW0eQSUV4nxN1h3cjHCO+kJkLAgTf6kwm4r1kIj0PtVOJOn66728jAekNT4wKloAAeIpgVFtsrX5t4sToMQzZMASPBw1cgjFnGwyN82fK6ui02clK+nnX3i2YFVcpPifNUq3wMODvkBY9IERkc5pWEYy7zlZLIrpERr+Hee+JA0w==
    ELASTICSEARCH_USERNAME: AgBfidnBVevR1vRCthD1sMMsPZ66/y/V8Hm6Nm3htPWuBhvMw5zb4/xvYoLRp0bQ88899qbQbAh9tRCaiGiMbknaOB53wY0vLWuhaeFqI8UdaXLKqu8y1/Ja0F3U01HnOxCnrr1ocOVvZKstoLzuiBzZ6XyWV2Dx2Q0YsuF3jpIjWgb2t1b+2IuIHyScwrtmQ9J0s8nlUJvT/iN1lzVM+6tq2AQXS2JouHJRG4RIDmwEQ9VYLbtN4hvnhR+vz/GVME6X8WnuMgA1i5ZteDcOu/+cAp8DK1FwBeeo1Q4cDWXRYOVVFif8bQQuFoevvH0xAT6vqXJISuKrATkUKMQ1laXUaBuKRr4ORDKkKR63iy2gAeNG1QF5ec/ht5vR0Jnu4CWnF1ExQyPSzpscWiNdLZWEJcoWcJ0c7Q4CoxoE3IKj4644LfaM69bBuUr7oDZ/HgbhHEupP8KmblRyO+yFnpA5GUCmyfYSBD8feNCkFdWnVpBzSbEVsJqMvt4n/CN292a/De4utJyZimVtCc92or0zUXZLpYoIOobr1xrHxYb0wf4xluIE2a3pJY5EATfsBsbSCyP7fvcrCxOU/+J/d0+PhZrDxwKp2vHXQVC34leDPJ+9ICsPNRtRxemZ3yBbB/fKBLerjuiyi1NuJDo0u1DBgjHS3uwwfEGQVGAscMCIqC6MAMArcAOBO6uWZw8tQWHRXfk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: yas-elasticsearch-credentials-secret
      namespace: yas-preview
