---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: yas-postgresql-credentials-secret
  namespace: yas-preview
spec:
  encryptedData:
    POSTGRESQL_PASSWORD: AgAAF8LIn8Wxce5ZUYi50V3s0+oTSU/Os84dlWM9UZCw/tuoCbKj5kpIXbT4GE1EoztIqXmDO+KMZN8zb7bPnEd+jrNoNko9xZ+o/pudiLz53KkDSFORMfQnjakZPp/vyrh8SgSYcqWjQh/acBMve+2ASiTRyGsLPRtB3NAateDDks0c+wBNfX+tDQPCTZ1ukWYZuFNkQcEklhVtHdwBD6aeyN2bFu2ZgsXiVTZxbWzSDvr1TOYaWTtLWXfVxKL7MW7ML+hmhdlCNLdtEXLchto6Y2sBaSD6M98S/IWU5Dcbi0fy8bqKNcW8Ty7LMLWLHUXD73uGr5bcLXCU1Ockq+z3MYXZYRu8yBY05Ek/DN+VIEcX9c8gHXeAr0zgKgd7RqcXgtEAUTLsErLJnhElMnXBcjPUQM4HJTzK5P9XdZWOBzVk1TEsi5kCgt1TTaoiwQlPuREVQHCMud5GMeexNieEMEMBni5VYUTqQgLF7GIWZ/KKcwsWjZFCn39FoaoIhGNR360Ti0vKTIulNnCwDB8A5z2sruLYOS8bQabUOD8+L3SIE+qKXz0kn6TPWk/aWqQt2VyksfAPd3p0adnFWygokZIwDn08XdUDnzI8PItlooVpx/rS9VDznf4rTkY4nHpNs/NqLtTlT21LiNIP/O6K9L8AGeqmjZ+Y3NSa41LW+T5FWjHG4UVb+dNHCRmpMY3thxNHlQ==
    POSTGRESQL_USERNAME: AgAL2U4JJN4C3Zv4LfZEUoW0fcYL+cRpN/W/uoYSFic8VYYWN/o0BGWoS6jHgSt14iljloY25YVoIN3Lp0xA7Sr7ii60nISQGlHAsxD87YACU2sPuKClXgkr2MG1Uqts1XhBKJzU5JtvKfy/Z8xbGt+ArvxaJBjpa5TlSVri7pu+UJ3u90/JliJlzlbwdEVIhqbJxz2ttnQ3Uf01hFifDlFeleIyFdG4iIzdRRh/PfASFUPN7iA6Nnt2WPA8exfQoYbvSNj0yjDu8IAplt+1aXHfwrcEbqZ+GavUwKnF7OG5YgeqJZM6V6YofdmJ47Y+ly0spO5TaM0ofl1T9PoGNzcmRDyLq8anb1PXkMSMAbei0poW/tYQgT7C1BdEsT8D5cD818gv0sFWhvaA6CT8fwRdjdVCfpm3jeU6VeA0exqjmPVCpj1bLirkFxsks6rm/wyP9Sr44TEHr2DaQhvwOP+o395BtvZmWI4kv4DGZel8kRad2nv6ZlBzkU5fKBE//YFBT9RkGqV/apzZpWQHPnVDLJZNZq5pbhvC1ZITssfCPaUVZ4GIORC4Jup7hw9gK23FAYvJIvMZDn6R5uPvopHZkaR46MDDZV0ZvXKjaYeuqkCFdSGykVrmxyrATsAMtBgEHh/sEqBPqjtUh9Z+Hb97THlqas77SsSWORMLwwjFE+Hek1lWc1t1SYCnLam2sQo30qen9OqinlE6fzo=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: yas-postgresql-credentials-secret
      namespace: yas-preview
