---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: yas-openai-api-key-secret
  namespace: yas-preview
spec:
  encryptedData:
    OPENAI_API_KEY: AgCeLn1eemxhqjNsk6ygCXCtiNXNgckFEfKj+/JsdMG1+z/Zv+WpxPuH6MUjzRIaJWpv9G9XjbEWXf3lwGoJQCjPCJJssb5NupJ5ndLAs7SzyzmoxhKmKooLyts3li3SxcOATmTQzom7e+gRsvumJhRyoOVsao0gA+pyffBAbuBpmEMXLxFfKAC54uuFw5GT5UMpaLbVL88ZWBwczZcF4K7kbwgLylPqYy8s75QF2FDKNVK1E9KtFhvGYxC6i6akREgNTJk/Bl4dSJaP20USmW+sU+8RYyJLJvaUNLH+i8nLmW9O8huk3iTGFVlDTLHWFYjPPiIqLmddWMp2/qzp2yogeO7kU7xro/934uUqz7+gAc2zhEzMTxwqZhJCFoC6eQyhQEPGuL1ieW1Yw231SqCRQFi+F4zF4oA6JjG1yu2T158r8pkd03jUZS5hyqpRbr6ndysj/h16YNIU+xwuKTTdoFVe6kuTmqos7OpGir95cIpkRS26m8dR4YUsDhhogWzVqWTOMLmmItSRotsdhjBtbevCNAxP90DT+hs21qY8EtiGLc10OELI30tPhgYvshhVmgUtUYW3RmAM+TcxK06RMhThEMqYUbZr57GOxPepKPctEvowOePISIvTiW0qjmrBFXLuthRmwOKFE/Lp13jNqvIsKmU7be2cEh7ZCqaJ9XdicdEmZsAxqkh3PGGRpDSlwas=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: yas-openai-api-key-secret
      namespace: yas-preview
