---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: yas-openai-api-key-secret
  namespace: yas-preview
spec:
  encryptedData:
    OPENAI_API_KEY: AgBS8nDYV+ctzxskOw5nqnUS6NSe1h0dmolpT2MKCmuTqmgLjVgLgFz0htAfH62zSAbO8yVO4n7rBlqZjU7Bfa7xkKlQFP8NDzCSBtWdr+QQDyLvEqTchz3UWjwUZTOeR+bJHqPOulmWRRT+94Tpn9lqGqI0oziaQBjPRVmGHp2F8oYodi+m7OdGvfkUgnkF4VzFEWy6dl7Xy8IKw3s8iwYYA+y5B2q3/8qF1q0ZxRvPxtLvUEVcT4ajoDykmjpWVjid8FB2CNRGDnYtfQ/uwKUXo/yV5P7YTliyoS2ID9n/m4n1f18jcQc/yVDShG5BhWcrMFWOCppEQrmHnYLdFP9Ph2iiUqGa00xBRGVld7/kkFPhBGDX+3fW0FsXDMUqHI4O+cXpGxzu730D8/fGb8owC7WiUr4TZGE/uVSufFT5t4uQU0KIL/YT9yHFfkfWnY1Sn/TqSLctFuRKcv+ggFa5rb8VsX3AndJiqvnFUzzylSH0iBSCPC0TsijSaOAqt4ZG5TKIBNzHlGcKLuDUMLLDmvg0+fa8Z3G7H2ZLelCxUHWGQvAKyNhKjlArL9i4nACna9MjUkCR999Ozrx7fKOIdwEpeH7esdBtTaoZa2dCm5m/2YMwTxKc1Q6sMQiedK5W6zyZS7CCvfIEH9cvWaNK5pwZtzem1DboT9VJq/6IM6aIMjqBMZbsB4kXpexIUf4OnhA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: yas-openai-api-key-secret
      namespace: yas-preview
